contiki-os/contiki

core/net/rpl/rpl-timers.c

The special value 0 of DIO Redundancy means that DIO suppression mechanism is disabled instead of triggered immediately as currently done.
<pre>
In RPL, when k has the value
of 0x00, this is to be treated as a redundancy constant of
infinity in RPL, i.e., Trickle never suppresses messages.
</pre>

Allow disabling of DIO suppression as required by RFC

---

core/net/rpl/rpl-icmp6.c

When a no_path DAO is received, an internal flag is set in the parent structure to not set again the DAO lifetime in case a redundant no-path DAO is received. However when a non no-path DAO is received the flag is not reset. This cause that all subsequent no-path DAO are ignored

Reset nopath_received flag when new DAO is received

---

core/net/packetbuf.c

This PR aligns packetbuf on 32-bit rather than 16-bit, which is required for platforms such as the OpenRISC that does not support non-aligned 32-bit word access.
I would also expect this to make memcpy and memcmp potentially faster on Cortex-M3 and other 32-bit CPUs.

Align packetbuf on an even 32-bit boundary

---

core/net/ipv6/uip-ds6-nbr.h
core/net/rpl/rpl-dag.c
core/net/rpl/rpl-mrhof.c
core/net/rpl/rpl-of0.c
core/net/rpl/rpl.h

This PR is for moving where the ETX is stored. Today it is in the RPL parents which works well until a global repair is made - then the ETX is gone - which make the global repair do a very bad job at repairing and finding the best parent. By moving to ds6-nbr which is then stored as long as the neighbor is there - independent of RPL state - this information will be kept during the global repair and RPL can pick the best parent with up-to-date information on ETX.

moved ETX storage variable from RPL to ds6-nbr

---

core/net/rpl/rpl-dag.c

This PR makes sure that nodes in the RPL network pick up new configuration of trickle timers and route default lifetime at a global repair. This makes the whole network run the same settings as the RPL Root when it is changing the configuration (I have had problems getting all the nodes in a network to update timers and route-lifetime when updating the RPL Root with new config in a already deployed network).

fixed so that trickle timer and route lifetime rpl config is updated at global repair

---

core/net/ipv6/uip-ds6-route.c

This PR make the routing table check that the nexthop we are trying to add is different than the nexthop already   in the routing table for the specific route entry. If that is the case it skips doing both a remove and an add.

avoid updating routes that already are correct

---

platform/z1/Makefile.common

Remove leading zeros to avoid node id being treated as octal

Remove leading zeros from node id

---

cpu/cc253x/dev/uart0.c

[ cc253x ]  Fix the peripheral I/O Pin Mapping with RTS and CTS in P0SEL in cpu/cc253x/dev/uart0.c

Fix the uart0 flow control register P0SEL setting in cpu cc253x

---

cpu/cc2538/dev/cc2538-rf.c

When using the cc2538-rf driver without using radio duty cycling I discovered that if an error occurs, the radio is switched off, reinitialized, but never switched back on again, which killed all radio reception until the stack decided to switch the radio on again for any reason.
Also, the channel was reset to the default in this case, instead of what was last set. 
Thirdly, the radio was switched on whenever channel was changed, even if radio was currently off. This makes sleepy nodes switch on their radio of for instance using multichan.
* This patch stores the RF channel internally in the module and always reinitialize to the last set value.
* This patch only switch on radio when chaning channel iff the radio was on
* This patch switches radio back on after reinitializing

CC2538 RF driver issues x3

---

tools/cooja/java/org/contikios/cooja/plugins/analyzers/IPHCPacketAnalyzer.java

This pull request fixes a wrong interpretation of some fields in the packet analyzer of Cooja, when dealing with a compressed header.
According to RFC 6282 section 3.2 (https://tools.ietf.org/html/rfc6282#section-3.2) a 0 in the address compression fields (SAC and DAC) indicates a stateless compression, not a stateful one.

Fix: Cooja HC packet analyzer fix for SAC and DAC fields

---

core/net/rpl/rpl-icmp6.c

There is a overlap between RPL_DIO_MOP_MASK and RPL_DIO_PREFRENCE_MASK.
according to rfc 6550, RPL_DIO_MOP_MASK should be 0x38

change value of RPL_DIO_MOP_MASK 

---

core/net/ipv6/multicast/roll-tm.c
core/net/ipv6/multicast/roll-tm.h
core/net/ipv6/multicast/smrf.c
core/net/ipv6/multicast/smrf.h
core/net/ipv6/multicast/uip-mcast6-engines.h
core/net/ipv6/multicast/uip-mcast6-route.c
core/net/ipv6/multicast/uip-mcast6-route.h
core/net/ipv6/multicast/uip-mcast6-stats.c
core/net/ipv6/multicast/uip-mcast6-stats.h
core/net/ipv6/multicast/uip-mcast6.h

This pull:
* Creates a doxygen group and adds multicast files to it, so that documentation appears within the module hierarchy, rather than simply under files
* Documents plenty of functions, macros, constants, data types which were previously undocumented
* Re-structures some doxygen comments to improve structure and readability

Tidy-up multicast documentation

---

platform/avr-zigbit/Makefile.avr-zigbit
platform/avr-zigbit/contiki-avr-zigbit-main.c

I had some reference errors for avr-zigbit platform.
I added to the makefile some necessary files and from contiki-avr-zigbit-main.c I commented the rime-stack initializations and modified the baud rate.

Fix: Misconfigurations to compile for avr-zigbit platform

---

apps/mqtt/Makefile.mqtt
apps/mqtt/mqtt.c
apps/mqtt/mqtt.h
examples/cc2538dk/mqtt-demo/Makefile
examples/cc2538dk/mqtt-demo/Makefile.target
examples/cc2538dk/mqtt-demo/README.md
examples/cc2538dk/mqtt-demo/mqtt-demo.c
examples/cc2538dk/mqtt-demo/project-conf.h
regression-tests/15-compile-arm-apcs-ports/Makefile

This pull adds:
* An engine for MQTT 3.1 under the `apps` directory
* An example use of the engine for the CC2538DK platform
* A travis test for the engine + example
The code has been tested on Srf06+CC2538EM with mosquitto as well as with IBM's quickstart service through NAT64 with 6lbr.
The engine supports MQTT QoS levels 0 and 1.

Mqtt contrib

---

apps/er-coap/Makefile.er-coap
apps/er-coap/er-coap-engine.c
apps/er-coap/er-coap-engine.h
apps/er-coap/er-coap-observe-client.c
apps/er-coap/er-coap-observe-client.h
examples/er-rest-example/er-example-observe-client.c
examples/er-rest-example/project-conf.h
examples/er-rest-example/server-client-observe.csc

This pull request extends Erbium with client-side support for CoAP Observe.
An example showing how to use the new functionality is also included.
As requested by @mkovatsc, the new code is not compiled by default. To enable it the `COAP_OBSERVE_CLIENT` macro must be defined equal to 1. On a Tmote Sky, this will increase the Text section by ~1100 bytes and the BSS section by ~300 bytes.
Happy Holidays! :)

Erbium: client-side support for CoAP Observe

---

dev/cc2420/cc2420.c

Make it possible to set and get the CC2420's CCA threshold through the extended radio API.

Implement set/get of the CCA threshold for CC2420

---

platform/cc2538dk/dev/button-sensor.c

It's now more convenient to add new buttons. If button is redirected to another port, this could doesn't need to be changed. The code itself now is more clear.

Make the CC2538DK button sensor clearer to work with

---

core/net/rpl/rpl-dag.c

In the current code, the No-Path DAO is send, even when the the node has no preferred parent (which happens when it first joins a DODAG), this cause a malformed DAO to be send.
Updated 3/3: The previous PR comment was completely wrong (but the title was right)

Send no-path DAO only when the dag has a preferred parent

---

cpu/msp430/Makefile.msp430

Original discussion [Here](http://sourceforge.net/p/contiki/mailman/message/32628670/)
Tested with json-ws test application at examples/ipv6/json-ws.
Original:
> websense-z1.z1 section `.far.text' will not fit in region `far_rom'
> region `far_rom' overflowed by 376 bytes
Amended:
msp430-size websense-z1.z1 
>   text    data	    bss	    dec	    hex	filename
>  48260	    594	   5936	  54790	   d606	websense-z1.z1

Changed code region to any

---

platform/z1/dev/sht25.c

Duplicated condition removed, the configuration should only be done on SENSORS_ACTIVE, to ble used from the SENSORS_ACTIVATE and SENSORS_DEACTIVATE macro.

Removed duplicated condition in sht25 configuration

---

cpu/cc2538/Makefile.cc2538
cpu/cc2538/dev/i2c.c
cpu/cc2538/dev/i2c.h

Originally from PR #677, just uncristified, made some functions static and added burst modes for sending and transmitting.  Tested with the SHT25, TSL2563 and TMP102 sensors using the Re-Mote platform (CC2538 + CC1120 based).

I2C driver taken from PR #677, made functions static and aded burst modes

---

core/sys/timer.c

I've seen several people (including me) having problems with the behavior of `timer_reset()` when it is invoked before the timer expired.
The problem was already discussed in #293 more detailed.
In my opinion adding a simple note should be the easiest solution so far as it does not introduce further computation overhead would but gives a hint for (doc-reading) users.

Note that timer_reset() must not be executed before timer expired

---

dev/enc28j60/enc28j60.c
dev/enc28j60/enc28j60.h

The ENC28j60 is a common Ethernet chip used by both the new OpenMote platform (http://www.openmote.com/), the do-it-yourself Thingsquare CC2538 setup (https://github.com/thingsquare/hardware/blob/master/ti/cc2538dk/assembly/README.md), and other upcoming platforms.
This pull request adds Thingsquare's ENC28j60 driver to the Contiki tree.

ENC28j60 Ethernet driver code

---

examples/z1/Makefile
examples/z1/test-reed-sensor.c
platform/z1/dev/reed-sensor.c
platform/z1/dev/reed-sensor.h

This pull request adds a basic driver for a Reed Sensor with two basic operation modes:
* Polling: user polls the sensor for a status update.
* Event-based: a timer runs in the background and post an event if the status (closed/open) has changed.
There's also a minor fix to the SHT25 driver to eliminate some warnings.

Added Reed Sensor driver, example, and minor fix to the SHT25 sensor driver

---

core/net/ipv4/uip.c

`net/ipv4/uip.c` will not even be included in the list of sources in the first place if we are building with NETSTACK_CONF_WITH_IPV6 (CONTIKI_WITH_IPV6). Thus, there is no longer a need to wrap the entire source code in an #if guard.
Closes #935

Remove unnecessary #if guards

---

apps/dhcp/dhcp.c
apps/netconf/netconf.c
core/contiki-net.h
core/net/ip/resolv.c
core/net/ip/resolv.h
core/net/ip/uip-nameserver.c
core/net/ip/uip-nameserver.h
core/net/ipv6/uip-nd6.c
core/net/ipv6/uip-nd6.h
cpu/6502/ipconfig/ipconfig.c
cpu/6502/lib/config.c
platform/apple2enh/contiki-main.c
platform/atarixl/contiki-main.c
platform/c128/contiki-main.c
platform/c64/contiki-main.c
platform/win32/contiki-main.c

This is an update of https://github.com/contiki-os/contiki/pull/643, which introduces a nice new API for the DNS resolver library and adds support for RDNSS. Unfortunately the original pull request failed on some platforms as the code was not optimized for the case when there was only one DNS server configured.
This updated pull request adds a special-case optimization for when we only have one DNS server which makes the code smaller in that situation.
Ping @lebrush and @oliverschmidt.

RDNSS support, again

---

core/net/rpl/rpl-conf.h
core/net/rpl/rpl-ext-header.c

Although Hop-by-hop option is extremely useful, it is not mandatory in RPL. This PR allows to deactivate properly RPL HBH

Allow user configuration of RPL hop-by-hop option

---

cpu/cc26xx/dev/cc26xx-rf.c

This was pointed out in TI's E2E forum:
https://e2e.ti.com/support/wireless_connectivity/f/158/t/415130
The CC26xx RF will reject frames with version == 1.
Until a while ago, Contiki would send out frames with version==0 (`FRAME802154_IEEE802154_2003`), but as of #557 (19c9ef0a) we are sending out 1 (`FRAME802154_IEEE802154_2006`). 
I've been using the hardware with an older version of 6lbr, which still sends out version==0 and for that reason I had not noticed this up to now.
This pull updates the CC26xx RF driver to accept frames with version==1.
This is basically a very very nasty bug: CC26xx will refuse to talk to any device using our current master (including a 2nd CC26xx), so I'll be merging this immediately as soon as travis passes.

Fix CC26xx RF frame filtering for frames with version==1

---

dev/enc28j60/enc28j60-ip64-driver.c
dev/enc28j60/enc28j60-ip64-driver.h

This pull request contains the glue code for using the `enc28j60` Ethernet driver for the IP64 module.

IP64 bindings for the ENC28j60 Ethernet driver

---

cpu/cc2538/dev/i2c.c

While working on the clock system of the CC2538 (wanted to make it run at 32 MHz) i found a bug in the clock computation of the i2c module.
This is the second, hopefully clean pull request for this issue.

cc2538 i2c bug in clock computation

---

core/net/ipv6/uip-ds6-route.c

We have no guarantee that `current_nexthop` is not null even when `r` is a valid entry. On platforms with memory protection, `memcpy` on a null pointer can hurt. Found this bug while playing with a regression test with native compilation.

Added missing sanity check in uip-ds6-route.c

---

examples/cc2538dk/sniffer/netstack.c

The CC2538 sniffer example is currently broken. The RF is forever off, therefore what we have is a sniffer which doesn't sniff a whole lot...
The CC2538 RF driver's init() does not put the RF in RX mode.
* When using NullRDC, NETSTACK_RDC.init() will ultimately call NETSTACK_RADIO.on();
* The sniffer example used to work by accident: set_channel() would leave the RF unintentionally on. This was fixed in #946, but as a consequence the sniffer stopped working.
This pull changes the sniffer example to explicitly put the RF in RX after initialisation.

Turn on the CC2538 RF explicitly in the sniffer example

---

.travis.yml
platform/cc2538dk/README.md
regression-tests/15-compile-arm-apcs-ports/Makefile
regression-tests/18-compile-arm-ports/Makefile

As per the subject, the objective of this pull is to test cc2538dk with the toolchain recommended in the platform's README (GNU Tools for ARM Embedded Processors), instead of the one that was being used two years ago (Sourcery G++ Lite 2008q3-66). The job using the former is currently disabled on Travis, due to being broken for the ev-aducrf101mkxz platform.
With this in mind, this pull:
* Moves cc2538dk tests to the arm-aapcs job, which is the one using GNU Tools for ARM Embedded Processors
* ~~Re-enables the job in `.travis.yml` and~~~ changes `BUILD_ARCH` from 'arm'  to 'arm-aapcs' for clarity
* ~~ev-aducrf101mkxz tests remain disabled, but this is now done within the job's Makefile rather than in `.travis.yml`. Re-enabling tests for this platform will be a trivial patch.~~
And a quick …

Test cc2538dk with the recommended toolchain

---

examples/cc26xx/cc26xx-web-demo/httpd-simple.c

This pull proposes improvements to the HTTPD part of the CC26xx web demo example:
* Prettifies top matter: [[ link ]](#) becomes [ [link](#) ]
* Send the correct filename as part of the HTTP POST when clicking the action button in HTML forms.
* Correctly parses the first line of a POST request to extract the target filename
* Returns the correct value for the HTTP "Location:" header, used by the browser to retrieve a fresh copy of the respective page after configuration updates.

Improve HTTPD in the CC26xx web demo

---

cpu/cc26xx/dev/cc26xx-rf.c

The CC26xx RF driver puts the CM3 to sleep while waiting for TX to finish.
Theory: The CM3 wakes up by the TX_DONE interrupt, checks that TX has finished and continues / returns.
In reality though, this logic is broken: The TX command's status field is updated by the CPE _after_ throwing TX_DONE. As a result, the CM3 wakes up, inspects the command's status field, thinks that TX is still ongoing and goes back to sleep until something else wakes it up (usually an RTC tick).
The result of this is that `.transmit()` takes way too long to return, the exact duration depending on exactly when the next RTC tick happens to take place. The final outcome of this is that ContikiMAC's TX only sends a small number of strobes, which in turn increases packet loss.
With this pull, we change the wakeup …

Fix "CC26xx delayed wakeup after RF TX" bug

---

examples/cc26xx/cc26xx-web-demo/project-conf.h
platform/srf06-cc26xx/contiki-conf.h
platform/srf06-cc26xx/sensortag/button-sensor.h
platform/srf06-cc26xx/srf06/button-sensor.h

This pull makes some small changes to the CC26xx platform code, so that slip-radio and rpl-border-router will compile off-the-shelf.

Enable slip-radio and rpl-border-router for CC26xx

---

core/net/rpl/rpl-dag.c

When the maximum number of DODAG for a given instance is reached, the current code delete that instance.

Do not delete instance when a new DODAG can not be created

---

core/net/rpl/rpl-dag.c

When a node becomes a DODAG root within a given instance, it must leave any DODAG it has joined previously, not only the current DODAG and remove any references to the known DODAGs.

Remove all the DODAG from the instance when the node is set as Root

---

core/net/rpl/rpl-conf.h
core/net/rpl/rpl-dag.c
core/net/rpl/rpl-icmp6.c
core/net/rpl/rpl-private.h
core/net/rpl/rpl-timers.c
core/net/rpl/rpl.c
core/net/rpl/rpl.h
regression-tests/12-rpl/09-rpl-probing.csc

This PR implements an optional probing mechanism for RPL. Nodes will periodically send a unicast message (DIO or DIS) to one of their best parents (mostly the current preferred and second best parent, sometimes also the third best), to keep link metric estimates up to date. The main benefit is that it avoids switching to a parent which is seemingly good but has an outdated link metric (or never updated, stuck at its initial value). 
When probing and refreshing our link estimate to the second best parent **S**, there are three possible consequences:
(1) the link estimate remains roughly unchanged, **S** can be used safely as a backup in case the current preferred parent fails
(2) the link proves better than we thought, RPL may chose to switch parent a now use **S**
(3) the link proves …

RPL probing

---

tools/cooja/apps/avrora/src/org/contikios/cooja/avrmote/MicaZMote.java
tools/cooja/apps/avrora/src/org/contikios/cooja/avrmote/interfaces/MicaClock.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/MspMote.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/MspClock.java
tools/cooja/java/org/contikios/cooja/contikimote/interfaces/ContikiClock.java
tools/cooja/java/org/contikios/cooja/interfaces/Clock.java

This pull requests implements support for motes that progress with different speed.
Currently the clock of all simulated motes is perfectly synchronized with the simulation time. In reality, the clocks of two nodes will drift apart (hardware imperfections/temperature differences/etc.). This PR enables to simulate and test systems where the clocks are not perfectly aligned. 
Each the mote clock interface has now the possibility to set a deviation factor between 0.0 and 1.0. A factor of 1.0 means that the clocks will be perfectly aligned with the simulation time. 0.5 means that the mote is running in half speed. 
Standard values are 1.0 and there is no gui to change the value, but it is accessible through the java interface for the motes.

Time Drifting Motes

---

platform/srf06-cc26xx/README.md

TI released a new version of CC26xxware this week and our CC26xx port will fail to build with this version - see the discussion in #1058.
This pull merely updates the platform's README:
* It states the correct version number explicitly
* It provides a link to a page where the user can find a download link for this version
I am becoming increasingly convinced that we should pull CC26xxware as a submodule, which is something I will probably do when I update the port to use the latest version. So this is just a temporary counter-measure.

Update CC26xxware download instructions

---

cpu/cc2538/Makefile.cc2538
cpu/cc2538/startup-gcc.c
platform/cc2538dk/Makefile.cc2538dk

This pull proposes moving CC2538's `startup-gcc.c` to the CPU dir. This file contains startup code and initialises the vector table.
@adamdunkels suggested this move a few months ago, but I had some concerns about the various `#if` statements used to manage some of the interrupt handlers. Looks like they were unfounded, but please take a look if you will.
In the longer term, I think we should use weak symbols here for handlers. It should help get rid of those `#if`s altogether.
This pull also sneaks in a minor code style fix.

Move cc2538 startup-gcc.c to the CPU dir

---

.travis.yml
cpu/cc26xx/Makefile.cc26xx
platform/srf06-cc26xx/README.md

As per the discussion in #1058, TI's Flash Programmer seems to dislike 03 records in ihex files. As a result, the `.hex` file generated by the CC26xx build system cannot be used with Flash Programmer.
This pull changes the CC26xx build system as follows:
* We `objcopy` from the `.elf` to an intermediate `.hex` ~~which has all addresses offset by `0x200000`. This forces `objcopy` to only use 04/05 records instead of 02/03.~~
* We use `srecord` to post-process this intermediate hex. This produces a final hex file that uses 32-bit linear addresses ~~by offsetting everything back by `-0x200000`. This produces a final `.hex` which has correct addresses, but which only uses 04/05 records.~~
This final `.hex` was used successfully to program Srf+CC2650 EM as well as the SensorTag with …

Produce ihex files usable with TI's Flash Programmer

---

cpu/msp430/Makefile.msp430

Currently there is an linker error when compiling with debug information.
This is only the case for dwarf (the default). Everything is fine with
stabs, thus allowing to debug and use all the other nice tools like
"objdump -S".

[MSP430] Add gstabs debug information (dwarf is broken)

---

cpu/cc2538/spi-arch.h

The current SPI_FLUSH macro first waits for the SPI RX FIFO to fill with something. So if an application makes a SPI_FLUSH call and the RX FIFO happens to already be empty, the application stalls.

[CC2538] Fix SPI_FLUSH

---

platform/cc2538dk/README.md

Document the URL of the older Sourcery G++ Lite 2008q3-66 arm-none-eabi
toolchain mentioned by README.md so that users can easily find it if
needed.

cc2538dk: README: Add URL of Sourcery G++ Lite 2008q3-66

---

tools/cooja/apps/mrm/java/org/contikios/mrm/MRM.java
tools/cooja/java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java
tools/cooja/java/org/contikios/cooja/radiomediums/DGRMDestinationRadio.java
tools/cooja/java/org/contikios/cooja/radiomediums/DirectedGraphMedium.java
tools/cooja/java/org/contikios/cooja/radiomediums/UDGM.java

* Fix CCA detection in Cooja in the case when the receiver switches on the right channel during an ongoing transmission. Always add a connection on transmission, even when the channel is not correct. Initially the connection is in a dormant state; this mimics what Cooja is doing when the receiver radio is turned off; when the receiver is turned on and switched to the right channel, `updateSignalStrengths()` is called, and the connection starts to receive PHY-level traffic.
* Add "channel" property for DGRM edges.
* Avoid cross-channel interference on DGRM and MRM radio mediums
Test applications are available here: https://github.com/atiselsts/contiki/tree/master/examples/multichannel-test

Improve multichannel support in Cooja

---

cpu/cc2538/clock.c
cpu/cc2538/dev/i2c.c
cpu/cc2538/dev/spi.c
cpu/cc2538/dev/sys-ctrl.c
cpu/cc2538/dev/sys-ctrl.h
cpu/cc2538/dev/uart.c
cpu/cc2538/lpm.c

Allow for configuration of processor speed using configuration parameters for system and I/O clock. (Re-pull request for https://github.com/contiki-os/contiki/pull/1044). Added two new macros in sys-ctrl.h (SYS_CTRL_CONF_SYS_DIV and SYS_CTRL_CONF_IO_DIV) and modified clock dependent modules accordingly.

CC2538: Allow for configuration of processor clocks

---

core/cfs/cfs-coffee.c

Remove redundant assignment (reported by CppCheck)

Remove redundant assignment

---

platform/z1/dev/tmp102.c

Hello,
When using this code:
(int8_t)tmp102_read_temp_x100() / 100
Only the first value is casted into a `int8_t` type.
`tmp102_read_temp_x100()` returns the temperature in Celcius * 100. Most of
the time this value will be lower than -2^7 or higher than 2^7 (+/- 1.27°C).
Best Regards,

Z1: tmp102: simple: fixed wrong cast

---

cpu/cc2538/cc2538.lds
cpu/cc2538/startup-gcc.c

Make the initialization of the .data and .bss output sections safer, faster, smaller, simpler and more maintainable. See the commit messages for details.
This is a follow-up of #581.
For `memcpy()` vs. `rom_util_memcpy()` speed/size comparison, see https://github.com/contiki-os/contiki/pull/426#issuecomment-28699372.

cc2538: Fix and improve .data/.bss initialization

---

platform/cc2538dk/README.md

* The current version of the README points to a wrong URL for the LUFA Virtual Serial driver.
* A driver is nowadays provided by TI through CC2538 Foundation Firmware
Thus, this pull updates the LUFA driver URL, documents that TI also provides a driver and adds a link to the CC2538 Foundation Firmware download page

Update the CC2538DK README about a Win CDC driver

---

core/net/rpl/rpl-conf.h
core/net/rpl/rpl-dag.c

In high density network with DIO suppression activated it may happens that a node will never sent a DIO once the DIO interval becomes high as it has heard DIO from many neighbors already. As the default route to the preferred parent has a lifetime reset by receiving DIO from the parent, it means that the default route can be destroyed after a while.
This PR add the possibility to create default route with infinite lifetime, thus securing the upstream route. The default value is to not enable it though.
(It should be noted that TinyOS uses infinite lifetime for upstream routes in RPL)

Allow rpl default route lifetime to be infinite

---

core/net/rpl/rpl-dag.c

Currently Contiki only updates rank of parent belonging to the active DAG, parents belonging to other DAGs keep their initial rank even when receiving DIO from them.
This PR adds a mechanism to update the rank of these parents and also prevent the DODAG Root to join another DAG. With #912, a node can be part of MAX_DODAG_PER_INSTANCE DODAGs and drops dead ones.

Multi DODAG support

---

tools/z1/z1-bsl-nopic

The Zolertia Z1 bootloader script will work only with Python2 and was broken due to mixing spaces and tabs.

Fix z1-bsl-nopic

---

Makefile.include

The commit bddd96d5c83323fb3f99835149af5ab1058c10bb "Removed all module
makefiles. Instead, all .c files in a module directory are compiled."
made the MODULESSUBST variable useless, but it did not remove it, so do
it now.

Makefile.include: Remove unused MODULESSUBST

---

cpu/cc2538/dev/uart.c

This function is only supposed to be used by uart.c, so it should be
static.

cc2538: uart: Make uart_isr() static

---

platform/win32/contiki-main.c

This is i.e. necessary to have the file based webserver-example successfully read 'contiki.gif'.

Set Win32 file i/o to binary mode.

---

tools/6502/Makefile

- By end of Jan 2014 SuperTweet.net was shut down (http://supertweetnews.140plus.com/). So Breadbox64 has come to an end for sure :-(
- The email app - or rather email sending app as it is SMTP only - can't be used anymore since nowadays everybody uses some "strong" authentication for SMTP session logon (thanks NSA).
- The ftp client app isn't very useful as it supports only download - for which the WGET app is almost always more useful for. But more important it doesn't support PASV which is more or less the only supported mode nowadays (especially over NAT).

Removed obsolete apps from retro distribution.

---

core/lib/aes-128.c
core/lib/aes-128.h

Made AES-128.set_key's argument const, thus helping to avoid compiler warnings.

made AES-128.set_key's argument const

---

core/net/ip/uip-debug.c

If DEBUG is enabled in uip-ds6-nbr, the code crashes when trying to print a NULL lladdr. A NULL lladdr occurs with INCOMPLETE neighbor state.

Check pointer in uip_debug_lladdr_print

---

cpu/cc2538/dev/watchdog.c
cpu/cc253x/8051def.h

The CC2538 WDT cannot be stopped once it has been started.
The CC2530/1 WDT can be stopped if it is running in timer mode, but it cannot be stopped once it has been started in watchdog mode.
Both chips currently provide "dummy" implementations of `watchdog_stop()`, one does nothing and the other one basically re-maps `_stop()` to `_periodic()`.
This was originally done in order to provide implementations for all prototypes declared in `core/dev/watchdog.h`. In hindsight and as per the discussion in #1088, this is bad practice since, if the build succeeds, the caller will expect that the WDT has in fact been stopped, when in reality it has not.
Since the feature (stopping the WDT) is unsupported by the hardware, this pull removes those dummy implementations. Thus, we will now be able to …

Remove CC2530 and CC2538 dummy watchdog_stop()

---

apps/dhcp/dhcp.c
cpu/6502/ipconfig/ipconfig.c

In order to have DHCP retries actually work dhcpc_appcall() must be called for PROCESS_EVENT_TIMER too.

Fix DHCP client retries.

---

core/net/ip/uip-debug.c

Change all printf into PRINTA in uip-debug.c; remove compilation warning (an array can never be a NULL pointer) and move addr check after local variables definition in uip_debug_ipaddr_print() for older compiler.

Change all printf into PRINTA in uip-debug.c and remove compilation warnings

---

cpu/cc26xx/dev/cc26xx-rf.c

After making this change I am able to get ~3x higher max data throughput when sending packets with RIME (as quickly as I can) on ContikiMAC (with duty cycling enabled on the transmitter, duty cycling disabled on the receiver and a CHANNEL_CHECK_RATE of 8) than without these changes.
This improvement seems to be caused by significantly reducing the number of false positive CCAs. These false positives then limit the TX rate by causing ContikiMAC to detect collisions before sending.
In addition, I have found that this also reduces the number of false positives in the receiver routines of ContikiMAC which will result in less power consumption on duty cycling receivers.
I am somewhat concerned that these changes will lead to less reliable operation in very noisy environments but I think that …

turned on correlator in radio packet filter

---

cpu/6502/net/cs8900a.S
cpu/6502/net/lan91c96.S
cpu/6502/net/w5100.S

There are scenarios in which it is beneficial to search for an Etherne chip at several i/o locations. To do so the chip initialization is performed at several i/o locations until it succeeds. In order to allow for that operation model the i/o location fixup needs to be repeatable.
Note: This won't work with the RR-Net because the fixup bits overlap with the chip i/o bits.

Allow fixup to be repeated.

---

cpu/cc26xx/dev/cc26xx-rf.c

Setting bAutoFlushCrc=1 so that the radio co-processor will automatically drop packets with bad crc.
Created as per discussion in #1140. 
I've confirmed that this fixes the problem of corrupt frames propagating up to the application layer.

CC26xx autoflush bad crc packets

---

examples/cc2530dk/cc2531-usb-demo/cc2531-usb-demo.c

No code change, just a change to the descriptive comment in the cc2531 usb demo

Clarified that a newline is needed for the echo

---

core/net/mac/contikimac/contikimac.c

This pull changes ContikiMAC so that it allows the project / platform to provide values for `CCA_SLEEP_TIME` and `LISTEN_TIME_AFTER_PACKET_DETECTED`.
This is useful for sub-ghz operation.
This has been shamelessly stolen from the [Mountain Sensing project](https://github.com/feshie/contiki)
@heliosfa @kmartinez

Make ContikiMAC more configurable

---

cpu/cc26xx/dev/cc26xx-rf.c

Enabled the RX_NOK interrupt, if DEBUG or CC26XX_DEBUG_CRC are set true, for the purpose of monitoring packets with bad CRC.
With bAutoFlushCrc now set true, we can't monitor bad CRC packets without enabling RX_NOK (we could also monitor the radio's  nRxNok counter but then we can't see the bad CRCs as they occur).

CC26xx - Enable RX_NOK on DEBUG builds

---

core/net/ipv6/multicast/roll-tm.c

The Trickle Multicast ICMP packet handler was not resetting uip_len to zero,
so all incoming TM ICMP packets were forwarded overloading the network.

[multicast] Do not forward every incoming TM ICMP

---

cpu/cc253x/dev/cc2530-rf.c

function pointer typesig says const, function declaration doesn't

fix minor warning in cc2530-rf driver

---

apps/er-coap/er-coap-engine.c

When a client sends a CoAP request without specifying a block2 size, the server should choose one.
The CoAP engine sets this to `REST_MAX_CHUNK_SIZE`, which is not a valid block size as it is not a power of two.
As a result, resources can return a payload that isn't a valid block size.
Some clients (Californium is affected, Cooper does not seem to be) do not check the block2 size with the actual payload size, and can therefore end up with duplicated data.
For example, on the Z1 platform:
* An initial CoAP request is sent without a block2 header
* The CoAP engine calls the resource handler with `preferred_size` set to `REST_MAX_CHUNK_SIZE`, in this case 48.
* The resource returns a payload of size 48.
* The client receives the payload, and stores all 48 bytes.
* The client sends a further …

Fix default CoAP header block2 size

---

cpu/6502/6502def.h
cpu/6502/sys/clock.c
platform/apple2enh/sys/clock.c

The DNS resolver requires 1/4 sec clock resolution. The retro targets had a 1/2 sec clock resolution (optimized for the 1/2 sec TCP timer) resulting in DNS resolver timeouts being 0. Therefore the retro target clock resolution is now increased to 1/4 sec.

Adjusted retro target clock to "new" DNS resolver.

---

core/net/rpl/rpl.c

The function ```rpl_ipv6_neighbor_callback``` is called when a neighbour has been removed or a new one has been added to the ```ds6_neighbors``` table. However, the ```rpl_ipv6_neighbor_callback``` always prints ```RPL: Removing a neighbor ...``` when ```DEBUG``` is enabled in ```rpl.c```. This PR changes the print statement to don't misunderstand the NBR event.
Perhaps, it would be nicer to change the definition of ```NEIGHBOR_STATE_CHANGED(n)``` to ```NEIGHBOR_STATE_CHANGED(neighbor, state)``` and then within the RPL callback function we could understand if a NBR has been added or removed. I could change the functions to work that way, but in that case when removing a NBR which state should we send in the ```NEIGHBOR_STATE_CHANGED``` function? I guess we could send ```NBR_INCOMPLETE``` …

Changed RPL IPv6 NBR Callback Print Statement

---

.travis.yml

Up to now we were using the LibreOffice 4.3 ppa (ppa:libreoffice/libreoffice-4-3) to install doxygen, but the LibreOffice Packaging team appear to have removed it. As a result, our doxygen build suddenly started failing (https://travis-ci.org/contiki-os/contiki/jobs/74366993) with:
```
gpg: "tag:launchpad.net:2008:redacted" not a key ID: skipping
W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 83FBA1751378B444
WARNING: The following packages cannot be authenticated!
doxygen
```
This changes the ppa we use to LibreOffice 4.4.x.

Use a different LibreOffice ppa to install doxygen

---

cpu/cc26xx/dev/cc26xx-rf.c

Fixes various bugs and stylistic issues with the `read_frame` function.
In particular:
- Fixed a race condition caused by using the dataEntry after setting status to PENDING
- Fixed general misuse of the packet length
- made some stylistic changes

Cc26xx fix read frame implementation

---

README.md

This PR updates `README.md` to show the build status of the current master rather than latest build status (can be any pull request, i.e. can show "fail" while the master does pass the test). The link also points to Contiki branches rather than latest build.

Fix Travis icon in README.md

---

dev/cc1200/cc1200-802154g-863-870-fsk-50kbps.c
dev/cc1200/cc1200-arch.h
dev/cc1200/cc1200-conf.h
dev/cc1200/cc1200-const.h
dev/cc1200/cc1200-rf-cfg.h
dev/cc1200/cc1200.c

In our company's effort to develop a new platform (CC2538 + CC1200 + ENC28j60) i hereby commit the driver for the CC1200 radio. Even if it borrows some ideas e.g. from the cc1120 or cc2538 radio driver, it was completely re-worked, is highly configurable and also supports 802.15.4g (packet length > 127 bytes). It also uses the channel spacing defined in 802.15.4g for ETSI and FCC. It is currently running stable at 50kbps (ETSI) using nullrdc mac-driver. To my knowledge it will NOT WORK with the cc1120 or cc1101 drivers at it uses at least another channel spacing. Hopefully we will be able to achieve compatibility with old (and upcoming) sub-ghz radios one day...
I would again like to raise the question if we shouldn't consider a re-work of way we handle rf transmission within contiki. As …

cc1200: New device driver for TI sub-ghz radio

---

core/net/ip/dhcpc.c
core/net/ip64/ip64-dhcpc.c

RFC2131 states on page 36 regarding DHCPREQUEST: " 'xid' from server DHCPOFFER message "
As the DHCPOFFER message uses the 'xid' from the DHCPDISCOVER message this means that the DHCP client is supposed to re-use the 'xid' from its DHCPDISCOVER for the DHCPREQUEST.

Fixed DHCP client.

---

CONTRIBUTING.md

This PR reflects internal discussions we had on a new merging policy. Overall, the policy changes two things:
* bounded idle time: after a delay of inactivity all pull requests end up closed or merged
* silent co-approval: one approval + delay with no disapproval results in merging
After merging this, I propose to update https://github.com/contiki-os/contiki/wiki/Code-Contributions with the same content as `CONTRIBUTING.md` and delete https://github.com/contiki-os/contiki/wiki/Pull-Request-Policy (content now part of `CONTRIBUTING.md` and the Code Contribution page).

New PR merging policy

---

core/sys/etimer.c
core/sys/etimer.h

This new function is similar to reset, but allows to also set a new
timeout. Thus long-term accuracy with changing timeouts is now possible.

Add function etimer_reset_set.

---

core/net/rpl/rpl.h

Removes an unused next-pointer in the RPL parent struct.

RPL: removed pointer to next parent since it is not used anymore

---

core/net/ipv6/uip-ds6.c
core/net/ipv6/uip-nd6.c

I found two bugs about the prefix diffusion in IPv6 Neighbor Discovery protocol.
It is about:
* the PIO is never sent in RA message
* problem about the return function when we add prefix in table (host version)
Sébastien

IPv6 prefix bug

---

platform/cc2530dk/contiki-conf.h
platform/cc2538dk/contiki-conf.h
platform/remote/contiki-conf.h
platform/sensinode/contiki-conf.h
platform/srf06-cc26xx/contiki-conf.h

This pull request removes the unused `RPL_CONF_MAX_DAG_ENTRIES` of `contiki-conf.h` config file.  I couldn't find this definition anywhere else.

Remove unused RPL_CONF_MAX_DAG_ENTRIES

---

platform/wismote/contiki-wismote-main.c
platform/z1/contiki-z1-main.c
platform/z1/dev/cc2420-arch.c

This PR initializes the random seed on Z1 and Wismote, and fixes CC2420 SFD timestamp configuration on Z1 (to now use the flag `CC2420_CONF_SFD_TIMESTAMPS`, as other cc2420 platforms do).

Minor fixes to Z1 and Wismote

---

platform/wismote/contiki-wismote-main.c

https://github.com/contiki-os/contiki/pull/1226 was wrongly assuming link-layer addresses of 8 bytes in `random_init` for Wismote (not an issue with the z1 code, where `node_mac` always is 8 bytes long).

Fix Wismote randon_init for link-layer addresses shorter than 8 bytes

---

core/net/ipv6/uip-ds6-route.c
core/net/nbr-table.c
core/net/rpl/rpl-dag.c
core/net/rpl/rpl-icmp6.c
core/net/rpl/rpl-private.h

This PR is spawned by the discussions on the PR #1213 . The PR moves the locking when DAO is received from its location in RPL (e.g. locking an RPL parent) to the corresponding location in uip-ds6-route module. The RPL locks was never unlocked which causes risk of ending up with a lot of locked entries in the nbr-table. Moving it to the uip-ds6-route module makes it easier to get a consistent locking / unlocking behaviour as this module removes the nbr-table entry for any neighbor that is no longer a nexthop. The locking is now made for each entry that is used as nexthop.
I also added some debug printouts for the nbr-table module that are useful when debugging locking and unlocking.

Move locking of neighbors / children from RPL to uip-ds6-route module 

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
cpu/cc26xx-cc13xx/rf-core/prop-mode.c
cpu/cc26xx-cc13xx/rf-core/rf-core.c
cpu/cc26xx-cc13xx/rf-core/rf-core.h

Fix for #1229
rf_core_cmd_done_en() was enabling the wrong irq for detecting the completion of foreground operations. This was causing cc26xx devices to not wake-up on time when calling lpm_sleep() from transmit().

CC26xx - enable correct IRQ in rf_core_cmd_done_en

---

cpu/cc26xx-cc13xx/dev/contiki-watchdog.c

I'm pushing up several changes to the CC26xx's WDT interface from my private repo.
These include:
- Added macro to make WDT timeout configurable
- Added working watchdog_stop() implementation
- Fixed the way in which the WDT is reset in watchdog_periodic()
- Enabled configuration register locking to avoid accidental changes

CC26xx - various fixes and improvements for the watchdog module

---

tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/CC2420RadioPacketConverter.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/Msp802154Radio.java
tools/cooja/java/org/contikios/cooja/motes/AbstractApplicationMote.java
tools/cooja/java/org/contikios/cooja/plugins/RadioLogger.java

Due to errors in mspsim and/or radio drivers, packets of incorrect length are sometimes transmitted. The length might be larger than the 127-byte maximum (considered negative in the current code) or not matching the actual number of transmitted bytes. This leads to wrong packet delimiting when converting from the mspsim-level stream of bytes to Cooja-level packets, causing unhandled exceptions that terminate the simulation.
This patch checks the frame preamble (0000007A) and the length field. If they are wrong, no decoding attempt is done.
The transmitted bytes are still delivered to the receivers untouched. The connection is terminated when the radio state is changed (which always happens when TX is done).

[Cooja/cc2420] Check the frame preamble and MPDU length before parsing an outgoing packet

---

core/sys/energest.h
cpu/cc2538/lpm.c
cpu/cc26xx-cc13xx/lpm.c
platform/cc2530dk/contiki-main.c
platform/exp5438/contiki-exp5438-main.c
platform/mbxxx/contiki-main.c
platform/seedeye/contiki-seedeye-main.c
platform/sensinode/contiki-sensinode-main.c
platform/sky/contiki-sky-main.c
platform/wismote/contiki-wismote-main.c
platform/z1/contiki-z1-main.c

Each time when switching between modes, energest could lose a tick or more. This happened when rtimer tick counter advanced between the call of RTIMER_NOW() in ENERGEST_OFF() and the call of RTIMER_NOW() in ENERGEST_ON(), so that end of the old mode was registered at time t, but start of the new mode at time t+1 or greater.
Thanks to Carlo Boano for reporting this.

Improve energest accuracy

---

apps/er-coap/er-coap-observe.c
core/net/ip/tcpip.c
core/net/mac/contikimac/contikimac.c

These 5 commits fix compiler warnings for TCPIP, coap-observe, msp430 mtarch, z1/tmp102 driver, and ContikiMAC.
Details are included in the commit messages.
I can submit these all as separate PRs if that's preferred.

Fix multiple warnings (TCPIP, coap-observe, msp430, z1/tmp102, ContikiMAC)

---

platform/wismote/contiki-conf.h
platform/wismote/contiki-wismote-main.c

This PR changes the WisMote's default MAC and RDC layers to CSMA and ContikiMAC, respectively. Furthermore, it fixes a compilation error concerning an invalid header inclusion when the IPv4 stack is enabled.

Minor fixes for the WisMote platform

---

regression-tests/01-compile-base/Makefile

Because we don't want to restrain ourselves with 700 bytes of new features!

Travis: compile er-rest-example for the Wismote platform rather than Sky

---

platform/cooja/cfs/cfs-cooja.c
tools/cooja/java/org/contikios/cooja/contikimote/interfaces/ContikiCFS.java

Previously, the Cooja mote assumed that its file was always initially empty (`file.endptr == 0`). Therefore, a file uploaded to a mote's CFS could never be read by the mote, as the mote would prevent reads from going past the EOF (indicated by `endptr`).
By tracking the file size and making it accessible to Cooja, the correct size of the uploaded file can be reported to the mote and allow it to read the uploaded file.

Cooja: Track CFS file size

---

dev/cc2520/cc2520.h

Fixed the issue with CC2520_READ_REG macro to read correct value of register.

Fixed the issue with CC2520_READ_REG macro to read correct value of register.

---

core/net/rpl/rpl-icmp6.c

With `DEBUG` enabled, two variables where unused. This PR removes the dead code.

Fix compiler warnings in rpl-icmp6.c

---

cpu/avr/radio/rf230bb/halbb.c

I think the if statements in the ISR in rf230bb look weird. If the first flag is matched then no other IRQ flags will be checked. According to the data sheet, the IRQ signal is deasserted after reading the IRQ status register, which, as I understand it, would cause the other unhandled IRQ flags to be lost forever. See AT86RF212 data sheet, chapter 8.1 "Frame Receive Procedure".
If my understanding of the data sheet is correct, then this behaviour can possibly lead to missed TRX_END interrupts, because RX_START is checked first. The reason that these two flags would be set at the same time could be that the handling of the interrupt from the radio has been delayed by other code either disabling interrupts, or another ISR with a higher priority was executing during the time between RX_START …

rf230bb: Handle all IRQ flags in one ISR call. (Q: Is the current ISR valid?)

---

tools/cooja/java/org/contikios/cooja/plugins/analyzers/PacketAnalyzer.java

THe packet analyser plugin is modifying the original packet data instead of working on it's own copy. This leads to broken cap files when more than one packet analyser is running.

Cooja: Clone packet data before modifying it in packet analyser

---

tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/CC2420RadioPacketConverter.java
tools/cooja/java/org/contikios/cooja/contikimote/interfaces/ContikiRadio.java
tools/cooja/java/org/contikios/cooja/util/CCITT_CRC.java

Packets sent from CoojaMote do not have a CRC. CoojaRadio simply send the packet to the RfListener as is. Also the adaptation layer between CC2420 emulator and RfListener drops and recreates the CRC for outgoing and incoming packets.
This PR ensure that all packets have (or keep) their CRC and so are exportable into valid PCAP.
Notes: I had to copy CCITT_CRC from MSPSIM as I did not see a way to cleanly reference it from Cooja, also, other radio driver might need adaptation, so feedback is most welcome.

Add CRC to packets send by CoojaMote

---

core/net/ip/ip64-addr.h
core/net/ip/uip-debug.c

IPv4-mapped Address [1] are now printed accoriding to the text representation
mixed IPv4 and IPv6 networks as specified in [2]
[1] https://tools.ietf.org/html/rfc6890#page-14
[2] https://tools.ietf.org/html/rfc3513#page-5

Better prints of ::FFFF: prefixed IPv4-mapped addresses

---

core/net/ip64/ip64-conf-example.h
core/net/ip64/ip64.c
core/net/ip64/ip64.h

I just replaced the two defines "IP64_CONF_DHCP" and "IP64_CONF_UIP_FALLBACK_INTERFACE"
from ip64.c and moved their definition into ip64.h. In addition, i added IP64_CONF_DHCP to the example configuration file for completeness.

ip64: Streamlined configuration parameters

---

core/net/mac/phase.c

This patches correct a potential problem in phase optimization code in the network stack in case of memory allocation failure.

Phase RDC memory allocation bugfix

---

core/net/ip/tcpip.c

The UIP_CONF_FORWARD is now handled in a better way that the general structure
of packet_input can be clearer seen.

Refactor tcpip.c packet input

---

core/lib/ringbuf.c
core/sys/cc.h

This fixes a potential issue with concurrency and the compiler being allowed to reorder instructions in the ringbuff (The whole topic is quite interesting and caused quite some discussions in our working group). Unfortunately this causes msp430-gcc 4.7.0 to produce worse code (for some reason the optimizer does not detect, that a register isn't needed anymore and does not reuse it, therefore needing an additional instruction). Nonetheless the side effects caused by this in the future may become quite ugly.

Ensure that the data in ringbuff is accessed in the right order

---

core/net/ip/tcpip.c

This pull request enables tcpip_ipv6_output() to send the first of the (possibly multiple) NS messages for a new IPv6 neighbor immediately after this neighbor is added to the neighbor list.
Under the current implementation, tcpip_ipv6_output() prepares a new NS packet, places it in the uip buffer, but returns, before sending it, relying on the periodic calls of the IPv6 engine to send the pending frame. However, if a packet arrival from the underlying MAC layer (e.g. sicslowpan) occurs before the following call of uip_ds6_periodic, the pending NS frame is lost (sicslowpan overwrites the uip_buf and uip_len may be set to 0 after processing the incoming frame). This pull request will force the NS transmission before tcpip_ipv6_output() releases the control.

Send the first NS attempt inside tcpip_ipv6_output()

---

cpu/native/net/linuxradio-drv.c

Re. https://github.com/contiki-os/contiki/commit/bd1b7d981438fb589e27ad6bf5c818175db2eac7#commitcomment-13490428

Fixed linuxradio-drv guard macro name

---

core/net/rpl/rpl-dag.c

Currently if Contiki RPL tries to join a network that make use of a non-supported objective function it will try to both create a DAG and a parent before realising that it is not going to be possible to join. This fix checks the OCP against the currency supported objective function before trying to allocate or create anything and fails earlier. Without this fix some examples that use a border router with a non-supported OF do crash (er-coap examples, etc).

RPL: check if objective function is supported before creating dag.

---

core/net/ipv6/uip-nd6.c

This PR ensures the second parameter of `uip_ds6_nbr_add` is word-aligned, which is required as the parameter is directly accessed as `uip_lladdr_t*` (not as a byte array).
Bug report from Deepak Sudhakar

ND6 alignment bugfix

---

core/net/ipv6/sicslowpan.c

Since #557, MAC_MAX_PAYLOAD does not include 802.15.4 header size anymore, that means the fragments count estimation is wrong again in sicslowpan.c (it requires too few queuebuf for a given packet).
This PR add the 802.15.4 header length again as committed by the framer.

Estimated fragments count should take into account 802.15.4 header size

---

apps/er-coap/er-coap-observe.c
apps/er-coap/er-coap-observe.h
apps/er-coap/er-coap-res-well-known-core.c
apps/er-coap/er-coap-transactions.c
apps/er-coap/er-coap.c
apps/er-coap/er-coap.h
apps/rest-engine/rest-engine.c

This PR is a set of CoAP bug fixes and small feature improvements. They were developed during our work with a Contiki implementation of LWM2M and IPSO Objects that was interop tested during the IPSO Interop in May 2015.
Fixes and improvements include:
* support for observe on sub-resources
* fixed URI to always be NULL terminated for observe
* more defensive programming for bad arguments and buffer overruns
This work has been performed as a part of an open source IoT edge project and is contributed by Yanzi Networks AB and SICS Swedish ICT. Intel Corporation is a sponsor of the open source IoT edge.

CoAP fixes and improvements

---

core/lib/ccm-star.c

This line assumes that the plaintext directly follows the AddAuthData. But the plaintext is already at memory location m, so there is no location change needed.

fixed memory bug

---

core/net/ip/uip-udp-packet.c

If the buffers overlap, `memcpy` must not be used as it might have arbitrary
results. This commit checks if the buffers overlap and safely copies everything
into the `uip_buf`

Fixes a possible unsafe memcpy in uip_udp_packet_send

---

core/net/ipv4/uip.c
core/net/ipv6/uip6.c

Ported change https://github.com/contiki-os/contiki/commit/2432a8ee7da3a7cdd6c05c54d28ada85105a0b37 (set expected reception sequence no to zero - to get initial connection to avoid having ack-number other than zero) from uIPv6 to uIPv4.

Initialize acknowledgment no. on establishment of outgoing TCP connection.

---

tools/cooja/java/org/contikios/cooja/SafeRandom.java

I implemented SafeRandom to avoid potential problems with simulations not being reproducible. Seems like I didn't think things all the way through. This should fix things.

Fix SafeRandom

---

core/net/rpl/rpl-conf.h
core/net/rpl/rpl-dag.c
core/net/rpl/rpl-private.h
core/net/rpl/rpl-timers.c
core/net/rpl/rpl.c
core/net/rpl/rpl.h
regression-tests/12-rpl/10-rpl-multi-dodag.csc

Currently there is no automated way to remove obsolete DODAG in a node, if a node has seen MAX_DODAG_PER_INSTANCE DODAGS all new DODAG are ignored, the only way to remove the old DODAG is to reset the node.
This PR add a lifetime for each DODAG, the lifetime is reset each time a DIO advertising that DODAG is heard. When a DODAG is not updated since RPL_CONF_DAG_LIFETIME the DODAG is removed from the list. Note that the currently joined DODAG is immunized from this.

Add DODAG lifetime, update of parent rank when switching dag and multi dodag non-regression test

---

core/contiki-default-conf.h
examples/cc2530dk/udp-ipv6/project-conf.h
examples/cc2538dk/udp-ipv6-echo-server/Makefile
examples/sensinode/udp-ipv6/project-conf.h
examples/udp-ipv6/Makefile
regression-tests/11-ipv6/code/receiver/project-conf.h
regression-tests/11-ipv6/code/sender/project-conf.h

This PR proposes to enable IPv6 NDP (Neighbor Discovery Protocol) only when IPv6 is set without RPL. This means that by default, in projects with `CONTIKI_WITH_IPV6` (implies IPv6+RPL) NA will be disabled. To re-enable it, set `UIP_CONF_ND6_SEND_NA` in `project-conf.h` or unset `CONTIKI_WITH_RPL` in the makefile.
This is only a proposal, no strong opinion on it. One could just as well disable NDP explicitly when needed. The PR includes a fix to a number of examples that need NA, but I might have missed a few.
Reasons to **not** run NDP along with RPL:
* NDP adds unneeded traffic (NDP is not designed for multi-hop, RPL DIO are sufficient to handle MAC-IP mapping)
* NDP adds complexity and might have bad interactions with RPL, e.g. delete a neighbor RPL still needs

Default NDP configuration

---

core/net/ip/tcpip.c
core/net/ip/uip.h
core/net/ip64/ip64-eth-interface.c
core/net/ip64/ip64-slip-interface.c
cpu/native/net/wpcap.c
examples/cc2530dk/border-router/slip-bridge.c
examples/ipv6/native-border-router/tun-bridge.c
examples/ipv6/rpl-border-router/slip-bridge.c
examples/sensinode/border-router/slip-bridge.c
platform/avr-ravenusb/contiki-raven-main.c

When there's a failure to send a packet in the fallback interface the
destination is unreachable and therefore the source should be notified.
This is a rebase of #222 as the original author did not respond within 27 days.

More flexibility for the fallback interface

---

platform/jn516x/dev/uart-driver.c

This fixes https://github.com/contiki-os/contiki/issues/1314

jn516x uart-driver.c: use DBG_vPrintf instead of printf.

---

core/net/ip/resolv.c
core/net/ip/uip.h
core/net/ipv6/multicast/roll-tm.c
core/net/ipv6/sicslowpan.c
core/net/ipv6/uip-ds6.c
core/net/ipv6/uip-nd6.c
core/net/ipv6/uip6.c
core/net/rpl/rpl-dag-root.c
core/net/rpl/rpl-icmp6.c
tools/sky/uip6-bridge/fakeuip.c
tools/stm32w/uip6_bridge/fakeuip.c

A simple search and replace of `uip_is_addr_link_local` to ensure the more
commonly used `uip_is_addr_linklocal` is used consistently.

Removes duplicate of uip_is_addr_linklocal

---

tools/tunslip6.c

This PR reverts https://github.com/contiki-os/contiki/commit/6608b62b01953b8a263ffda65802c1bc9052c06c which seems to break tunslip6 at  least for `examples/ipv6/rpl-border-router`. It also disables by default the IP address inquiry option, not supported by the BR.

Fix tunslip6

---

core/net/rime/stunicast.c

In core/net/rime/stunicast.c:
When calling stunicast_send_stubborn, a clock_time_t argument is passed to determine re-transmission time. The connection's ctimer is set with this time to call the send function.
When the timer expires for the first time and the send function is called, it sets the re-transmission timer to CLOCK_SECOND, regardless of the time that was passed to  stunicast_send_stubborn.
In this fix, I simply restart the connection's ctimer, i.e. setting it to the same given clock_time_t argument as passed to stunicast_send_stubborn.

Stunicast timer fix

---

core/net/mac/contikimac/contikimac.c
core/net/mac/csma.c

Fix for #1165
This fixes this problem by storing pending status in a local variable before calling mac_call_sent_callback.
Since this is (in my opinion) the obvious way to fix this problem I have gone ahead and simply implemented (and tested) this solution.

Fix Mishandling of PENDING/Queued Packets at ContikiMAC and CSMA

---

apps/er-coap/er-coap.c

According to the RFC, TKL greater than 8 MUST be processed as a message format error.

CoAP: Fix handling of Token Length greater than 8

---

dev/cc1200/cc1200-conf.h
dev/cc1200/cc1200.c

Made `USE_RX_WATCHDOG` configurable at i.e `project-conf.h`.  Also changed `RF_TESTMODE` to `CC1200_RF_TESTMODE` to allow configuring per application.

Made CC1200 test mode and rx watchdog selectable

---

platform/atarixl/Makefile.atarixl

The cc65 memory map for the ATARI XL has two holes so the linker needs hints which object files go where. Source changes lead to object file size changes requiring now and then to rearrange the object files.

Rearranged ATARI memory usage.

---

cpu/cc26xx-cc13xx/lpm.c

Sometimes you may want to go to shutdown without having a GPIO pin set as wakeup, eg if you prefer the device to reset to wakeup (through reset pin or power toggle). This PR makes this possible through use of `IOID_UNUSED` as wakeup-pin parameter.

[cc26xx-cc13xx] allow lpm_shutdown() without a wake-up pin set

---

cpu/cc26xx-cc13xx/lpm.c

The LED fading is nice looking, but strange feature to have in the lpm-module. It consumes unnecessary power, and you even may want to have an LED on even in shutdown.

Remove LED fade in lpm.c

---

apps/webbrowser/webclient.c
apps/webbrowser/www.c

When the client has already called webclient_close() it doesn't expect to have webclient_datahandler(NULL, 0) called just because the connection was closed by the server "at the same time". Rather it expects to always have webclient_closed() called.
Calling webclient_datahandler(NULL, 0) instead of webclient_closed() means that the web browser shows "Done" in the status line instead of "Stopped". So the user is mislead to think that he has already seen all of the page.
Note: webclient_close() is called by the client during newdata() so the already existing check for WEBCLIENT_STATE_CLOSE further above doesn't help.

Client requested close takes precedence over server initiated close.

---

apps/webbrowser/www.c

After page loading has finished the number of free bytes left for page attributes is logged. It turns out that "usual" pages tend to get along with ~800 bytes while i.e. the Google search pages use all of the 2000 bytes of page attribute memory allocated by default (because of the long URLs with many parameters). So it seems that reducing this default isn't exactly the best way to reduce memory consumption...

Log web browser page attributes free memory left.

---

tools/sky/serialdump.c

Using clang (on osx) yields to some warnings
(conversion between signed/unsigned, unused variable)
which gcc would only produce when used with -Wall.
This commit fixes those.

Fix serialdump.c warnings (clang)

---

tools/cooja/java/org/contikios/cooja/util/CCITT_CRC.java

This is a whitespace change only. Similar to #756.
A problem with this file is also mentioned in a comment in #1162

CCITT_CRC.java Change line endings from CRLF to LF

---

platform/srf06-cc26xx/README.md

Code block in a list was not properly indented, so the gcc version string looked like a link leading to nowhere (because of markdown)

Small correction to cc26xx readme

---

apps/webbrowser/www.c
examples/jn516x/rpl/border-router/slip-bridge.c
examples/wget/wget.c

This fixes three warnings that slipped in after https://github.com/contiki-os/contiki/pull/1293 was last built in Travis.

Last compiler warnings

---

core/net/ipv6/sicslowpan.c

This PR fixes unused variable warnings in case 6lowpan fragmentation is disabled

sicslowpan.c: warning-free compilation even with fragmentation disabled

---

regression-tests/15-compile-arm-apcs-ports/Makefile
regression-tests/Makefile.compile-test

Some platforms use make variables to specify different build options such as target boards. Adding the option to specify make variables in regression compile tests makes it possible to test compiling for different boards with same target.
```
EXAMPLES = \
hello-world/stm32nucleo-spirit1:BOARD=ids01a4:SENSORBOARD=iks01a1 \
hello-world/stm32nucleo-spirit1:BOARD=ids01a5:SENSORBOARD=iks01a1 \
hello-world/srf06-cc26xx:BOARD=srf06/cc26xx \
hello-world/srf06-cc26xx:BOARD=srf06/cc13xx \
```

Add option to specify make variables for regression compile tests

---

core/net/rpl/rpl-conf.h
core/net/rpl/rpl-private.h

Created a configuration-define for DIS start delay and moved it + DIS interval out of rpl-private.h and into rpl-conf.h. It seems appropriate since DIO interval is already specified here, and the DIS parameters are similarly interesting to tweak.

Add configuration of DIS start delay and interval in RPL conf.

---

core/net/rpl/rpl-icmp6.c
core/net/rpl/rpl-private.h
core/net/rpl/rpl-timers.c

`DAO_EXPIRATION_TIMEOUT` is renamed to `RPL_NOPATH_REMOVAL_DELAY` to reflect what it actually is.
`RPL_DAO_LATENCY` is renamed ti `RPL_DAO_DELAY` for consistency with the terminology in RFC6550 and other RPL and IPv6 constants in Contiki.
Both are now documented and configurable.

RPL: clearer naming and documentation of DAO delay constants

---

cpu/cc26xx-cc13xx/rf-core/prop-mode.c

#1233 applied some improvements to the CC13xx/CC26xx IEEE mode driver. This pull replicates those improvements for the prop mode driver. In summary:
* We only switch channel if a new channel is being requested
* We turn the CC13xx RF back off after prop TX if it was off to start with
* Turn off `ENERGEST_TYPE_LISTEN` in CC13xx prop mode `off()`

Improve the CC13xx sub-ghz driver

---

.gitignore

Ignore:
- .cooja (elf files generated by cooja builds)
- .swp (vim editor temporary files)
- doc/latex/ (generate with ```make -C doc pdf```)
- various build & temporary files generated in regression-tests

Ignore various build and temporary files

---

platform/cc2538dk/Makefile.cc2538dk
platform/remote/Makefile.remote
platform/srf06-cc26xx/README.md
platform/srf06-cc26xx/srf06/Makefile.srf06

This PR updates the cc2538-bsl submodule to the latest version (2.0).
**Biggest change**: the script now supports upload of firmware to the **cc13xx and cc26xx chips**. This comes with a big Thank You to @g-oikonomou for adding support for these chips and improving the script in general!
Makefiles of the relevant platforms have been updated to support `.upload` for a 1 command compilation and uploading.
Other improvements:
- Fixed an annoying bug involving garbage characters left over in a serial buffer.
- Added support for uploading `hex` files.
- Improved abstraction in the script to support multiple chips or targets
- Added chip autodetection
- Improved chip info readout
- Improved PY3 support
- Improved read command
- Added basic testing
- Added a `force` option and a `disable …

cc2538-bsl update to 2.0, cc13xx and cc26xx support

---

core/net/ipv6/uip-ds6.c
core/net/ipv6/uip-icmp6.c
core/net/ipv6/uip-nd6.c

This PR simply fixes some debug log messages in which IPv6 addresses are printed together with some other text, instead of separated by white spaces.

Print IPv6 addresses properly in ICMPv6 and NDP debug messages

---

dev/cc1200/cc1200-conf.h
dev/cc1200/cc1200.c

With regard to contikimac, i modified the usage of the RX watchdog and calibration behavior. There was a bug in the usage of the etimer used for the RX watchdog and also in the rx_rx() routine which was meant to restart rx in every case of error. In fact, flushing the RX fifo while keeping the cc1200 in rx is not a good idea...

cc1200: Make it more suitable for contikimac + bugfix in rx restart routine

---

core/net/ipv6/uip-ds6-route.c
core/net/rpl/rpl-dag.c
core/net/rpl/rpl-icmp6.c

This PR simplifies and re-enabled the annotation of removed routes in `uip-ds6-route.c`, extends the printouts of DAO sending to specify whether this is No-Path or not, and uses consistent case for No-Path throughout.

Improved RPL debugging

---

core/net/mac/contikimac/contikimac.c

Replaced a cast of the function pointer to powercycle with a wrapper calling powercycle which has the correct signature.
The previous implementation was an instance of undefined behaviour according to the C standard.

Replaced function pointer cast in contikimac

---

core/net/rpl/rpl-ext-header.c
core/net/rpl/rpl-private.h
core/net/rpl/rpl-timers.c
core/net/rpl/rpl.h

This PR improves RPL loop repair by:
* Sending unicast DIO to the packet source when detecting a loop from ext header;
* Fixing rank along the path (update neighbor rank from ext header when rank error is signaled).
The unicast DIO transmission is delayed to after relaying the packet being forwarded. This is implemented on top of the existing probing mechanism. Testbed in different testbeds, TelosB and NXP JN5168.

Enhanced RPL loop repair

---

cpu/cc2538/Makefile.cc2538
cpu/cc2538/dev/pwm.c
cpu/cc2538/dev/pwm.h
examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-pwm.c
platform/cc2538dk/README.md
platform/zoul/README.md

This PR adds support for PWM on CC2538-based platforms.
* Frequencies from 1 Hz to 160 KHz.
* Duty cycle from 1-99%.
* Allows to toggle duty cycle.
* The pin state when the PWM signal is stopped can be defined by the user (low/high)
* `GPT0 timer A` is reserved for `clock_delay_usec` so returns an error if selected

Added PWM driver for the Zolertia Zoul module and CC2538 platforms

---

core/net/mac/contikimac/contikimac.c
core/sys/rtimer.h

CONTIKIMAC_RTIMER_GUARD_TIME is the minimum amount of rtimer ticks between the current time and the future time when the ContikiMAC rtimer is scheduled.
It is necessary to avoid accidentally scheduling a rtimer in the past  on platforms with fast rtimer ticks (e.g. 16 MHz).

ContikiMAC: add CONTIKIMAC_RTIMER_GUARD_TIME #define

---

core/net/rime/chameleon-bitopt.c

use BITOPT_HDR_SIZE rather than sizeof(struct bitopt_hdr)

Rime Chameleon fix for 32-bit platforms

---

core/sys/cc-gcc.h
core/sys/cc.h
cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
cpu/cc26xx-cc13xx/rf-core/prop-mode.c
cpu/cc26xx-cc13xx/rf-core/rf-ble.c
cpu/cc26xx-cc13xx/rf-core/rf-core.c
doc/Doxyfile

I think that it does not make sense to define functionality specific to compilers in platform headers or as needed in C files. I'd like to propose that we have specific header files for compiler specific functionality and have created such a header for gcc.
In addition to the above, this will also have the tangible effect of defining CC_CONF_INLINE on platforms that build with gcc and which do not already define it (such as CC2538 and CC2650) without having to add more to the platform specific header files.

put gcc specific stuff into seperate .h

---

core/net/rime/chameleon-bitopt.c

https://github.com/contiki-os/contiki/pull/1133 introduced a warning, undetected when it was last tested for non-regression as we didn't compile with -Werror back then. This fixes the warning and should get Travis green again!

Fix warning introduced by https://github.com/contiki-os/contiki/pull/1133

---

cpu/cc2538/startup-gcc.c

According to the Procedure Call Standard for the ARM Architecture
(AAPCS) - ABI r2.09 [1], §5.2.1.2, the stack pointer must be
double-word-aligned at a public interface. The stack implementation
being full-descending, this requires that the top of stack be
double-word-aligned too.
[1] http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042e/IHI0042E_aapcs.pdf
Closes #1398.

cc2538: Fix stack alignment

---

cpu/cc2538/dev/pwm.c
cpu/cc2538/dev/pwm.h
cpu/cc2538/lpm.c
examples/zolertia/zoul/test-pwm.c

This is a follow-up of #1399.
The peripheral core clock of the general-purpose timers used by the PWM driver is the system clock, not the I/O clock (see the CC2538 user's guide).
The peripheral core clocks of the PWM timers are gated in PM1+, so these power modes must be disabled if a PWM timer is running. Use lpm_register_peripheral() to handle this automatically and dynamically (suggested by @g-oikonomou in #1399).

cc2538: pwm: Fix clock and automatically disable PM1+ if running

---

examples/zolertia/zoul/rtcc/Makefile
examples/zolertia/zoul/rtcc/project-conf.h
examples/zolertia/zoul/rtcc/test-rtcc.c
platform/zoul/README.md
platform/zoul/remote/Makefile.remote
platform/zoul/remote/README.md
platform/zoul/remote/rtcc-config.h
platform/zoul/remote/rtcc.c
platform/zoul/remote/rtcc.h

This PR adds support for the RE-Mote's on-board Real Time Clock Calendar.
More information about the RTCC (Abracon AB080x) can be found in our [Resource](https://github.com/Zolertia/Resources/tree/master/RE-Mote/Hardware/Revision%20A/Datasheets/Components) repository
The port is missing a function to select the oscillator source, but it is hardcoded to use the XT (external crystall).  A pending improvement would be also to wake up the device from PM3.

Added support for the RE-Mote on-board Real Time Clock Calendar (RTCC)

---

platform/jn516x/README.md

New maintainer for the JN516x platform available

Changed NXP maintainers for JN516x platform

---

cpu/cc26xx-cc13xx/rf-core/rf-core.c

As discussed in #1279, the current CC13xx/CC26xx rf-core code makes some unnecessary power domain-related reads. This pull removes them.
Closes #1279

Remove redundant function calls in CC13xx/CC26xx RFC code

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
cpu/cc26xx-cc13xx/rf-core/rf-core.c
cpu/cc26xx-cc13xx/rf-core/rf-core.h

The radio driver has 2 problems:
* Firstly, detection of whether a command is a Radio Op is broken: Some immediate commands will get categorised as Radio Ops, when in reality they are not. One such command is `CMD_SET_TX_POWER`.
* Secondly: When `set_tx_power()` is called in IEEE mode, it will try to immediately apply the new setting by sending `CMD_SET_TX_POWER`. If this command fails, then the new TX power setting will not be applied at all. One reason of such failure is if the RFC is powered off.
Thus, this pull:
* Fixes the command type classification logic.
* Changes the logic in `set_tx_power()` for IEEE mode. If the new user setting is valid, it always gets saved. If the RFC happens to be powered up, the new setting gets applied immediately with `CMD_SET_TX_POWER`. If the RFC is …

Correctly set new CC26xx TX power when the RFC is powered off

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c

As discussed very briefly in #1229, access to the data structure representing CMD_IEEE_TX should be volatile.

Use volatile access for CMD_IEEE_TX

---

cpu/cc26xx-cc13xx/dev/soc-rtc.c
cpu/cc26xx-cc13xx/lpm.c

This pull addresses a number of issues and applies a number of improvements to the CC13xx/CC26xx low-power logic.
_Firstly_, we make sure the AON RTC CH1 event handler always sets a valid time for the next compare event.
The current logic is to schedule CH1 events on each 512 AON RTC counter boundary while running (not when deep sleeping). However, under certain conditions the AON RTC interrupt handler will end up scheduling the next CH1 compare event too soon in the future, or on some extreme cases even in the past.
When this happens, the LPM logic gets confused thinking that there is not sufficient time to deep sleep and always chooses to put the SoC to sleep instead. The condition manifests itself by observing devices fully operational but otherwise stuck in a high power consumption …

Improve the stability of CC13xx/CC26xx low-power operation

---

examples/zolertia/zoul/project-conf.h
examples/zolertia/zoul/test-tsl2563.c
platform/zoul/dev/tsl2563.c
platform/zoul/dev/tsl2563.h
platform/zoul/dev/zoul-sensors.h
platform/zoul/firefly/board.h
platform/zoul/remote/board.h

This PR fixes and enhances the current `tsl2563` driver implementation with the following:
* Interruption when a value is over/below a given threshold
* Gain and timing selectable (16X, 13.7ms up to 402ms)
* Lux calculation checked for different configurations
* Partnumber and version check
This has been tested on the `firefly` and the `RE-Mote`, for the later (revision A) as the `PD1` pin is shared with the `power-mgmt` communication pin (with a pull-down) the interruption feature is broken, a quick workaround is to use a different pin (change in `board.h`).

Enhanced TSL2563 driver for the Zoul module (RE-Mote/Firefly)

---

platform/zoul/dev/adc-sensors.h

This PR fixed the ADC initialization as the filter condition was wrong.

Fixed filter value preventing from initializing the ADC

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/project-conf.h
examples/zolertia/zoul/test-bmp085.c
examples/zolertia/zoul/test-motion.c
examples/zolertia/zoul/test-sht25.c
platform/zoul/dev/bmp085.c
platform/zoul/dev/bmp085.h
platform/zoul/dev/motion-sensor.c
platform/zoul/dev/motion-sensor.h
platform/zoul/dev/sht25.c
platform/zoul/dev/sht25.h

This PR enables support for PIR-based digital motion sensors, based on driving a signal low/high when motion is detected.  This driver has been tested with the [Seeedstudio's PIR motion sensor](http://www.seeedstudio.com/depot/PIR-Motion-Sensor-Large-Lens-version-p-1976.html) and [IRTEC 550LP sensor](http://www.irtec.com/en/pirtybvi.asp?PagNO=1&PcID=60&fxfID=49&Mde=V)
This PR depends on #1454

Add support for digital motion/presence sensors

---

platform/srf06-cc26xx/sensortag/bmp-280-sensor.c
platform/srf06-cc26xx/sensortag/ext-flash.c
platform/srf06-cc26xx/sensortag/opt-3001-sensor.c

This is to prevent a compile error caused by function prototype conflict between a function called `select()` (present in a number of sensortag peripheral drivers) and the one in `sys/select.h`. The error manifests itself with gcc-arm-embedded version 5.2.1 20151202 (2015-q4).
To fix the error we simply rename our function.
This is simply a compile fix. I have not tested whether the resulting binaries work correctly.
Fixes #1434

Rename select() in various sensortag sensor drivers

---

regression-tests/18-compile-arm-ports/Makefile

This adds three travis compile jobs in order to test:
* Drivers for the CC2650 Sensortag
* Drivers for CC1310 RF prop mode
* The cc2650 web demo and the very sleepy demo for the CC2650 Sensortag
This is what it looks like:
```
[...]
Building example 07: cc26xx/very-sleepy-demo/ BOARD=sensortag/cc2650 for target srf06-cc26xx
cc26xx/very-sleepy-demo/ srf06-cc26xx: OK
Building example 08: cc26xx/cc26xx-web-demo/ BOARD=sensortag/cc2650 for target srf06-cc26xx
cc26xx/cc26xx-web-demo/ srf06-cc26xx: OK
Building example 09: cc26xx/cc26xx-web-demo/ BOARD=srf06/cc13xx for target srf06-cc26xx
cc26xx/cc26xx-web-demo/ srf06-cc26xx: OK
[...]
```

Compile-test the CC2650 Sensortag and Srf06+CC1310EM code

---

platform/zoul/dev/adc-sensors.c
platform/zoul/dev/adc-zoul.c

Fixes mask OR'ed values being treated as invalid due to restrictive check, leftover from a previous commit

Removed harsh restriction on mask values and disabled debug flags

---

examples/er-rest-example/server-client-native.csc
examples/er-rest-example/server-client.csc
examples/er-rest-example/server-only.csc
examples/ipv6/sky-websense/example-sky-websense.csc
examples/zolertia/z1/ipv6/z1-websense/example-sky-websense.csc
regression-tests/13-ipv6-apps/x02-sky-coap.csc

Loading examples using the SerialSocketServer plugin in Cooja failed. This was because of using SerialSocketServer instead of the full name org.contikios.cooja.serialsocket.SerialSocketServer. This patch fixed the problem on my side.
To reproduce the failure:
1.) Launch cooja (ant run)
2.) Load e.g. examples/ipv6/sky-websense/example-sky-websense.csc
3.) On the command prompt you should see an error on loading SerialSocketServer
4.) Setup tunslip (e.g. make connect-router-cooja) will fail without this patch

Fixed loading SerialSocketServer plugin in Cooja using FQDN

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-bmp085-bmp180.c
platform/zoul/dev/bmpx8x.c
platform/zoul/dev/bmpx8x.h

This PR unifies the driver to support both BMP085 and the BMP180 atmospheric pressure sensors, as both reuse the same logic, but the BMP180 has been advertised to provide better results.

Unified BMP180 and BMP085 drivers

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-grove-gyro.c
platform/zoul/dev/grove-gyro.c
platform/zoul/dev/grove-gyro.h

This PR adds support for the [Grove's 3-axis gyroscope](http://www.seeedstudio.com/wiki/Grove_-_3-Axis_Digital_Gyro), including a zero-point calibration function, return values in degrees/seconds and data-ready interrupts to maximize the data acquisition.

Add support for the ITG-3200 3-axis gyroscope

---

platform/zoul/dev/weather-meter.c

Updated as previously named `adc-sensors` has been renamed to `adc-zoul`

Updated to new adc-zoul renaming

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-lcd.c
platform/zoul/dev/rgb-bl-lcd.c
platform/zoul/dev/rgb-bl-lcd.h

This PR adds support for the [Grove's LCD display with RGB backlight](http://www.seeedstudio.com/wiki/Grove_-_LCD_RGB_Backlight), based on the [JHD1214](http://www.seeedstudio.com/wiki/images/0/03/JHD1214Y_YG_1.0.pdf) LCD and the [PCA9633 I2C LED driver](http://www.seeedstudio.com/wiki/images/1/1c/PCA9633.pdf)

Ported Grove LCD with RGB backlight for the Zoul platforms

---

.travis.yml
platform/cc2538dk/README.md
platform/srf06-cc26xx/README.md
platform/zoul/README.md

Do we want to switch travis to arm-gcc v5.2.1?
We'll first need to make sure that resulting binaries work well for the affected platforms.
If #1452 gets merged, then merging this one here will cause travis errors unless #1451 also gets merged.

Change travis arm tests to use gcc-arm-embedded v5

---

cpu/cc26xx-cc13xx/rf-core/rf-core.c

When sending a command to the CC13xx/CC25xx RF core, we wait for command completion by checking the LSB of CMDSTA (correctly so). However, in doing so we also zero out the 3 CMDSTA return bytes. For some commands, those bytes contain useful information (e.g. an RSSI value) and are required by the caller.
This problem manifests itself e.g. in PROP mode `channel_clear()`, whereby the caller will always see an RSSI value of 0.
This pull therefore fixes the logic in `rf_core_send_cmd()` to check for command completion by blocking on the CMDSTA result byte without zeroing out the 3 return bytes.
Fixes #1465

Allow the caller to access the entire content of CMDSTA

---

platform/zoul/dev/weather-meter.c

This PR fixes the wind direction average calculations, as using unsigned variables was provoking erratic values and missing some checks.  This has been tested in a personal project over the past days, and for different averaging values (validated [mitsuta](http://abelian.org/vlf/bearings.html) vs [mean of circular quantities](https://en.wikipedia.org/wiki/Mean_of_circular_quantities) with small variations)

Fixed casts and calculations for the wind direction circular averaging

---

platform/jn516x/contiki-jn516x-main.c
platform/jn516x/dev/uart-driver.c
platform/jn516x/dev/uart-driver.h

Fixes a bug that caused loss of some incoming uart data

jn516x: flush only uart Tx FIFO in main loop, leaving Rx FIFO intact

---

apps/shell/shell-vars.c

" sprintf(numbuf, "0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x",...)" . the formatted data wrote to "numbuf" is 39 bytes, but numbuf is 32 bytes.

a memory overflow in shell-vars.c

---

platform/galileo/Makefile.galileo

This patch revises the compiler flags when LLVM Clang is in use to
cause Clang to automatically use its built-in header files rather than
those for GCC.  This avoids compiler errors that can otherwise
be generated by including certain built-in headers.

galileo: Revise include flags for LLVM Clang

---

regression-tests/simexec.sh

Simply print out the standard output from java instead of the Cooja log.
stdout includes the full Cooja log, but also error messages in cases the JVM crashes (e.g. native node triggers segfault).

Travis: improved output for failed Cooja simulation

---

core/net/ip64/ip64-eth-interface.c
core/net/ip64/ip64.c
dev/enc28j60/enc28j60-ip64-driver.c

This PR fixes warning upon compiling for `ip64` and fixes broken `enc28j60-ip64-driver.c` related to `linkaddr_node_addr` being undeclared

Fix ip64 warnings and error

---

core/net/rime/route-discovery.c
core/net/rime/route-discovery.h

For route discovery connections, 2 logical channels are used:
One channel for netflood messages, and one for unicast.
When opening a route discovery connection using
route_discovery_open(), only one channel number is specified
and used for netflood, and the unicast channel number is
hard-coded to be the next channel (+1).
This commit adds an alternative function for opening route
discovery connections, allowing the user to specify both channels
independently, to gain improved control, flexibility and readability.
The existing function (route_discovery_open()) was modified to
make use of the new function, to prevent code duplication,
without breaking the expected behavior.

Add route_discovery_explicit_open()

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-iaq.c
platform/zoul/dev/iaq.c
platform/zoul/dev/iaq.h

Made VOC driver based on the iAq-Core with a test application. The driver has to wait 5 minutes after the sensor is enabled to be able to obtain data readings, as indicated by the sensor manufacturer.

Added VOC (iAQ-Core) drivers and test application

---

platform/zoul/dev/adc-sensors.c
platform/zoul/dev/adc-sensors.h

This pull request removes code lines related to PM10 from `adc-sensors` driver. The PM10 driver is implemented with her own files and only access to `adc-zoul` driver.

Removed PM10 code lines from adc-sensors driver

---

.travis.yml

Make Travis CI use the GNU ARM Embedded toolchain version specified by
the READMEs, instead of automatically using the latest version provided
by the PPA. In this way, the READMEs will still be correct after a PPA
upgrade, and the version used by Contiki is under control.
This is a follow-up to #1453 (@g-oikonomou @alignan).

travis: Force AAPCS toolchain version

---

apps/shell/shell-exec.c

This PR fixes a compilation error when `PROCESS_CONF_NO_PROCESS_NAMES` is enabled

Fixes error when processes name are not used

---

core/net/ipv6/uip-icmp6.c

The sent ICMP6 packets (for example from RPL) are currently
not counted towards the sum of sent ip and icmp packets.
Is there any reason behind this or is it just a bug?
Looking at the code I found no side effects of adding these two lines.
Debug output:
```
uip_stat.ip .recv 10 .sent 23 .forwared 0 .drop 0
uip_stat.icmp .recv 10 .sent 11 .drop 0
uip_stat.udp .recv 0 .sent 12 .drop 0
```
(Sum of ip.sent matches icmp.sent and udp.sent)

uIP Stats: Count sent ICMP6 packets

---

tools/tunslip6.c

When running multiple tunslip6 instances, it collides with tun0 being already
used (cannot open file). However, system default is already to use "tun0" and "tap0".
By putting the default empty string as name, system automatically increment and
selects a free interface, "tun0", "tun1".

Fix default tun/tap issue with multiple tunslip6

---

apps/er-coap/er-coap-separate.h
apps/er-coap/er-coap-transactions.h
core/lib/gcr.c
core/lib/settings.h
core/lib/trickle-timer.c
core/net/ipv6/sicslowpan.c
core/net/rpl/rpl-dag.c
core/net/rpl/rpl.h
examples/er-rest-example/resources/res-event.c

I was getting warnings when building with `-Wstrict-prototypes`:
```
In file included from ./resources/res-b1-sep-b2.c:42:0:
../../apps/er-coap/er-coap-separate.h:64:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
void coap_separate_reject();
^
In file included from ./resources/res-b1-sep-b2.c:43:0:
../../apps/er-coap/er-coap-transactions.h:70:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
void coap_register_as_transaction_handler();
^
../../apps/er-coap/er-coap-transactions.h:78:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
void coap_check_transactions();
^
./resources/res-event.c:56:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
static void res_event_handler();
^ …
```

fix warning: function declaration isn't a prototype

---

platform/galileo/bsp/libc/build_newlib.sh

This avoids treating as patches other files that may happen to be
present in the newlib patch directory in a working tree.

galileo: build_newlib.sh: Only apply patch files with the extension ".patch"

---

platform/galileo/bsp/libc/build_newlib.sh

This patch adds a check for the result of the newlib configure command
and immediately exits the build_newlib.sh script if configure fails.

galileo: build_newlib.sh: Exit on configuration error

---

core/net/mac/tsch/tsch.c
examples/ipv6/rpl-tsch/project-conf.h
regression-tests/11-ipv6/21-z1-rpl-tsch-security.csc

Due to what seems to be a msp430x linked bug, we get half-random 2-Byte ROM overflow every now and then when z1 firmwares get large (even though there *is* enough space left).
This PR saves some space on the TSCH Security example, and should help https://github.com/contiki-os/contiki/pull/1539 and https://github.com/contiki-os/contiki/pull/1540 get through.

TSCH-Security regression test: save space

---

core/net/rpl/rpl-dag.c
core/net/rpl/rpl-timers.c

Two fixes in debug messages:
1. Removal of a white space between "RPL" and ":" in a couple of message headers in rpl-dag.c
2. Spelling correction in rpl-timers.c

RPL: fix typos in debug messages

---

core/net/ipv6/uip-icmp6.c
core/net/ipv6/uip6.c

This is a collection of fixes required to get traceroute to work.
There were several connected problems:
* icmp error messages should return the original incoming packet, but they returned an altered version due to extension header handling and buffer length bugs
* the last hop never returned a "port unreachable" message

uip6, icmp6 and ext header handling fixes: traceroute now working!

---

examples/ipso-objects/README.md
examples/ipso-objects/example-ipso-objects.c
examples/ipso-objects/example-server.c
examples/ipv6/rpl-tsch/node.c
examples/jn516x/tsch/tx-power-verification/node/node.c
examples/jn516x/tsch/uart1-test-node/uart1-test-node.c

A number of new "aaaa" slipped in between the original PR and its merge. This replaces them with the new local prefix "fd00"

Fix a number of leftover mentions of aaaa as a prefix (now fd00)

---

core/net/ip/resolv.c

I did a quick check with a MSP430 and with a ARM based platform, here's the size diff. I'm a bit surprised to see only marginal savings in BSS, nonetheless flash savings seem to indicate it's worth to drop the `static` declarations.
| text | data | bss | dec | platform |
|------|-------|------|-------|-----------|
| -170  |    0  |   -6 | -176  |  MSP430 |
| -280  |     0 |   -12 |  -292 |   ARM |
Closes https://github.com/contiki-os/contiki/issues/1333

trims resolv.c by removing unrequired static declarations

---

platform/sky/platform-conf.h

On many other tool chains, like TI's new MSG430-GCC, the typedef will be conflict.

off_t changed to signed to stay the same as POSIX

---

core/net/ipv6/uip-ds6-nbr.c
core/net/ipv6/uip-ds6-nbr.h
core/net/ipv6/uip-ds6.c
core/net/rpl/rpl-icmp6.c
core/net/rpl/rpl.c

Addresses one of the issues in https://github.com/contiki-os/contiki/issues/1380
Nodes running RPL with NDP disabled will now remain in REACHABLE state.
Removing some state in `uip-ds6-nbr` also results in about 20 bytes saved per neighbor.

NDP disabled: also disable uip_ds6_neighbor_periodic

---

examples/zolertia/z1/test-adxl345.c
examples/zolertia/z1/test-tmp102.c
platform/z1/dev/adxl345.c
platform/z1/dev/adxl345.h
platform/z1/dev/tmp102.c
platform/z1/dev/tmp102.h

This PR adapts the current implementation of the `TMP102` and `ADXL345` on-board sensors to the Contiki's sensor API, while maintaining previous functions to avoid breaking up applications out of the tree.
Unused blocks and misused data structures are removed; functions not being declared as static, and some minor code style are also fixed (a full uncrustify touch-up on the Z1 current code is pending in a separate PR).

Adapt Z1 on-board sensors to Contiki's API

---

cpu/x86/Makefile.x86_quarkX1000
cpu/x86/drivers/legacy_pc/shared-isr.c
cpu/x86/drivers/legacy_pc/shared-isr.h
cpu/x86/drivers/quarkX1000/gpio.c
cpu/x86/drivers/quarkX1000/i2c.c
cpu/x86/drivers/quarkX1000/i2c.h
cpu/x86/init/common/interrupt.h
cpu/x86/quarkX1000.ld
examples/galileo/Makefile
examples/galileo/README.md
examples/galileo/gpio-input.c
examples/galileo/gpio-interrupt.c
examples/galileo/gpio-output.c
examples/galileo/i2c-LSM9DS0.c
examples/galileo/i2c-callbacks.c
platform/galileo/README.md
platform/galileo/contiki-main.c
platform/galileo/drivers/galileo-pinmux.c

This patchset enables interrupts to be delivered to both the I2C and GPIO subsystems.  Previously, interrupts could only be delivered to one or the other due to an incorrect assumption in the code that the two controllers use separate interrupt pins.
This patchset also centralizes the initialization of the I2C and GPIO subsystems so that they are always initialized, even if they are not used by the selected application(s).  It seems likely that most usages of this platform will involve GPIO and/or I2C.  The Ethernet device is likewise always initialized even if it is not required.  Furthermore, #1433 requires that GPIO and I2C be initialized early during boot so that they can define their associated system calls at the appropriate time.
Finally, this patchset provides various minor …

galileo: Enable I2C and GPIO interrupt sharing and centralize their initialization

---

doc/uip6-doc.txt

that one warning slipped in after merging https://github.com/contiki-os/contiki/pull/1387, which was last run in Travis in November. Not sure if this is the cleanest of fixes, simply suppresses the ref to `uip_ds6_neighbor_periodic` as the function is now compiled out by default.

Fix doxygen warning

---

tools/cooja/apps/serial_socket/java/org/contikios/cooja/serialsocket/SerialSocketServer.java

I add a problem running Cooja serial socket server without a graphical interface. It created NullPointerException at the initial stage.
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.contikios.cooja.serialsocket.SerialSocketServer$6.actionPerformed(SerialSocketServer.java:652)
at javax.swing.Timer.fireActionPerformed(Timer.java:312)
at javax.swing.Timer$DoPostEvent.run(Timer.java:244)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
at java.awt.EventQueue.access$300(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:706)
at java.awt.EventQueue$3.run(EventQueue.java:704)
at java.security.AccessController.doPrivileged(Native Method)
at …
```

fix SerialSocketServer when run without GUI

---

cpu/x86/Makefile.x86_quarkX1000
cpu/x86/dma.h
cpu/x86/drivers/quarkX1000/eth.c
cpu/x86/drivers/quarkX1000/imr-conf.c
cpu/x86/drivers/quarkX1000/imr-conf.h
cpu/x86/drivers/quarkX1000/imr.c
cpu/x86/drivers/quarkX1000/imr.h
cpu/x86/drivers/quarkX1000/msg-bus.c
cpu/x86/drivers/quarkX1000/msg-bus.h
cpu/x86/quarkX1000_dma.ld
examples/galileo/Makefile
examples/galileo/README.md
examples/galileo/print-imr.c
platform/galileo/README.md

Depends on #1444.
This patchset adds drivers for the Intel Quark X1000 SoC message bus and Isolated Memory Regions (IMRs).  It also adds support for optionally configuring and locking the IMRs during boot to block DMA to memory regions that do not contain any data that needs to be DMA-accessible.

galileo: Isolated Memory Region support

---

core/net/mac/tsch/tsch-packet.h
core/net/mac/tsch/tsch-queue.c
core/net/mac/tsch/tsch-queue.h
core/net/mac/tsch/tsch-slot-operation.c
core/net/mac/tsch/tsch.c

Do not merge yet, this is not tested on all platforms.
Explicitly turn off the radio after ACK Tx, may be needed on some platforms (most platform would turn it off anyway as it was off before Tx). Also fixes `TSCH_PACKET_MAX_LEN` for platforms with smaller `PACKETBUF_SIZE`.
Added another fix: we now flush all queues and reset backoff exponents whenever re-associating.

Minor TSCH fixes

---

platform/jn516x/dev/clock.c

This small fix has a huge impact on the etimer events. The current check is wrong for sure since `clock_time_t` is unsigned. For further details check my comment on #1265.

JN516x clock module sign error fix

---

platform/zoul/contiki-main.c
platform/zoul/dev/adc-sensors.c
platform/zoul/dev/adc-zoul.c
platform/zoul/dev/adc-zoul.h
platform/zoul/dev/zoul-sensors.c
platform/zoul/firefly/board.h
platform/zoul/remote/board.h

Added enabling up to 6 ADC channels for RE-Mote and Firefly platforms.
Solved problem with `enabled_channels` variable in adc-zoul driver.

Added enabling up to 6 ADC channels and fixed adc-zoul driver problem. 

---

.travis.yml

Up till now we have been installing arm-gcc using apt from the team-gcc-arm-embedded ppa.
As discussed in #1453 and implemented in #1504, we have decided to lock travis to use the specific version of the toolchain that is documented in the READMEs of relevant platforms. However, the PPA no longer hosts this version, apt fails to install arm-gcc and as a result the job fails too.
This pull changes the travis job to wget an installation tarball for the desired version, instead of trying to install via apt.
Fixes #1586

Fix failure of ARM-AAPCS travis job

---

core/net/ip/tcpip.c

A number of local variables in tcpip.c were declared with static storage for no good reason (they do not ever preserve state between function calls).
This patch removes static declaration from these variables.

changed tcpip static temporaries to stack vars

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
cpu/cc26xx-cc13xx/rf-core/prop-mode.c

This pull request fixes an issue in the cc26xx-cc13xx oscillator control which causes occasional faults and device lockup.
When running both ContikiMAC and the BLE beacon process, the ContikiMAC interrupt will occasionally preempt the beacon process while it is modifying the oscillators. This causes occasional bus faults and infinite loops if it happens at just the right time.
This pull request prevents the conflicts by checking that the BLE beacon is not active prior to modifying the oscillators.

cc26xx-cc13xx oscillator control issue

---

cpu/cc26xx-cc13xx/rf-core/rf-ble.c

This pull request fixes an issue in the cc26xx-cc13xx BLE beacon process.
The rf_ble_beacon_process yields the thread using PROCESS_WAIT_EVENT() which allows the process to continue when _any_ event is posted rather than checking that the event timer has expired, which is what we really want. This pull request adds a check for ble_adv_et event timer expiration, which prevents broadcasts from sensor updates, etc. from triggering the BLE beacon.

cc26xx-cc13xx BLE beacon event issue

---

tools/collect-view/src/org/contikios/contiki/collect/MoteFinder.java
tools/collect-view/src/org/contikios/contiki/collect/SerialDumpConnection.java

Select the tools for macos when checking for motes or opening a
serial dump connection on OS X.

collect-view gui: Add support for OS X serialdump and motelist

---

examples/ipv6/native-border-router/slip-config.c

When running the native border router on my raspbian installation it would always fail because for some reason the while loop would not consider the statement to be true.
My best guess would be that the -1 value for a char is `0xFF` while the same for an int would be `0xFFFFFFFF`.

Add typecast to native border router switch statement

---

core/cfs/cfs-coffee.c
core/cfs/cfs-coffee.h

Improved mainly the comments, debug statements and source code formatting. Also changed type of sector indices to cfs_page_t in case <code>uint16_t</code> is too small.

Coffee: improve comments and code formatting

---

platform/avr-atmega128rfa1/Makefile.avr-atmega128rfa1
platform/avr-atmega128rfa1/contiki-conf.h

Set operating speed to 16MHz and added missing dependency to llsec.
This fix was tested with sparkfun ATmega128RFA1 Dev Board.

Fixed using target AVR ATmega128RFA1

---

core/net/rpl/rpl-conf.h
regression-tests/Makefile.simulation-test

This PR:
* Disables DAO-ACK by default, as it seemed to cause a failure on test `04-rpl-large-network.csc` with random seed 1, triggering a new run with seed 5. As this is one of the longest tests, this often triggered a Travis timeout;
* Uses a single seed for all simulation tests (instead of two). Now a failure on a single seed will cause a complete failure of the non-regression test.

Fixing 04-rpl-large-network

---

core/net/mac/tsch/tsch-slot-operation.c

This particular log was mostly creating noise

TSCH: remove 'not for us' log

---

core/net/rpl/rpl-conf.h

I'm pretty sure the intended default lifetime was 30 times 60 seconds, not 48 times 96 seconds.

RPL default lifetime

---

core/net/rpl/rpl-icmp6.c

This fix makes sure the `dao_sequence` stored in `my_dao_seqno` is the same used in the outgoing DAO

DAO ACK fix

---

dev/cc1200/cc1200.c
examples/zolertia/zoul/cc1200-sniffer/Makefile
examples/zolertia/zoul/cc1200-sniffer/Makefile.target
examples/zolertia/zoul/cc1200-sniffer/README.md
examples/zolertia/zoul/cc1200-sniffer/netstack.c
examples/zolertia/zoul/cc1200-sniffer/project-conf.h
examples/zolertia/zoul/cc1200-sniffer/sniffer.c
examples/zolertia/zoul/cc1200-sniffer/stub-rdc.c

This PR allows the CC1200 to run the [Sensniff](https://github.com/g-oikonomou/sensniff) Sniffer application.  This has been tested with the `RE-Mote` platform extensively.
As it is heavily based on the `cc2538dk` sniffer application (well, copy/pasted) I'm open for suggestions to have a single sniffer application, instead of instances per platform (there's was also a previous PR with support for the Z1 mote).

Added sensniff support for the CC1200

---

core/net/rpl/rpl-icmp6.c

We currently do not retransmit nopath DAOs nor do anything when getting an ACK for them. This PR removes the K flag from nopath DAOs to make sure no ACK is sent.

RPL: do not add K flag to no-path DAO as we discard the ACK anyway

---

core/net/mac/tsch/tsch-log.c

This PR prevents possible NULL pointer access for `log->link` in `tsch_log_process_pending()`.
`log->link` would have NULL if `current_link` is NULL when `tsch_log_prepare_add()` is called. This could happen in `tsch_slot_operation` Protothread. Here is the relevant code block, where the TSCH_LOG_ADD macro expands with `tsch_log_prepare_add()` when TSCH_LOG_LEVEL is greater than or equal to 2.
```C
if(current_link == NULL || tsch_lock_requested) { /* Skip slot operation if there is no link
or if there is a pending request for getting the lock */
/* Issue a log whenever skipping a slot */
TSCH_LOG_ADD(tsch_log_message,
snprintf(log->message, sizeof(log->message),
"!skipped slot %u %u %u",
tsch_locked,
tsch_lock_requested,
current_link == NULL);
);
```

Handle the case when log->link is NULL in tsch_log_process_pending

---

examples/cc26xx/cc26xx-demo.c
examples/cc26xx/cc26xx-web-demo/cc26xx-web-demo.c
examples/cc26xx/cc26xx-web-demo/cc26xx-web-demo.h
examples/cc26xx/cc26xx-web-demo/coap-server.c
examples/cc26xx/cc26xx-web-demo/resources/res-leds.c
platform/srf06-cc26xx/README.md
platform/srf06-cc26xx/common/board-spi.c
platform/srf06-cc26xx/common/board-spi.h
platform/srf06-cc26xx/common/ext-flash.c
platform/srf06-cc26xx/common/ext-flash.h
platform/srf06-cc26xx/contiki-main.c
platform/srf06-cc26xx/launchpad/Makefile.launchpad
platform/srf06-cc26xx/launchpad/board-peripherals.h
platform/srf06-cc26xx/launchpad/board.c
platform/srf06-cc26xx/launchpad/button-sensor.c
platform/srf06-cc26xx/launchpad/button-sensor.h
platform/srf06-cc26xx/launchpad/cc2650/Makefile.cc2650
platform/srf06-cc26xx/launchpad/cc2650/board.h
platform/srf06-cc26xx/launchpad/launchpad-sensors.c
platform/srf06-cc26xx/launchpad/leds-arch.c
platform/srf06-cc26xx/sensortag/Makefile.sensortag
platform/srf06-cc26xx/sensortag/ext-flash.c
regression-tests/18-compile-arm-ports/Makefile

This adds support for one more CC26xx board: the new LaunchPad
We support LEDs and Buttons and also the LP's external flash.
The flash is a Macronix part with an instruction set that is basically a superset of the one of the Winbond part present on Sensortags. Thus, we extend the sensortag flash driver to support this additional part and we use the same driver for both boards. We create a `common` dir under `srf06-cc26xx` and we put the flash and SPI drivers therein. These are shared across the two boards for now, but it's really meant as a pool of drivers for devices present on more than one board.
This pull also extends cc26xx examples to support the LP and adds compile tests for LP builds

Add support for the CC2650 LaunchPad (LAUNCHXL-CC2650)

---

core/cfs/cfs-coffee.c
core/cfs/cfs-coffee.h

We encountered the problem with trailing zeros in files leading to wrong file size. This fix ensures that all bytes will get set to zero and works fine for us as it ensures that there are no zeros in the buffer on adresses we expected to get set to the content of the file. Also as long as there are enough bytes to read in the file the execution time should't increase at all. In cases that the given size only represents the size of the buffer and there are way less bytes to be read in the file the execution time will slightly increase.

Trailing zeros in file leading to unexpected file length get set in destination buffer

---

core/cfs/cfs-coffee.c

Files opened with `CFS_READ` should not allow seeking past the end of the file.

core/cfs: Disallow seeking past the end of a file unless it is writable

---

platform/z1/contiki-z1-main.c

In case of using IPv4,  `contiki-z1-main.c` uses a wrong include.

Fix broken include

---

cpu/msp430/dev/uart0-putchar.c
cpu/msp430/dev/uart1-putchar.c

In case of using IPv4, `putchar()` is provided by the SLIP device. The missing `#ifndef` result into an error: `multiple definition of 'putchar'`

Fix putchar include when using IPv4

---

apps/ipso-objects/ipso-temperature.c

Like the IPSO documentation says
http://unitsofmeasure.org/
https://loinc.org/usage/units

ipso-temperature: Use "Cel" for degrees celsius

---

examples/ravenusbstick/Makefile.ravenusbstick
platform/avr-ravenusb/cdc_task.c

Two errors have been spotted, when IPv6 is enabled in the **ravenusb**
Project-Makefile:
`#CONTIKI_NO_NET=1`
`CONTIKI_WITH_IPV6=1`
The compile error results from a variable name mismatch in `cdc_task.c`
The variable `r` is undeclared and should be renamed to `route`
The linker also fails with _undefined references_
This has been mediated by adding `core/net` to Modules in the
Project-Makefile.

Fix for IPv6 compilation and linkage errors

---

platform/stm32nucleo-spirit1/README.md

Added github accounts of the maintainers (now STclab is an organization account), a Documentation section pointing to resources on ST website. Other small fixes in other sections.

Update to stm32nucleo-spirit1 platform README file.

---

tools/sky/msp430-bsl-linux
tools/zolertia/z1-bsl
tools/zolertia/z1-bsl-nopic

The the author of the library *pyserial* removed the command `setBaudrate()` starting from version 3.0. This PR solves problems caused by that in the bsl by setting the baudrate directly.
*pyserial* 3.0 is just upcoming for example in Debian stretch.

Do not use setBaudrate

---

platform/srf06-cc26xx/launchpad/Makefile.launchpad

This PR simply adds the upload command to the Makefile of the CC2650 Launchpad addressing the comment of @joakimeriksson on the already merged [#1485](https://github.com/contiki-os/contiki/pull/1485) pull request. I also confirm that the BSL script worked for me on Mac OS X without any problem after addressing the changes described by @g-oikonomou and also setting the `SET_CCFG_BL_CONFIG_BL_LEVEL` to `0x0` in the `ccfg.c` file.
I have set `115200` as predefined baud rate for the script.

Add upload script to Makefile.launchpad

---

regression-tests/20-ip64/01-cooja-ip64-http-socket.csc
regression-tests/21-large-rpl/testscript.js

This PR resolves errors raised on executing two of the regression tests, `20-ip64` and `21-large-rpl`, under Instant Contiki (a non Travis environment).
Here are error messages you'll see with the tests:
```shell
user@instant-contiki:~/contiki$ make -C regression-tests/20-ip64 RUNALL=yes summary
make: Entering directory `/home/user/contiki/regression-tests/20-ip64'
Running test 01-cooja-ip64-http-socket with random Seed 1: .... INFO [main] (Cooja.java:1781) - 
(snip)
FATAL [Thread-5] (LogScriptEngine.java:312) - Test script error, terminating Cooja.
FATAL [Thread-5] (LogScriptEngine.java:313) - Script error:
java.lang.reflect.UndeclaredThrowableException
at com.sun.proxy.$Proxy5.run(Unknown Source)
at org.contikios.cooja.plugins.LogScriptEngine$4.run(LogScriptEngine.java:300)
at …
```

Fix the path for wpcapslip in testscript for Instant Contiki

---

apps/oma-lwm2m/lwm2m-plain-text.c

Fixes bug: If no decimal point is present then the entire number is treated as the decimal part instead of as the integer part

oma-lwm2m: Handle text/plain floatfix numbers without decimal point

---

platform/zoul/contiki-main.c

No brainer, fixes a typo in `PLATFORM_HAS_BUTTON`

Fixed typo in button definition

---

cpu/cc26xx-cc13xx/lpm.c
cpu/cc26xx-cc13xx/lpm.h

Bug fixes include:
- keep interrupts disabled during lpm_sleep() so that we don't miss any interrupts we may have been expecting.
- check that the pending etimer isn't already expired (and don't sleep at all if it is)
- check that the about-to-be scheduled rtimer wakeup is neither too far into  the future nor too close into the future (or even in the past) before actually setting the interrupt (should fix #1509); If the time is out of bounds we use a default min or max value instead.
- Correctly handle LPM_MODE_MAX_SUPPORTED set to zero (and added a macro for the zero value) so that sleeping can be disabled altogether
- If no etimer is set, we specify a wakeup time which is reasonably far into the future instead of setting none at all (this will save on power consumption whenever no …

Fixed numerous bugs in CC26xx-CC13xx lpm

---

platform/srf06-cc26xx/README.md
platform/srf06-cc26xx/common/ext-flash.c
platform/srf06-cc26xx/contiki-main.c
platform/srf06-cc26xx/launchpad/cc1310/Makefile.cc1310
platform/srf06-cc26xx/launchpad/cc1310/board.h
regression-tests/18-compile-arm-ports/Makefile

This pull request adds support for TI's CC1310 Launchpad.
We support LEDs and Buttons and also the LP's external flash. Examples under `examples/cc26xx` should work off-the-shelf.
According to the CC1310LP design files, the flash on it is the same as the flash on the CC2650 LP (MX25R8035F 8Mbit). However, the flash on some CC1310 LPs reportedly identifies itself as the 16Mbit one (MX25R1635F) instead. Instruction sets are identical, we simply need to tell the driver to recognize this part's Device ID. Thus, this pull also extends the driver to support this part, in case any user happens to have one of those launchpads.
Build with `BOARD=launchpad/cc1310`.
This pull also adds a travis test for the CC1310 LP build.

Add support for the CC1310 LaunchPad (LAUNCHXL-CC1310)

---

core/net/mac/tsch/tsch-slot-operation.c
core/sys/rtimer.h
cpu/arm/aducrf101/aducrf101-contiki.h
cpu/mc1322x/contiki-mc1322x-conf.h
platform/cc2538dk/contiki-conf.h
platform/cooja/contiki-conf.h
platform/galileo/contiki-conf.h
platform/jn516x/platform-conf.h
platform/mbxxx/platform-conf.h
platform/openmote-cc2538/contiki-conf.h
platform/seedeye/contiki-conf.h
platform/srf06-cc26xx/contiki-conf.h
platform/stm32nucleo-spirit1/platform-conf.h
platform/zoul/contiki-conf.h

On platforms with 16-bit rtimer, the current `estimated_drift` is wrong when either (but not both) `expected_rx_time` or `rx_start_time` has wrapped. This sends the node straight off sync.
The fix introduces a new macro `RTIMER_CLOCK_DIFF`, defined exactly where `RTIMER_CLOCK_LT` was already set.

Fix bug in TSCH for platforms with 16-bit rtimer

---

cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
platform/srf06-cc26xx/launchpad/Makefile.launchpad
platform/srf06-cc26xx/srf06/Makefile.srf06

The block that controls the `.upload` target is unnecessarily replicated in multiple sub-board Makefiles. This was originally done because the SmartRF and the Launchpad can be programmed with the c2538-bsl script, whereas the sensortag cannot.
This commit moves the `cc2538-bsl` / `.upload` target logic to the top level platform Makefile (`platform/srf06-cc26xx/Makefile.srf06-cc26xx`). Board makefiles simply set the make variable `BOARD_SUPPORTS_BSL` to 1 to signal that they can be programmed by the BSL script. If `BOARD_SUPPORTS_BSL` is not equal to 1, trying to use the `.upload` target will return an error message.
For example:
```
$ make BOARD=sensortag/cc2650 cc26xx-demo.upload
using saved target 'srf06-cc26xx'
This board cannot be programmed with the ROM bootloader and therefore does …
```

Consolidate .upload for all CC26xx/CC13xx boards and add login make target

---

core/net/ip/uip-debug.c
core/net/ip/uip-debug.h
core/net/mac/frame802154e-ie.c
core/net/mac/tsch/tsch-log.c
core/net/mac/tsch/tsch-packet.c
core/net/mac/tsch/tsch-queue.c
core/net/mac/tsch/tsch-rpl.c
core/net/mac/tsch/tsch-schedule.c
core/net/mac/tsch/tsch-security.c
core/net/mac/tsch/tsch-slot-operation.c
core/net/mac/tsch/tsch.c
core/net/net-debug.c
core/net/net-debug.h
platform/mbxxx/contiki-main.c

This PR moves non IP related debug functions from `ip-debug.[ch]` to `net-debug.[ch]`, enabling the use macros such as `PRINTF` and `PRINTLLADDR` in code that may run without IP.

Added net-debug.[ch] to provide debug functions even in the non-IP case

---

examples/rime/example-unicast.c

This PR simply adds a packet sent callback to the unicast connection used in the example to better illustrate the possibilities of the unicast primitive. Every time a packet is sent the callback is called and prints the linkaddr_t destination, the MAC status of the message sent, and the link layer number of transmissions of the packet. The PR also removes some unneeded headers for the example.

RIME: Extend unicast example to include a sent callback.

---

regression-tests/21-large-rpl/testscript.js

With a timeout set to 40 min, this test often failed at about 95% of the script, causing many spurious pull request test failures. Increase the timeout to 50 min.

21-large-rpl: Avoid frequent timeout in Travis CI

---

core/sys/process.c

This allows the optimizer to put the corresponding variables into registers.
See also discussion about other static variables:
https://sourceforge.net/p/contiki/mailman/message/35010460/

Removed some unnecessary statics in do_event() and process_post().

---

core/net/rime/chameleon-raw.c

Fix the bug #1675.
If the length of some packet attribute is larger than 8, chameleon raw module's `hdrsize()` will return an incorrect header size.
This patch make the `hdrsize()` compatiblie with underlying packet attribute that the length is larger than 8.

fix the bug about chameleon raw hdrsize

---

core/net/ipv6/uip-nd6.c
core/net/nbr-table.c
core/net/nbr-table.h

This is a fix for ND6 that makes the nbr-table have two entries with the same link layer address. This cause permant disconnect from RPL root (until global repair or reboot). The reason it happens is that the nbr table allow adding a NULL entry for the neighbor discovery to handle the case when there is not yet any know link layer address. The NA code then just do a memcopy so that NULL suddenly is a valid link layer address and when that happen to exist in the tables already - things break down. This fix removes the NULL entry and re-installs it again to avoid the problem.
This bug was found by the Intel IoT team in Malaysia that have been testing the 6LoWPAN stack significantly so many thanks for your efforts! (@jeremy-ang, @usmansarwar and @pedquarkbld).

Removed memcpy that cause inconsistency in nbr-table when adding nd6 neighbors.

---

.travis.yml
cpu/6502/Makefile.6502
platform/apple2enh/Makefile.apple2enh
platform/atarixl/Makefile.atarixl
platform/c128/Makefile.c128
platform/c64/Makefile.c64
tools/6502/Makefile

The new cl65 option --print-target-path allows to get rid of CC65_HOME altogether.

Make use of new cl65 option --print-target-path.

---

dev/enc28j60/enc28j60.c
dev/enc28j60/enc28j60.h

I have changed the ptr argument passed to init/send/write to const in the enc28j60 driver.
I made the change because I was passing a const from my own code, which was causing a compiler error.

Changed read-only pointers to const in enc28j60

---

core/net/http-socket/http-socket.c

Currently, http-socket uses a `parse_url` method which only works correctly with IPv4 hosts (e.g. `http://192.168.1.1:3000`).  When using an IPv6 host (e.g. `http://[abcd::1]:3000`), the port number is not parsed due to a pointer increment error, which leads to the algorithm assuming a default port of 80 even when the user code has specified otherwise.  This fix provides full URL parsing for IPv6 hosts, and does not break IPv4 functionality.

Fix IPv6 HTTP URL parsing

---

core/net/ip/resolv.c

On platforms which do not define the macro ```__SDCC``` the ```strcasecmp``` function may not have a definition (this happens at least on CC26xx). The prototype for this function is now defined if ```__SDCC``` is false.

Fix warning about missing strcasecmp definition

---

apps/at-master/Makefile.at-master
apps/at-master/at-master.c
apps/at-master/at-master.h
examples/zolertia/zoul/at-test/Makefile
examples/zolertia/zoul/at-test/at-master-test.c
examples/zolertia/zoul/at-test/project-conf.h

This PR includes support to implement AT commands to interact with the nodes, allowing to drive devices over UART ports (USB and alike).  An example shows how to implement an AT-based API.

AT driver (master) and example

---

tools/cooja/java/org/contikios/cooja/Simulation.java

This is an old bug of mine. As mine was the only plug-in that actually needed this, and only because it always added nodes from the simulation-thread, this never popped up.

Cooja: Make sure motes are always removed from the list of unintialized motes

---

tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/Msp802154BitErrorRadio.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/Msp802154Radio.java

This Cooja interface more accurately models bit errors as observed in IEEE 802.15.4-compatible radios, such as CC2420 and CC2520.
Only errors due to signal fading are supported, as opposed to errors to interference. Interesting and quite realistic performance can be observed if this is used together with a dynamic channel fading model.
A usage example [is available here](https://github.com/atiselsts/contiki/commit/758202de6c2dfd28d2fc3199b336d2b15a8df5f0). The example includes two `.csc` files, one using the existing Msp802154Radio and one the new Msp802154BitErrorRadio, but otherwise identical. The BitError example shows corrupted packets detected by the Contiki `.c` code and occasionally packets being completely lost (due to corruption in the header).
This pull request is based on work …

Cooja: add Msp802154BitErrorRadio interface

---

core/net/ipv6/uip6.c

Some "temporary" variables were declared with static storage duration for no good reason.
Replaced them with local stack variables wherever they were used.
There are still some variables that are unnecessarily given static duration which I have left alone.

Put some uip6 temporaries on the stack

---

core/net/rpl/rpl-ext-header.c

According to [RFC 2460](https://tools.ietf.org/html/rfc2460#section-4.3) the length field of the Hop-by-Hop options header uses a 8-octet unit (multiple of 8 byte). This is also correctly handled in [`uip6.c`](https://github.com/contiki-os/contiki/blob/master/core/net/ipv6/uip6.c#L1168), but not when setting up the header.
In a normal configuration the `RPL_HOP_BY_HOP_LEN` define is 8, so the current implementation works, but it is a bit misleading.
This fix is needed, when `RPL_HOP_BY_HOP_LEN` is more than 8. For example when adding extra elements to the `uip_ext_hdr_opt_rpl` for a custom header extension (eq. tracing packets).

rpl-ext-header: Use 8-octet unit for HBHO length

---

cpu/cc2538/Makefile.cc2538
cpu/cc2538/dev/sys-ctrl.c
cpu/cc2538/dev/sys-ctrl.h
cpu/cc2538/soc.c
cpu/cc2538/soc.h
platform/cc2538dk/contiki-main.c
platform/openmote-cc2538/contiki-main.c
platform/zoul/contiki-main.c

Print the following SoC information upon startup with `STARTUP_CONF_VERBOSE`:
- chip ID,
- revision,
- Flash memory size,
- SRAM size,
- enabled hardware features (AES/SHA, ECC/RSA),
- system clock frequency,
- I/O clock frequency,
- reset cause.
This makes it possible to have most useful information at hand without having to search for it. This can also be useful for debug logs.
With these changes, the first lines printed on boot look like this:
```
Contiki-3.x-2605-g9845973
Zolertia Firefly platform
CC2538: ID: 0xb964, rev.: PG2.0, Flash: 512 KiB, SRAM: 32 KiB, AES/SHA: 1, ECC/RSA: 1
System clock: 16000000 Hz
I/O clock: 16000000 Hz
Reset cause: POR
Rime configured with address 0f:0c
Net: Rime
MAC: CSMA
RDC: nullrdc
```

Print CC2538 info on boot

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-relay.c
platform/zoul/dev/relay.c
platform/zoul/dev/relay.h

This is a simple driver I often get asked to provide.  It basically allows to connect a common relay module (such as this one from [Phidget](http://www.phidgets.com/products.php?category=9&product_id=3052_1) or this one from [Seeedstudio](https://www.seeedstudio.com/item_detail.html?p_id=769)).

Added generic relay driver for the zoul-based platforms

---

core/net/ip/simple-udp.c

If the given local port is 0, we get no replies.

Allow creating connections on unspecified local port

---

core/net/rpl/rpl-timers.c

Clang seems not to discover that the statement is always false (while GCC does) and therefore complains about lack of the function called within the always false block e.g. rpl_ns_periodic();. Olaf Bergmann reported it to me and I got the same problem compiling with clang on my OS-X. This fix the issue.

Fix for compilation with clang - issue reported by Olaf Bergmann

---

core/net/mac/tsch/README.md
cpu/cc26xx-cc13xx/clock.c
cpu/cc26xx-cc13xx/dev/soc-rtc.c
cpu/cc26xx-cc13xx/lpm.c
cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
cpu/cc26xx-cc13xx/rf-core/prop-mode.c
cpu/cc26xx-cc13xx/rf-core/rf-core.c
cpu/cc26xx-cc13xx/rf-core/rf-core.h
cpu/cc26xx-cc13xx/rtimer-arch.h
platform/srf06-cc26xx/contiki-conf.h
platform/srf06-cc26xx/contiki-main.c

This pull request adds a full-featured (HW timetamps, polling mode, etc.) TSCH port on CC26xx. This port has been tested for several months in a small testbed with custom CC26xx SoC based devices at the University of Bristol.
Depends on #1708 and #1684 (#1708 is used as the base branch, and some cherry-picked commits included from #1684).
Fixes #1615.

TSCH port for CC26xx  

---

core/net/ip/uip-udp-packet.c

When an UDP packet too big to fit in the uIP packet buffer is to be sent, the part fitting in the uIP buffer is copied to it (so no buffer overflow occurs) but uIP actually sends a packet of the original size therefore a buffer over-read occurs.
This modification makes uIP sends only the data copied to the packet buffer. An alternative would be not to send anything and return an error.

Prevent uIP buffer over-read with big UDP packets

---

core/cfs/cfs-coffee.c
core/cfs/cfs.h
platform/native/cfs-coffee-arch.h
platform/sky/cfs-coffee-arch.h

* Simplify Coffee by changing certain CPP conditionals to C conditionals, which should be possible for the compiler to optimize based on their constant values.
* Remove the I/O semantics conditional because it is good to have consistent API across Coffee ports.
* Change the struct cfs_dir internal variable name to something more sensible.
* Minor clean up of the source code.

Coffee: minor enhancements

---

core/net/llsec/noncoresec/noncoresec.c
cpu/cc2538/dev/aes.c

Depending on the use case and on the timings, `auth_crypt_check_status()` sometimes never reported an available result, leading to a deadlock of any protothread waiting for this event, and to a `WDT` reset if a protothread was polling it.
This was caused by `aes_auth_crypt_start()` clearing the result available interrupt after operations that may rightfully trigger it, leading to a missed interrupt.
This PR also fixes build errors discovered in `noncoresec` with `DEBUG` set to `1` while investigating this issue. Even if `noncoresec` is removed soon, it's better to fix this in the meantime.

cc2538: aes: Fix possibly missing result available status

---

cpu/cc2538/dev/cc2538-aes-128.c

First, I adapted the `cc2538_aes_128_driver` to reboot if an error occurs. I also considered handling errors, but I think that this would result in a lot of rarely tested code. After all, I have never actually encountered errors when calling `cc2538_aes_128_driver`. Nevertheless, I am afraid that an attacker may provoke errors and then bad things may happen.

One fix to CC2538 hardware security

---

platform/srf06-cc26xx/contiki-conf.h

`CC2650_FAST_RADIO_STARTUP` is required for TSCH, but it currently breaks ContikiMAC. We set the default value to the one that will work with the default choice of RDC.
I'm also moving the define to a place in `contiki-conf.h` closer to where the user will look in order to configure the RDC driver.
Fixes #1744

Disable CC2650_FAST_RADIO_STARTUP by default

---

core/net/ip/uip-udp-packet.c
core/net/ipv6/multicast/README.md
core/net/ipv6/multicast/uip-mcast6.h
core/net/ipv6/uip-ds6.c
core/net/ipv6/uip6.c
core/net/rpl/rpl-dag.c
core/net/rpl/rpl-icmp6.c
core/net/rpl/rpl-private.h
core/net/rpl/rpl-timers.c
core/net/rpl/rpl.c
examples/ipv6/multicast/intermediate.c
examples/ipv6/multicast/root.c
examples/ipv6/multicast/sink.c

This PR fixes an issue that a link-local address is used as the source address of a packet destined to a routable multicast address. You can see this issue with `examples/ipv6/multicast/multicast.csc`. Multicast packets to `ff1e::89:abcd` have a link-local address, `fe80::212:7401:1:101`, as their source address. After applying the change, their source address become `fd00::212:7401:1:101`.
I found this issue has been reported with Issue #1292. As per @g-oikonomou comment on #1292, I replaced `UIP_CONF_IPV6_MULTICAST` with `UIP_IPV6_MULTICAST`. In addition, I renamed `RPL_CONF_MULTICAST` to `RPL_WITH_MULTICAST` because it doesn't seem to be a user configuration, either.

Fix the source address selection for multicast packets

---

core/net/ipv6/multicast/esmrf.c
core/net/ipv6/multicast/esmrf.h
core/net/ipv6/multicast/uip-mcast6.h
core/net/ipv6/uip-icmp6.h

ESMRF is an enhanced version of the SMRF engine with the aim of resolving the sending limitation of SMRF to allow any node within the DODAG to send multicast traffic up and down the RPL tree. you could find all details in the following paper https://drive.google.com/file/d/0B69lRSPVb6vDZ3AwWHk1S25sNGc/view?usp=sharing
The main idea of ESMRF is the multicast-on-behalf service which gives the RPL root the ability to forward the multicast traffic on behalf of the original sources. We demonstrated that ESMRF has the same performance with the SMRF in case the root of RPL is the source of multicast traffic and provides a promising performance in the case of the leaf nodes are  the source of multicast traffic in which case SMRF totally fails to deliver any multicast packets.

A new multicast engine called ESMRF for RPL

---

core/net/rpl/rpl-ext-header.c

This PR addresses mainly two bugs in `rpl-ext-header.c`.
1. The system crashes or falls into an infinite loop when it encounters an unsupported protocol header
(roughly speaking).
2. A RPL header to be processed is not handled properly unless it comes just after an IPv6 header.
You can confirm the first one with a packet unsupported by Contiki. For example, on sending a simple UDP-Lite packet to a mote running on Cooja, Cooja crashes by SIGSEGV. When the mote runs with Non-Storing mode enabled, Cooja stalls because the mote does not release CPU.
For the second bug, I used a packet which had a Destination Options header followed by a RPL Routing header. The Destination Options header had only one PadN option. Contiki was not able to find the RPL Routing header.

Improve RPL extension headers handling

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
platform/srf06-cc26xx/contiki-main.c

This fixes a problem that appears when CC2650_FAST_RADIO_STARTUP is set to 1: radio `on()` could occasionally be called without requesting HF crystal oscillator before trying to use it, leading to reboots.
This change unconditionally requested the HF crystal oscillator in `on()`, which is very fast in case the oscillator already has been requested before and is ready.

CC26xx: always request HF crystal oscillator at radio on()

---

platform/z1/contiki-conf.h

Minor changes:
* Moved `project-conf.h` inclusion to the top of `contiki-conf.h`, as configurable parameters are defined beforehand, thus requiring to `#undef` first.
* Made common parameters overridable
* Added `BOARD_STRING` platform definition

Minor changes to z1/contiki-conf.h

---

platform/zoul/Makefile.zoul

This adds support for flashing to multiple devices, by implementing the
$MOTES option used by the Z1.
This replaces the $PORT interface, as it only allowed flashing to one
device at a time, and the $MOTES interface was still used for other
tasks (such as getting a list of connected devices).
A foreach loop is used to dynamically create an upload rule per device
that needs to be flashed.
The "main" upload rule depends on the device specific ones.
This allows for parallel flashing.

zoul: Add support for flashing to multiple devices

---

core/net/mac/frame802154.c

I stumbled upon this warning when trying out the new GCC 6.1 release:
```
../../../contiki/core/net/mac/frame802154.c: In function ‘frame802154_has_panid’:
../../../contiki/core/net/mac/frame802154.c:151:30: warning: self-comparison always evaluates to true [-Wtautological-compare]
if(fcf->dest_addr_mode == fcf->dest_addr_mode) {
^~
```
I believe this is a typo and that the correct fix is the supplied PR, but please validate this independently.

core/net/mac/frame802154: Fix typo in PAN ID compression condition

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-dht22.c
platform/zoul/dev/dht22.c
platform/zoul/dev/dht22.h

This PR adds the [DHT22](https://www.adafruit.com/product/385) (the same as AM2302) sensor driver and test example, widely used and sold by different vendors, such as Grove, Adafruit, Sparkfun, etc.

Added DHT22 sensor to Zoul-based platforms

---

core/net/mac/tsch/tsch-slot-operation.c
platform/srf06-cc26xx/contiki-conf.h

This essentially fixes the guard time for ACK packets in TSCH. The default guard time led to a large number of missed ACKs because the first call to `receiving_packet()` returns with 352 usec delay on CC26xx, and the unadjusted ACK guard time is just 400 usec.

TSCH: add RADIO_DELAY_BEFORE_DETECT to rx guard time when waiting for a packet to be received

---

platform/srf06-cc26xx/contiki-conf.h

This change enables to run TSCH on CC26xx without application-specific configuration settings (i.e. without setting `CC2650_FAST_RADIO_STARTUP` to 1).
It fixes two real problems:
1) The early wakeup due to `CC2650_FAST_RADIO_STARTUP` requires additional energy compared to the "normal" wakeup at the start of an active TSCH slot.
2) Since `CC2650_FAST_RADIO_STARTUP` is not the default setting, it means that TSCH applications have to be explicitly ported to CC26xx by adding an application-specific setting. This is potentially confusing to new users. It is also not a good design since this approach would not scale well (in terms of more platforms).
The change introduces slightly "nonstandard" TSCH guard times for this platform. Numerous experiments have shown that slightly reducing the TSCH …

CC26xx: change default TSCH guard time to 1.8ms

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c

This pull request fixes the current, invalid logic in CC26xx IEEE mode radio driver, which messed up the global interrupt state.

CC26xx: enable MCU sleeping while transmitting if and only if not in poll mode

---

cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
cpu/cc26xx-cc13xx/dev/soc-trng.c
cpu/cc26xx-cc13xx/dev/soc-trng.h
cpu/cc26xx-cc13xx/random.c
cpu/cc26xx-cc13xx/ti-lib.h
platform/srf06-cc26xx/contiki-main.c

This pull request adds support for the CC13xx/CC26xx hardware RNG.
The hardware has 24 free-running oscillators (FROs) and generates random numbers by sampling them. The longer we let the hardware sample the FROs, the more entropy we will get in our random number. Thus, the hardware can generate low-entropy random numbers super quickly, or it can generate high-entropy random numbers, but this takes longer.
In this context, the driver can work in two modes:
* Synchronous mode: We issue a request to the hardware to generate a new, minimum-entropy random number and we block till it's ready. This function is thread-safe and can be called from inside an interrupt context. It is recommended to use this mode when a low-entropy number is required and therefore generation can be performed quickly. …

Add CC13xx/CC26xx TRNG Support

---

cpu/cc2538/dev/cc2538-rf.c

This pull request:
* Changes `get_sfd_timestamp()` and `mac_timer_init()` to static.
* Improves the code style of the CC2538 RF driver.

Improve code style of the CC2538 RF driver

---

core/net/mac/tsch/tsch-packet.c
core/net/mac/tsch/tsch.c
examples/rime-tsch/Makefile
examples/rime-tsch/node.c
examples/rime-tsch/project-conf.h

This PR makes TSCH work with short addresses and Rime. Added new example for Rime/TSCH. Useful for testing TSCH without a full IPv6 stack.
Note that this PR includes https://github.com/contiki-os/contiki/pull/1609

TSCH with Rime

---

core/net/ip/tcpip.c
core/net/ipv6/uip-icmp6.c
core/net/ipv6/uip6.c
core/net/rpl/rpl-ext-header.c
examples/ipv6/rpl-tsch/node.c
examples/ipv6/rpl-tsch/project-conf.h
regression-tests/11-ipv6/19-z1-rpl-tsch.csc
regression-tests/11-ipv6/20-z1-rpl-tsch-orchestra.csc
regression-tests/11-ipv6/21-z1-rpl-tsch-security.csc

This PR adds missing calls to `rpl_insert_header` right after building Echo Request messages, before calling `tcpip_ipv6_output`. This results in a missing hop-by-hop option at the first hop. In this PR, `rpl_insert_header` is called consistently, for ICMP, UDP, and TCP. We add a check that the packet is not link-local before adding the header, as only routable unicast MUST include RPL headers.

Insert RPL ext header before sending ICMP, UDP and TCP messages

---

core/net/ipv6/sicslowpan.c

When SICSLOWPAN_FRAMER_HDRLEN is defined its value is used as a frame header length. This allows for using sicslowpan without calling a framer. This is usefull if framer is not used on a given platform or when header length is always the same. 
This PR doesn't change the default behaviour.
In addition an unused variable warning, which shows up when fragmentation isn't used, is fixed.

Allow for using a fixed frame header length in sicslowpan.c

---

apps/webserver/httpd-cgi.c
core/net/ipv6/uip-nd6.c
core/net/ipv6/uip6.c
cpu/6502/net/ethernet-drv.c
cpu/6502/net/ethernet-drv.h

Adds some casts, splits declaration and non constant initialization and changes a few prototypes. The cc65 compiler wasn't happy with implicit casts.

Fixes compilation targeting c64

---

core/net/mac/contikimac/contikimac.c

The first time that powercycle() runs, cycle_start is incremented
by CHECK_TIME twice which causes the second cycle to be late.
This commit fixes this.

Fixed wrong first cycle_start

---

cpu/x86/drivers/legacy_pc/uart-16x50.c
cpu/x86/drivers/legacy_pc/uart-16x50.h
cpu/x86/drivers/quarkX1000/uart.c
cpu/x86/drivers/quarkX1000/uart.h
platform/galileo/contiki-main.c

The first patch extends the Intel Quark X1000 SoC UART initialization API to accept a numeric baud rate specification.  This is useful for projects that require configuring a serial port with a particular baud rate.
The second patch fixes UART system call authorization initialization for applications that initialize both UARTs.

x86: Support configurable UART baud rate and fix initialization

---

core/net/rpl/rpl-ns.h

Fixes
```
In file included from ../../../contiki/core/net/rpl/rpl-private.h:48:0,
from ../../../contiki/core/net/mac/tsch/tsch-rpl.c:42:
../../../contiki/core/net/rpl/rpl-ns.h:70:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
void rpl_ns_periodic();
^~~~
```

core/net/rpl: Fix function declaration isn’t a prototype

---

platform/galileo/Makefile.galileo

This is required by the IPv6 implementation in Contiki OS.

galileo: Build link-stats.c when IPv6 is enabled

---

platform/galileo/README.md
platform/galileo/bsp/docker/Dockerfile

This patch adds a Dockerfile for building a container configured as a
build environment for Intel Galileo boards.  This patch also provides
documentation for using the containerized build environment.  Finally, it
streamlines the instructions for booting Contiki on Galileo and includes
other documentation refinements.

galileo: Add support for containerized build environment

---

cpu/cc2538/dev/ecc-algorithm.c
cpu/cc2538/dev/ecc-curve.c
cpu/cc2538/dev/sha256.h
platform/srf06-cc26xx/srf06/board.c

Fix a few typos that made some doxygen modules become orphans.

doxygen: Fix orphan modules

---

platform/cc2538dk/contiki-conf.h
platform/openmote-cc2538/contiki-conf.h
platform/zoul/contiki-conf.h

Enable the 32.768-kHz crystal on all the CC2538 platforms where it is present in order to get a better time accuracy.
This should avoid new cases of #1817 for in-tree platforms.

CC2538: Use the 32.768-kHz crystal if present

---

cpu/cc2538/dev/cc2538-rf.c

After reading a frame, `read()` checks the status of the RX FIFO:
* If an overflow is detected, the FIFO gets flushed
* If there are more frames in the FIFO, the `cc2538_rf_process` will get polled again in order to read out the next frame.
#1550 changed `read()`, which now performs the above check for non-poll mode, but it then flushes the FIFO unconditionally. Therefore, if there are two or more frames in the FIFO, they will get flushed before the `cc2538_rf_process` has had a chance to read them out. This results in missed frames.
Reproducing this is trivial: Build a CC2538 sniffer and see how it will never show you .15.4 ACK frames. ACK reception completes while `read()` is still streaming the previous captured frame to the host. Upon completion, the FIFO will get flushed and the ACK …

Don't flush the CC2538 RF RX FIFO unconditionally

---

tools/zolertia/motelist-zolertia

This PR adds the Firefly to the motelist's targets list.

Zoul: added firefly to motelist targets

---

cpu/cc2538/dev/uart.c

`lpm_enter()` must not enter PM1+ if the UART is transmitting. Otherwise, the UART clock gets disabled, and its TX is broken.
The commit b8b54a033c67e2dbb98dabda6d1b4c9e64d5db90 from #408 had already partially fixed this issue, but it could still occur while transmitting stop bits because, contrary to `UART_FR.BUSY`, `UART_FR.TXFE` takes only the data bits into account, not the stop bits.

cc2538: uart: Fix garbled output occurring upon lpm_enter()

---

cpu/cc26xx-cc13xx/rf-core/prop-mode.c

If `NETSTACK_CONF_RADIO.set_value(RADIO_PARAM_CHANNEL, ...)` is called when radio is on, it will fail to apply the channel change, because it won't re-send `CMD_PROP_RADIO_DIV_SETUP` and `CMD_PROP_FS`. This commit fixes this condition, by making sure the correct commands are sent to the radio.

Fix PROP mode channel switching

---

core/net/mac/framer-802154.c
core/net/mac/tsch/tsch-packet.c
core/net/mac/tsch/tsch-packet.h
core/net/mac/tsch/tsch.c

This PR does two things, in TSCH:
* move from ad-hoc seqno handling to the generic and standard-compliant mac-sequence module
* use sequence numbers only for unicast packets. We suppress it in broadcast. This has two benefits, (1) slows down the pace at which seqnos wrap and (2) save one byte in broadcast frames.
Together with https://github.com/contiki-os/contiki/pull/1738 this avoids spurious duplicate drops.

Improved TSCH sequence number handling

---

platform/zoul/dev/tmp102.c

Updates the value conversion by discarding the non-used bits.

Zoul: fix TMP102 value conversion

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-ac-dimmer.c
platform/zoul/dev/ac-dimmer.c
platform/zoul/dev/ac-dimmer.h

This PR adds support for an AC light dimmer using a zero-crossing trigger.  The specific AC dimming module is the [Krida Electronic's AC dimmer module](http://www.inmojo.com/store/krida-electronics/item/ac-led-light-dimmer-module-with-heatsink/).
[![](https://img.youtube.com/vi/cvkhv_EkM6Y/0.jpg)](https://youtu.be/cvkhv_EkM6Y)
The timings were verified using a logic analyser, for a 50Hz AC frequency.

Zoul: added driver to control an AC light dimmer with zero-crossing

---

examples/ipv6/rpl-udp/project-conf.h

In examples/ipv6/rpl-udp, the Non-Storing mode is not enabled properly by `make MAKE_WITH_NON_STORING=1`. You have to set 1 to `RPL_CONF_WITH_NON_STORING` in project-conf.h manually as well.
This PR fixes this situation. The solution is removing the `RPL_CONF_WITH_NON_STORING` definition block of project-conf.h.
According to the following block of core/net/rpl/rpl-private.h, we don't need to set `RPL_CONF_WITH_NON_STORING` explicitly if `RPL_CONF_MOP` is `RPL_MOP_NON_STORING`. For the rpl-udp example, `RPL_MOP_NON_STORING` is set to `RPL_CONF_MOP` if `WITH_NON_STORING` is 1, and this is the case when `make` runs with `MAKE_WITH_NON_STORING=1`.
```C
202 /* RPL Mode of operation */
203 #ifdef  RPL_CONF_MOP
204 #define RPL_MOP_DEFAULT                 RPL_CONF_MOP
205 #else /* RPL_CONF_MOP */ …
```

Make it easier to use the Non-Storing mode with the rpl-udp example

---

core/net/rime/chameleon-bitopt.c

Make set_bits_in_byte() static (like done yet  for get_bits_in_byte) ... 
Will fail to link on my system otherwise : 
```
contiki-native.a(chameleon-bitop): In Funktion `set_bits':
/home/blackdigi/workspace-cdt/contiki/examples/multi-threading//../../core/net/rime/chameleon-bitopt.c:192: Nicht definierter Verweis auf `set_bits_in_byte'
/home/blackdigi/workspace-cdt/contiki/examples/multi-threading//../../core/net/rime/chameleon-bitopt.c:202: Nicht definierter Verweis auf `set_bits_in_byte'
/home/blackdigi/workspace-cdt/contiki/examples/multi-threading//../../core/net/rime/chameleon-bitopt.c:208: Nicht definierter Verweis auf `set_bits_in_byte'
/home/blackdigi/workspace-cdt/contiki/examples/multi-threading//../../core/net/rime/chameleon-bitopt.c:212: Nicht definierter Verweis auf …
```

Make set_bits_in_byte() static (like for get_bits_in_byte)

---

platform/jn516x/dev/exceptions.c

This issue was reported some time ago ([jn516x platform: Software Reset raising exception](https://sourceforge.net/p/contiki/mailman/message/34612894/)) and I ran into it. By removing the exception handler for SYSCALLs the JN516x restarts as expected.

JN516x: Exception handler causing infinite loop

---

core/net/rpl/rpl-dag.c

When configuring a project to not use RPL parent probing (ex: we set RPL_CONF_WITH_PROBING to 0 in our project configuration), a misplaced bracket causes a compilation error in function rpl_select_parent of the file core/net/rpl/rpl-dag.c.

fix misplaced bracket causing compilation error when probing is disabled

---

apps/oma-lwm2m/lwm2m-engine.c

Adds a response to the top level lwm2m object to list all its instances as corelf.
Useful in conjunction with Copper to get the instance list directly without going through an LWM2M server. (Copper automatically adds the new elements to the resource list when it receives a response with content type set to application/link-format)

oma-lwm2m: Add functionality to send object instance list as core link format

---

platform/galileo/contiki-main.c
platform/galileo/net/eth-conf.c

This patch adds a process that is started automatically to request DHCP
configuration.  It also moves the IP configuration ahead of autostart processes
in case some autostart process depends on the IP configuration.

galileo: Add process to perform DHCP configuration

---

cpu/msp430/f2xxx/uart0.c

This PR request fixes UART0 initialization with a hard-coded UBR's MSB register to zero, preventing baudrates like 9600 from properly being configured. Tested for 115200 and 9600 baud rates, using any of the Z1 test examples with putty configured for the tested baudrates.

MSP430/F2xxx: fix ubr msb byte being hardcoded to zero

---

tools/cooja/java/org/contikios/cooja/util/ExecuteJAR.java

Cooja lacked support for including Wismote and Z1 motes when exporting simulations as executable JAR files. Earlier Cooja only supported Tmote Sky motes and this PR adds support also for Wismote and Z1 motes.

Added support in Cooja to include Wismote and Z1 motes when exporting simulations

---

examples/zolertia/zoul/rev-b/Makefile
examples/zolertia/zoul/rev-b/Makefile.target
examples/zolertia/zoul/rev-b/project-conf.h
examples/zolertia/zoul/rev-b/test-power-mgmt.c
examples/zolertia/zoul/rtcc/test-rtcc.c
platform/zoul/dev/rtcc-config.h
platform/zoul/dev/rtcc.c
platform/zoul/dev/rtcc.h
platform/zoul/remote-reva/power-mgmt.c
platform/zoul/remote-reva/power-mgmt.h
platform/zoul/remote-revb/Makefile.remote-revb
platform/zoul/remote-revb/power-mgmt.c
platform/zoul/remote-revb/power-mgmt.h

This PR adds support for the RE-Mote revision B power management block, allowing to:
- Measure the voltage level of external batteries connected to the RE-Mote via its nanowatt PIC
- Shutdown mode: powers down the whole board (CC2538, CC1200, sensors, components, etc), but the nanowatt PIC and the RTCC, allowing to reduce the current draw to 150nA
- Configures the shutdown mode's awake trigger: a soft shutdown using the nanowatt PIC's timer, or a hard shutdown by configuring first the RTCC, using its `INT2` trigger
- Read back the shutdown cycle counter, allowing the application space to trigger specific routines
- Retrieve the firmware version of the nanowatt PIC
A test application is included to verify the shutdown operation.
Depends on https://github.com/contiki-os/contiki/pull/1859

Zoul: power management driver for the RE-Mote revision B

---

platform/zoul/remote-reva/power-mgmt.h

this minor fixation to avoid Doxygen bug, which appears when doing this in the documented code:
/**
/* \exception \c text
*/
void foo();

Doxygen Fix

---

cpu/cc26xx-cc13xx/rf-core/rf-core.c
platform/srf06-cc26xx/README.md
platform/srf06-cc26xx/contiki-conf.h
platform/srf06-cc26xx/contiki-main.c

This pull adds support for the CC1350.
We only focus on CPU capability here.
Board support to follow in a separate pull request. We've got a little bit of work to do before we can properly support CC1350 boards, eg the brand new CC1350 LP (LAUNCHXL-CC1350). The main reason for this is that we need to make RF front-end / bias more configurable and we also need a clever way to support antenna switches, which is what the CC1350LP uses.

Add CC1350 support

---

platform/wismote/dev/battery-sensor.c

Have added Wismote battery voltage measurement support. Tested with `test-battery.c` example code and it works fine.

Wismote: Added support for Battery voltage measurement

---

apps/mqtt/mqtt.c

Fixed copy-paste typo in debug PRINTF definition of mqtt client

Fixed debug PRINTF definition in mqtt client

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-tsl256x.c
platform/zoul/dev/tsl256x.c
platform/zoul/dev/tsl256x.h

This PR extends the existing light sensor driver to support both TSL2563 and TSL2561, the later one used in Seeedstudio's grove digital light sensor and currently tested.

Renamed driver and reworked to support both TSL2561/TSL2563

---

cpu/cc2538/lpm.h

Some arguments passed to the functions disabled with LPM_CONF_ENABLE == 0 could trigger build warnings because they became unused with this configuration option. Disable these functions by using empty static inline functions instead of empty macros, so that the function arguments are always considered by the compiler as used, without having to #if-out code in many places.

cc2538: lpm: Fix build warnings with LPM_CONF_ENABLE == 0

---

platform/galileo/drivers/galileo-gen2-pinmux.c

The pins array in galileo-gen2-pinmux.c:galileo_brd_to_cpu_gpio_pin is
unnecessarily large.  This patch reduces its size.

galileo: Shrink pinmux array

---

apps/rest-engine/rest-engine.c

Without this fix, the timers for periodic resources added after the REST engine was already running were never started. As a result, any observe requests over CoAP were never updated after the initial GET.

rest-engine: Allow adding periodic resources after starting REST engine

---

core/net/ipv6/uip-ds6-nbr.c
core/net/ipv6/uip-ds6-nbr.h
core/net/ipv6/uip-nd6.c
core/net/ipv6/uip6.c
core/net/rpl/rpl-icmp6.c

This PR creates a function called `uip_ds6_nbr_refresh_reachable_state`in `uip-ds6-nbr.c` that refreshes the `Reachable` state of a neighbor. This function should be called (if NDP enabled, i.e., `UIP_ND6_SEND_NA`enabled) when the IPv6 layer or higher receives a message from a neighbor that confirms its reachability, for instance, DAO ACK or ECHO Reply messages. By refreshing the reachability of a neighbor with these messages, we may reduce the amount of traffic that NDP creates.
This PR addresses some of the comments and suggestions mentioned in [#1380](https://github.com/contiki-os/contiki/issues/1380). Let me know your suggestions/improvements.

Refresh nbr reachable state after received IPv6 unicast message

---

core/net/rpl/rpl-timers.c

The two changes are into the condition for the transmission of DIO. The third is commented in the code.
1) The first is to be compliant to the RFC6550 that says: "In RPL, when k (i.e. DIORedundancyConstant) has the value of 0x00, this is to be treated as a redundancy constant of infinity in RPL, i.e., Trickle never suppresses messages). So, when the  instance->dio_redundancy is equal to 0, we can't suppress DIO transmission. This is the way to allow user to disable DIO suppression.
2) If we don't want to set the default route lifetime to infinite, in the case of a very large network (nodes > 40), there will be a high probability that instance->dio_counter is greater than instance->dio_redundancy. In this case the node will not send DIO anymore in the future (more so if this node is the …

Change on DIO trickle timer condition for DIO sending

---

tools/cooja/java/org/contikios/cooja/Simulation.java
tools/cooja/java/org/contikios/cooja/plugins/RadioLogger.java
tools/cooja/java/org/contikios/cooja/plugins/analyzers/IEEE802154Analyzer.java
tools/cooja/java/org/contikios/cooja/plugins/analyzers/PacketAnalyzer.java
tools/cooja/java/org/contikios/cooja/plugins/analyzers/PcapExporter.java

This PR makes PcapExporter write frames with timestamps in the simulated time.
Currently, PcapExporter records timestamps when they are written into a pcap file. Because of that, by looking at the pcap file, you cannot know if packets are sent at your expected timings unless the simulation runs at 100% speed.
Here is an example which shows packets generated and recorded in the simulation of `regression-tests/11-ipv6/01-cooja-ipv6-udp.csc`:
After applying the changes, you will get this:
In both cases above,  timestamps are represented as "Seconds Since Beginning of Capture."  If you select "Date and Time of Day", you will see a result like this:

Fix timestamps of packets recorded in pcap files

---

platform/srf06-cc26xx/contiki-conf.h

RF_CHANNEL added by #1827 will not be applied to CC13xx prop mode since it is checked after the RF_CORE_CONF_CHANNEL definition. This PR moves it above the prop mode section.

Move RF_CHANNEL check in cc13xx/cc26xx such that it applies for cc13xx prop mode 

---

platform/zoul/dev/cc1200-zoul-arch.c

Driver of cc1200 was mistakenly comparing gpio0 pin high status with 1. When the pin is high you should compare it with the pin number.

Fixed checking of the cc1200 GPIO0 pin status.

---

core/net/link-stats.c

This issue happened with the AVR Raven. When used with the Cetic 6lbr border router, the computation of the RPL DAO lifecycle timer was incorrect due to the limited clock_time_t width of the avr-raven and the default, relatively large values, of the DIO default lifecycle and lifecycle unit used by the Cetic 6lbr (30 and 256 respectively).
Do not assume clock_time_t is wide enough on all platforms but cast to the widest type avaliable when doing calculations.

RPL: fix clock_time_t calculations

---

examples/er-rest-example/project-conf.h
platform/cc2530dk/contiki-conf.h
platform/cc2538dk/contiki-conf.h
platform/openmote-cc2538/contiki-conf.h
platform/srf06-cc26xx/contiki-conf.h
platform/zoul/contiki-conf.h

The way to configure the RPL Objective Function to be used has changed and now uses the definitions of  `RPL_CONF_SUPPORTED_OFS` and `RPL_CONF_OF_OCP`. Previously, to change the objective function `RPL_CONF_OF` was used. This definition is not used anymore.
This PR removes the outdated definitions of `RPL_CONF_OF` from several platforms and the `er-rest-example`. Note that this should not affect the platforms because MRHOF is by default the objective function of RPL.
For more information see the appearance of `RPL_CONF_OF`in the code:
https://github.com/contiki-os/contiki/search?utf8=✓&q=RPL_CONF_OF
And also the discussion in issue [#1955](https://github.com/contiki-os/contiki/issues/1955).

Remove definitions of outdated RPL_CONF_OF

---

examples/ipv6/rpl-udp/udp-client.c

In contrast to the sky mote, z1 uses uart0. This leads to a link error when compiling the `rpl-udp/udp-client.c` example.
As the uart is initialized in the corresponding `contiki-<platform>-main.c` file, the corresponding include and initialization in `udp-client.c` are unnecessary and can be removed.

Do not initialize and use the wrong UART (z1)

---

.travis.yml

The Travis test has been failing since 1st of December. https://travis-ci.org/contiki-os/contiki/builds
I found the warning and error in a Travis Job log shown below, that appeared in failed tests:
```
(snip)
[javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
[javac] 1 warning
(snip)
Running test 01-cooja-http-socket-50 with random Seed 1: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/contikios/cooja/Cooja : Unsupported major.minor version 52.0
```
I assume this issue is related to https://github.com/travis-ci/travis-ci/issues/6928. This PR applies [the workaround](https://github.com/travis-ci/travis-ci/issues/6928#issuecomment-264227708) to make Travis green.
Related Issues:
https://github.com/contiki-os/contiki/issues/1965 …

travis: workaround for the Java issue on Travis CI

---

tools/sky/serialdump.c

This PR fixes some issues we found when working with serialdump on our own Contiki fork.
First, it adresses the issue that serialdump sometimes injects newlines while running. This results from not configured `c_iflag` in terminos. Depending on your system it might be configured to replace carriage returns with newlines or vice versa. This results in excessive newlines in the terminal output and wrong output when transferring binary data. While at it I made sure to initialize all `c_iflag` values to make it work reproducible.
Second, it makes serialdump terminate when the serial device gets disconnected, e.g. when the USB cable is unplugged. The original behaviour was that serialdump runs indefinitely without recovering even when replugging the USB device.
Third, serialdump exits cleanly …

Improved serialdump.c

---

core/net/ip/tcp-socket.c
core/net/ip/tcp-socket.h
core/net/ipv6/websocket-http-client.c
core/net/ipv6/websocket-http-client.h
core/net/ipv6/websocket.c
core/net/ipv6/websocket.h
examples/websockets/Makefile
examples/websockets/node/Makefile
examples/websockets/node/example-server.js
examples/websockets/websocket-example.c

This PR adds support for the websocket protocol (RFC 6455).
The websocket protocol is a lightweight framing protocol that runs over HTTP or HTTPS that allows maintaining an active connection over an HTTP/HTTPS transaction. The protocol is primarily intended as a way to communicate between a web browser and a web server, but because it runs over the standard HTTP/HTTPS protocol, it can pass through most firewalls and even many HTTP/HTTPS proxies. Websocket server software exists for most server-side frameworks such as node.js.
The intended use case for this code is for a device behind a Contiki `ip64` NAT gateway to connect to a server on the Internet. It only works with IPv6 and if a client asks to connect to an IPv4 address, the code converts it to an IPv6 address to make it pass through …

Contiki websocket client

---

.travis.yml
core/net/mac/frame802154.c
regression-tests/25-ieee802154/01-panid-handling.csc
regression-tests/25-ieee802154/Makefile
regression-tests/25-ieee802154/README.md
regression-tests/25-ieee802154/code/Makefile
regression-tests/25-ieee802154/code/project-conf.h
regression-tests/25-ieee802154/code/test-panid-handling.c
regression-tests/25-ieee802154/js/01-panid-handling.js

`frame802154_has_panid()`  is not fully compliant with IEEE 802.15.4-2015 [1] for frames of the frame version 0b10. This is because the current implementation is based on Table 2a in IEEE 802.15.4e-2012 [2], which "cannot specify all aspects of how the PAN ID Compression field is to be used", according to a document [3].
For example, in the case where the source address is an extended address, the destination is a short address, and the PAN ID Compression is 0, the Source PAN ID is present as per IEEE 802.15.4-2015. On the other hand, as per IEEE 802.15.4e-2012, the Source PAN ID is not present, which is the case where the Source address is present, the Destination address is present, and PAN ID Compression is 0.
This PR aims for rewriting `frame802154_has_panid()` with reference to Table …

frame802154: comply with IEEE 802.15.4-2015 on PAN ID Field Handling

---

core/net/ipv6/uip-nd6.c
core/net/ipv6/uip-nd6.h

No need to do the unspecified address twice.
```
if(uip_is_addr_unspecified(&UIP_IP_BUF->srcipaddr)) {
/* DAD CASE */
..........
```
```
if(uip_is_addr_unspecified(&UIP_IP_BUF->srcipaddr)) {
/* DAD CASE */
goto discard; 
```
this logic will bring confusion, especially when someone try to understand the implementation of other ND functions (NUD, address resolution)  .

DAD: Remove useless "if" that tests if the source address is unspecified

---

platform/galileo/contiki-main.c

This patch adds a general protection exception handler that prints a
message indicating the faulting instruction and the error code. This is
useful when debugging general protection exceptions.

galileo: Add general protection exception handler

---

cpu/x86/quarkX1000.ld

This patch fixes the section alignment specification in the linker script for
the Intel Quark X1000 SoC so that the UEFI GenFw program generates correct EFI
binaries.  See the added comment in quarkX1000.ld for details.

x86: Fix section alignment for EFI binaries

---

core/cfs/cfs-coffee.c

There is no good reason to leave out this function by default anymore.

Always enable the I/O semantics function in Coffee.

---

tools/cooja/java/org/contikios/cooja/contikimote/ContikiMoteType.java

In some failed tests, e.g. [this one](https://travis-ci.org/contiki-os/contiki/jobs/181329851), the "unmatched single quote" error by xargs is found:
```
==== Files used for simulation (sha1sum) ====
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
FAIL ಠ_ಠ
```
This error is caused by a missing single quotation mark at the end of the file path of a Cooja image in `Cooja.log`. Here is an example:
```
[17:43:16 - main] [ContikiMoteType.java:404] [INFO] - (snip) code/obj_cooja/mtype483.cooja
```
This PR adds the missing single quotation mark as shown below:
```
[17:49:16 - main] [ContikiMoteType.java:404] [INFO] - (snip) code/obj_cooja/mtype740.cooja'
```

Resolve  "unmatched single quote" error in Travis CI failed tests

---

tools/cooja/apps/avrora/src/org/contikios/cooja/avrmote/MicaZMoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/AbstractMspMoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/CC430MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/ESBMoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Eth1120MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp1101MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp1120MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp2420MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp5438MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/SkyMoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Trxeb1120MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Trxeb2520MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/TyndallMoteType.java
tools/cooja/java/org/contikios/cooja/Cooja.java
tools/cooja/java/org/contikios/cooja/CoreComm.java
tools/cooja/java/org/contikios/cooja/contikimote/ContikiMoteType.java
tools/cooja/java/org/contikios/cooja/dialogs/CompileContiki.java
tools/cooja/java/org/contikios/cooja/dialogs/MessageContainer.java
tools/cooja/java/org/contikios/cooja/dialogs/MessageList.java
tools/cooja/java/org/contikios/cooja/dialogs/MessageListText.java
tools/cooja/java/org/contikios/cooja/dialogs/MessageListUI.java

This hopefully fixes a few of the last parts of the COOJA code that still made use of the MessageList with UI that sometimes cause strange class cast exceptions when running in travis. Fixing the parts of the code that cause the problems that is mentioned in PR #1986.

Fixed COOJA to avoid using UI based message list when not using UI.

---

examples/rime/example-collect.c
regression-tests/04-rime/07-sky-collect.csc

Mainly two fixes:
- `04-rime/07-sky-collect.csc`: while a received `seqno` is supposed to be less than 10 in the test script, it doesn't handle a case where  `seqno` is larger than or equal to 10.
- `example-collect.c`: a node sends messages more frequently than expected, every 30 seconds.
Other changes are trivial: indentation fix and shortening time to wait in case of test failure.

Bugfix on regression-tests/04-rime/07-sky-collect.csc

---

platform/zoul/Makefile.zoul

This PR brings back having the baudrate set at the platform's `Makefile`, instead of defaulting to the maximum value in the `cc2538-bsl` script.  Now the default (and tested) baudrate is `460800`.
After testing several batches of platforms, we found the 3% have timing issues, related probably to the on-board PIC governing the flashing process, thus using the default `500000` yielded in errors, whereas other baudrates are OK:
````
$ make TARGET=zoul BOARD=firefly-reva zoul-demo.upload
CC        ../../../cpu/cc2538/./ieee-addr.c
CC        ../../../cpu/cc2538/cc2538.lds
CC        ../../../cpu/cc2538/./startup-gcc.c
CC        zoul-demo.c
LD        zoul-demo.elf
arm-none-eabi-objcopy -O binary --gap-fill 0xff zoul-demo.elf zoul-demo.bin
Flashing /dev/ttyUSB0
Opening port /dev/ttyUSB0, baud …
```

zoul: default cc2538-bsl baudrate to 460800

---

core/net/packetbuf.c
core/net/packetbuf.h

As far as I know, we don't have any API to get the length of remaining data space in `packetbuf`. `packetbuf_remaininglen()` provides this.

Introduce packetbuf_remaininglen()

---

tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/AbstractMspMoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/CC430MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/ESBMoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Eth1120MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp1101MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp1120MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp2420MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Exp5438MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/SkyMoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Trxeb1120MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Trxeb2520MoteType.java
tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/TyndallMoteType.java
tools/cooja/java/org/contikios/cooja/Cooja.java
tools/cooja/java/org/contikios/cooja/Simulation.java

The fix for travis (#1987) made the regular UI mode a bit boring to use since the "quick" mode did not work anymore so that everybody need to click 10 times to start the simulation. This fix re-enabled quick mode when using UI again and make using Cooja. Now any component that is configured at startup should respect `simulator.isQuickSetup()` if it supports quick mode.

fixed so that Cooja can run in quick mode when having UI

---

core/net/mac/contikimac/contikimac.c
core/net/mac/framer-802154.c
core/net/mac/tsch/tsch.c

Here is an excerpt from the code of  `create_frame()` in `framer-802154.c`:
```C
172   /*
173    * Set up the source address using only the long address mode for
174    * phase 1.
175    */
176   linkaddr_copy((linkaddr_t *)&params.src_addr, &linkaddr_node_addr);
177
178   params.payload = packetbuf_dataptr();
179   params.payload_len = packetbuf_datalen();
180   hdr_len = frame802154_hdrlen(&params);
181   if(!do_create) {
182     /* Only calculate header length */
183     return hdr_len;
184   } else if(packetbuf_hdralloc(hdr_len)) {
185     frame802154_create(&params, packetbuf_hdrptr());
```
It always sets `linkaddr_node_addr` to the source address of a newly creating frame at Line 176. It should take the address of `PACKETBUF_ADDR_SENDER` into account.
\<obsolete\>
As far as I know, …

Bugfix on source address setting in framer_802154.create()

---

core/net/mac/csma.c

`free_packet` de-allocates a packet and, if this was the last packet in queue, also frees the neighbor. Hence, we need to store `n->transmissions` before `free_packet` in order to return it safely.

CSMA bugfix: do not use field on a struct that may have been deallocated

---

core/net/mac/tsch/tsch-queue.c

The bug was created when adding adaptive sync traffic with https://github.com/contiki-os/contiki/pull/1741

TSCH bugfix: reset keep-alive timeout when switching time source

---

platform/z1/Makefile.z1
platform/z1/contiki-conf.h
platform/z1/contiki-z1-main.c

This PR add the required includes and commands to use link layer security (llsec) with Zolertia Z1 nodes (copied from Sky platform).

Enable llsec on Z1 nodes

---

core/net/linkaddr.c
platform/minimal-net/contiki-conf.h

This PR adds the ability for the nbr table to use 6-bytes link-layer address. Should improve things for cases where Ethernet is used instead of 802.15.4 (8 or 2 bytes). Also fixed config for minimal-net to use the 6-bytes address as it make use of a TAP (ethernet) to hook into the IP-stack of the host.

added support for 6-bytes link-layer address

---

core/net/mac/tsch/tsch-security.c
core/net/mac/tsch/tsch-security.h

- Add brief explanations for the APIs (`tsch-packet.h`)
- Fix indentation in `tsch-packet.c`
- Change the return type of the APIs from 'int' to 'unsigned int'

Trivial Updates on tsch-security.[ch]

---

platform/avr-zigbit/Makefile.avr-zigbit

I just tried to compile this platform for my Zigbit mote (AT86RF230) here in a hello-world example, but it didn't work.
I reviewed this makefile and found that the request to compile "frame.c" was not necessary and bring up a missing error:
"make: *** No rule to make target `obj_avr-zigbit/frame.o', needed by `contiki-avr-zigbit.a'.  Stop."
Frame.c is already inserted in radio's makefile.
Another problem was the undefined reference created by the missing module "core/net":
"contiki-avr-zigbit.a(sicslowpan.o): In function `input':"
"contiki/examples/hello-world/../../core/net/ipv6/sicslowpan.c:1521: undefined reference to `link_stats_input_callback'"
Both solved now. Hope it helps someone else.

Fixing Avr-Zigbit Makefile not compiling.

---

core/net/rpl/rpl-private.h
core/net/rpl/rpl-timers.c
core/net/rpl/rpl.c

RPL RFC states that if the path lifetime in a DAO transit option is set to 0xFF, it means that the path lifetime is infinite. On the other hand, a lifetime unit of 0xFFFF has not peculiar meaning.
<pre>
Path Lifetime: 8-bit unsigned integer.  The length of time in
Lifetime Units (obtained from the Configuration option) that
the prefix is valid for route determination.  The period starts
when a new Path Sequence is seen.  A value of all one bits
(0xFF) represents infinity.
</pre>

Make RPL route lifetime RFC compliant

---

core/net/rpl/rpl-dag.c

A parent with a rank lower than the DODAG Root rank can not exist by definition and therefore should never be selected.
(Sadly I don't remember which condition triggered the bug, but I guess it does not hurt to add this extra check)

Reject parents with invalid rank

---

examples/zolertia/zoul/project-conf.h

Minor documentation: explicitly specify the light sensor model in the example, so users know how to switch between the TSL2536 and TSL2561

Explicitly specify light sensor model in example

---

core/net/ipv6/uip-ds6-route.c
core/net/ipv6/uip-ds6-route.h

Trivial PR adding the missing uip_ds6_defrt_list_head() function to retrieve the first element of the default router list.

Adding uip_ds6_defrt_list_head()

---

apps/orchestra/orchestra-rule-unicast-per-neighbor-rpl-storing.c
examples/ipv6/rpl-tsch/node.c
regression-tests/11-ipv6/19-cooja-rpl-tsch.csc
regression-tests/11-ipv6/20-cooja-rpl-tsch-orchestra.csc
regression-tests/11-ipv6/21-cooja-rpl-tsch-security.csc

The main change is to use `cooja` mote instead of `z1`.
Two other changes:
- `20-rpl-tsch-orchestra.csc` failed because of a link error for `nbr_routes`. This is resolved by adding a `#if` guard in `orchestra-rule-unicast-per-neighbor-rpl-storing.c`. There could be a better solution.
- The test criteria seem incorrect. They are updated by the following.
```diff
-WAIT_UNTIL(msg.endsWith("Routing links (8 in total):"));
+WAIT_UNTIL(msg.endsWith("Routing links (9 in total):"));
```

TSCH: re-enable TSCH regression tests

---

core/net/rpl/rpl-dag.c
regression-tests/12-rpl/10-rpl-multi-dodag.csc
regression-tests/23-rpl-non-storing/10-rpl-multi-dodag.csc

When updating the dag lifetime, the multiplication constant RPL_DAG_LIFETIME must be used (or it has no use at all :) )

Use RPL_DAG_LIFETIME when computing dag lifetime

---

cpu/cc26xx-cc13xx/rf-core/prop-mode.c
platform/srf06-cc26xx/contiki-conf.h

This pull makes the number of RX buffers for CC13xx prop mode easily configurable via a simple define.
Can be used to fix #1878, possibly also #1933 and #1999.

Make the number of Prop Mode RX Buffers easy to configure

---

cpu/6502/README.md
cpu/6502/lib/config.c
cpu/6502/net/ethernet.c
platform/atarixl/Makefile.atarixl
tools/6502/Makefile

After all there's no momentum for a W5100-based Ethernet solution on the ATARI. So I revert to static linkage of the CS8900A driver as this improves program load times.

Revert to static Ethernet driver for the ATARI.

---

platform/openmote-cc2538/Makefile.openmote-cc2538
platform/openmote-cc2538/README.md

This PR adds support for the OpenMote-CC2538 Rev.A1 board, which uses the CC2538SF23 (256 KB Flash) instead of the CC2538SF53 (512 KB Flash), and the new OpenUSB carrier board, which includes a Texas Instruments CC1200 radio transceiver for 868/915 MHz and has support for automatic bootloading using the cc2538-bsl Python script.

Adding support for OpenMote-CC2538 Rev.A1 and OpenUSB

---

core/dev/slip.c
core/net/ip/slipdev.c
core/net/ip/uip.h
core/net/ip/uip_arch.h
platform/jn516x/lib/slip.c
tools/sky/uip6-bridge/dev/slip.c
tools/stm32w/uip6_bridge/dev/slip.c

Adam Dunkels writes on 2/5/2017 on the Contiki mailing list:
[...] the original idea was that the application could just point the uip_appdata pointer to wherever the data was, but we then changed it so that the data actually had to be copied into the uip_aligned_buf buffer. So, yes, the network device driver should only need to read from this buffer. [...]
This change removes comments on the possibility of uip_appdata pointing somewhere outside the uip_aligned_buf. And it removes code in the SLIP drivers not necessary anymore.
Additionally it makes code in a SLIP driver optional that takes care of the Microsoft-specific CLIENT / SERVER / CLIENTSERVER chat.

Removed artifacts of former uip_appdata handling.

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c

LQI reading was taken with an incorrect offset in the received packet buffer.
Also, the mask for the LQI in the status word should be 0x3f, not 0x7f, as the bit 0x40 refers to the frame filtering status of the packet.

CC26xx IEEE mode radio: fix LQI reading

---

core/net/ip/ip64-addr.c
core/net/ip/ip64-addr.h
core/net/ip64/ip64-dhcpc.c
core/net/ip64/ip64-ipv4-dhcp.c

This PR contains various small updated for the NAT64 modules :
* Support for runtime configuration of the NAT64 prefix used, but default it's still the ::FFFF:/96 prefix
* Removal of the servername in the outgoing DHCP request
* Replace printf() with PRINTF() macros
* Update of the nameserver using the information received in the DHCP reply (Note that the update is only done if no server is already configured or if it was already configured by NAT64)

Various updates for NAT64

---

core/dev/slip.c

Made code rest of the code in the SLIP driver optional that takes care of the Microsoft-specific CLIENT / SERVER / CLIENTSERVER chat.

Made rest of Microsoft-specific chat optional.

---

core/net/mac/tsch/tsch-queue.c
regression-tests/27-tsch/01-cooja-flush-nbr-queue.csc
regression-tests/27-tsch/Makefile
regression-tests/27-tsch/code/Makefile
regression-tests/27-tsch/code/common.c
regression-tests/27-tsch/code/common.h
regression-tests/27-tsch/code/project-conf.h
regression-tests/27-tsch/code/test-flush-nbr-queue.c
regression-tests/27-tsch/js/unit-test.js

This PR doesn't fix anything; just demonstrates a bug in `tsch_queue_flush_nbr_queue()`, which could be related to discussions in Issue/https://github.com/contiki-os/contiki/issues/1766 and Issue/https://github.com/contiki-os/contiki/issues/2105. 
The test introduced by this PR does the following: Please note `QUEUEBUF_CONF_NUM` is set with 1.
1. add one packet by `tsch_queue_add_packet(); should succeed
2. add one more packet by `tsch_queue_add_packet(); should fail because of lack of memory
3. call `tsch_queue_reset()` to invoke `tsch_queue_flush_nbr_queue()`
4. add one packet by `tsch_queue_add_packet(); should succeed
You can find the test code in `regression-tests/27-tsch/code/test-flush-nbr-queue.c`.
Here is the result on the tip of the master branch:
```shell
$ make …
```

TSCH: POC of a bug in tsch_queue_flush_nbr_queue()

---

core/net/mac/frame802154.c
core/net/mac/frame802154.h
platform/jn516x/contiki-conf.h
platform/jn516x/dev/micromac-radio.c

The PR allows the micromac driver of the JN516x platform to use the hardware MAC layer engine provided by NXP.
At first I wanted to have a JN516 framer to create a specific frame for micromac, however there are so many pieces of code that assume that the content of a packetbuf is a real 802.15.4 frame, that the complexity of the change were skyrocketing... Instead, the driver receives the 802.15.4 frame from the RDC layer and dissect it to create the JN516 specific frame and send it to the micromac driver. Similarly, when a frame is received from the microbic layer, the driver recreates a full 802.15.4 frame.
This driver has been tested with NullRDC and ContikiMAC, but without LLSEC, this would require additional changes to support the security header.
By default the hardware mac layer is …

JN516x: Add support for hardware MAC

---

.travis.yml
core/lib/ringbufindex.c
core/lib/ringbufindex.h
regression-tests/03-base/04-ringbufindex.csc
regression-tests/03-base/code/Makefile
regression-tests/03-base/code/project-conf.h
regression-tests/03-base/code/test-ringbufindex.c
regression-tests/03-base/js/04-ringbufindex.js

There are two bugs in `ringbufindex`. They are similar.
While `ringbufindex_peek_put()` is supposed to return the index of the next element to be added, it returns the next index of the adding element. `ringbufindex_peek_get()` returns the next index of the first element.
Travis got green on my account. However, `19-z1-rpl-tsch.csc.flaky` failed, that is one of non-regression tests of TSCH. Since this one fails even on the tip of the master branch, I would say, this PR doesn't cause the failure...
A regression test for `ringbufindex` has been introduced under `regression-tests/03-base` as `04-ringbufindex`. Without the fixes, two of them fails.
```shell
Random seed: 1
549000 node-1 Rime started with address 0.1.0.1.0.1.0.1
549000 node-1 MAC 00:01:00:01:00:01:00:01 sicslowpan/CSMA/nullrdc, …
```

Bugfix in ringbufindex

---

core/net/rpl/rpl-icmp6.c

A debug message output for `RPL_LEAF_ONLY` seems to have been added at a wrong place in `rpl-icmp6.c` by PR https://github.com/contiki-os/contiki/pull/142. Here is the relevant part. While L223 is within the case where the destination is a unicast address, the debug message is talking about "Multicast DIS." 
```C
221 #if RPL_LEAF_ONLY
222       if(!uip_is_addr_mcast(&UIP_IP_BUF->destipaddr)) {
223         PRINTF("RPL: LEAF ONLY Multicast DIS will NOT reset DIO timer\n");
224 #else /* !RPL_LEAF_ONLY */
225       if(uip_is_addr_mcast(&UIP_IP_BUF->destipaddr)) {
226         PRINTF("RPL: Multicast DIS => reset DIO timer\n");
227         rpl_reset_dio_timer(instance);
228       } else {
229 #endif /* !RPL_LEAF_ONLY */
```
The following is my proposal. 
```C
221 …
```

RPL: move a debug message for RPL_LEAF_ONLY to a correct place

---

core/net/ipv6/multicast/uip-mcast6.h

fix a macro related to multicast, which are not user configuration
- RPL_CONF_MULTICAST      -> RPL_WITH_MULTICAST

fix a macro related to multicast, which are not user configuration

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
cpu/cc26xx-cc13xx/rf-core/prop-mode.c

As discussed in #1341, the current CC13xx/CC26xx IEEE mode driver sends `CMD_GET_RSSI` once and returns the RSSI reading uncondtionally. This happens within the `get_rssi()` function.
This logic is broken if `get_rssi()` is called with the radio off. The function will make sure to turn on the radio first, but it does not make sure the RSSI reading is valid, which only happens a number of symbol periods after the radio enters RX. The outcome is that `NETSTACK_RADIO.get_value(RADIO_PARAM_RSSI, ...)` will always return -128 (meaning that RSSI is unavailable) if the radio was off at the time of calling the function.
The same condition affects the prop mode driver.
This commit changes the logic of `get_rssi()`. If `CMD_GET_RSSI` returns an invalid RSSI, we send it again. For unknown reasons, …

Wait for a valid RSSI reading in CC13xx/CC26xx RF drivers

---

platform/srf06-cc26xx/sensortag/board-i2c.c

This limits the busywaiting time of the SensorTag I2C driver as a robustness improvements. We have not experienced any problems with SensorTag as such; however, on a custom platform that does not have all the SensorTag sensors attached the code would occasionally lock up when trying to read a non-attached sensor, leading to a system reboot.
This code was developed as part of the SPHERE project (http://irc-sphere.ac.uk/)

CC26xx SensorTag I2C: add and use LIMITED_BUSYWAIT macro

---

apps/mqtt/mqtt.c

If the MQTT connection is acked by the broker with an error, like when the given client ID is not accepted by the server, the MQTT app recognizes that error, sends a corresponding event to the app user process, but then continues to use the connection as if the connection had been acked without an error, including sending another event to the app user process.

Fix Bug in MQTT App: Refused Connections should not be pursued.

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
cpu/cc26xx-cc13xx/rf-core/rf-core.c

This patch add a fix for the radio driver that limits the time it spends in busywaiting operations. At the moment it can lock up in case turning off the radio Rx mode fails, leading to a reboot of the system.
The patch also makes the radio timer (RAT) handling more robust.
This code was developed as part of the SPHERE project (http://irc-sphere.ac.uk/)

CC26xx IEEE mode driver fixes and robustness improvements

---

platform/avr-rss2/contiki-main.c

This platform did not have the Energest functions to measure CPU rticks, so they were added.

add CPU energest measurements that were lacking in this platform

---

apps/webserver/httpd-cgi.c

this simple change fixes the bug reported in #1541.
../../apps/webserver/httpd.h:63:9: note: expected ‘uip_ip6addr_t’ but argument is of type ‘union uip_ipaddr_t *’

update httpd_cgi to enable the compilation of webserver-ipv6 example

---

apps/webserver/httpd-cgi.c

#1972 removed the declaration of `i` from various locations. In one of those locations it is still needed. This commit puts it back.

Add missing variable declaration

---

core/contiki-default-conf.h

We are trying to set the default MOP in two places:
* `rpl-private.h`: Considers multicast engine selection and correctly allows MOP to be set to 3 when required.
* `contiki-default-conf.h` is not only redundant but also fails to handle situations where RPL multicast is required.
When selecting a multicast engine that requires RPL to be in MOP 3, compilation fails with the error shown in #2143.
This pull simply removes RPL MOP-related configuration from `contiki-default-conf.h` and allows user-provided configuration to take care of things, with `rpl-private.h` setting correct defaults if required.
Fixes #2143

Don't force RPL MOP configuration in contiki-default-conf.h

---

core/net/rpl/rpl-ext-header.c

When running a network in non-storing mode, the RPL root will drop any packets bound for outside the network  because `rpl_update_header()` returns `0` when root in non-storing mode if the destination ip address in the IP buffer isn't in a known DAG.
This adds an additional check to not drop the packet if we're in non-storing mode and the packet destination isn't in a known DAG.  Though this seems to work for me, suggestions for a better way to handle this are welcome.

Don't drop packets bound for outside the RPL mesh in non-storing mode

---

apps/er-coap/er-coap-engine.c
apps/er-coap/er-coap-observe-client.h
apps/er-coap/er-coap-observe.c
apps/er-coap/er-coap.c
apps/er-coap/er-coap.h

Er-coap style cleanup (`uncrustify-fix-style.sh`).
I wanted to clean up the style before contributing new code (https://github.com/contiki-os/contiki/pull/1995).
I also added a missing attribute name in the header.

er-coap: Fix style and add missing `addr` argument

---

cpu/avr/radio/rf230bb/at86rf230_registermap.h
cpu/avr/radio/rf230bb/atmega128rfa1_registermap.h
cpu/avr/radio/rf230bb/atmega256rfr2_registermap.h
cpu/avr/radio/rf230bb/rf230bb.c

including register update for MAC symbol counter. Basic functions for get/set-value
parameter setting added. SPI radios needs to be tested.
modified:   cpu/avr/radio/rf230bb/atmega256rfr2_registermap.h
modified:   cpu/avr/radio/rf230bb/rf230bb.c

Updates for  Atmel radio 

---

examples/sensniff/README.md
examples/sensniff/avr-rss2/avr-rss2-io.h
examples/sensniff/avr-rss2/target-conf.h
platform/avr-rss2/README.md

Title says it. Gives a very useful app with wireshark. Use 500 kbaud (default) or 1 Mbaud which goes well with the UART XTAL at 16Mhz. Tested on AtMega256RFR2.

Adding sensniff support for Atmel via avr-rss2 platform

---

examples/cc26xx/cc26xx-web-demo/httpd-simple.c

When a connection is aborted by the HTTP server while it's still being processed it is possible to hit a null pointer dereference issue by jumping back to a protothread (outputpt) after its httpd_state has been freed. This can be triggered by sending a POST to any form in the CC26xx web demo server using Firefox.
This patch prevents that by zeroing out httpd_state structs before freeing them, thus also clearing the httpd_state->outputpt field.
Tested using Firefox 55.0a1 on a CC2650 LaunchPad.

Zero out httpd_state before deallocating

---

apps/mqtt/mqtt.c
examples/cc26xx/cc26xx-web-demo/mqtt-client.c

The result of converting the IP address of the broker wasn't checked. As a result, if an invalid IP address was entered, the pointer was left uninitialised and the IPv6 address used for connecting was some random data. The function now returns an error. Before connect_to_broker is called, mqtt_register is executed, which memsets conn to 0, making its state 0 (MQTT_CONN_STATE_ERROR). In order to recover from this error state, the extra check was added in the MQTT_CLIENT_STATE_NEWCONFIG state.
This was discovered by @jackmcbride using [CodeSonar](https://www.grammatech.com/products/codesonar).

Check broker IP conversion. Adjust state machine accordingly

---

platform/srf06-cc26xx/sensortag/cc2650/board.h

I make some changes to SPI pin definition for Sensortag so it will be similar to launchpad. I successfully use this to connect ENC28J60 module and run 6lbr (eth-module and external flash works).

Correct SPI pins

---

core/net/mac/tsch/README.md

* Added link to new reference paper, to appear in DCOSS 2017, which details the design and implementation of Contiki's TSCH+6TiSCH;
* Minor updates: 802.15.4-2015 and 6TiSCH.

Updating TSCH readme file

---

platform/srf06-cc26xx/sensortag/hdc-1000-sensor.c

HDC sensor on SensorTag is currently having invalid values when temperature >+42.x degrees Celsius.
The cast to int16_t in this line seems to be at fault:
`*temp = ((double)(int16_t)raw_temp / 65536) * 165 - 40;`
Casting to signed is just not necessary here, as `raw_temp` can never be negative. `raw_temp` of zero corresponds to -40 degrees Celsius, which is the minimal value the sensor can read according to datasheet.

Fix HDC sensor reading conversion

---

core/net/rpl/rpl-icmp6.c
regression-tests/12-rpl/11-rpl-multicast.csc

This PR aims to resolve https://github.com/contiki-os/contiki/issues/2031.
A new regression test, `11-rpl-multicast.csc`, is introduced under `regression-tests/12-rpl/`.
Without the change, the test fails like this:
```shell
$ cd regression-tests/12-rpl
$ make 11-rpl-multicast.testlog
Running test 11-rpl-multicast with random Seed 1: ............../../regression-tests/simexec.sh: line 70: 83680 Aborted                 (core dumped) java -Xshare:on -j
(snip)
#
#
#
```
On the tip of the branch, the test succeeds:
```shell
$ cd regression-tests/12-rpl
$ make 11-rpl-multicast.testlog
Running test 11-rpl-multicast with random Seed 1: ................. OK
```

RPL: fix a bug accessing an uninitialized pointer

---

core/net/ip/resolv.c
core/net/ipv6/websocket.c

This fixes some potential issues with strings being copied using strncpy, which causes char arrays that are used as strings later on to be non-terminated.
I have also changed the typecasts in the tolower function calls to unsigned char.
Fixes #2185

Fix potentially unterminated strings

---

core/net/mac/frame802154.c
core/net/rpl/rpl-icmp6.c
cpu/cc26xx-cc13xx/rf-core/ieee-mode.c

This fixes several potentially unitinitialized variables found by codesonar.

Fix several uninitialized variables

---

apps/er-coap/er-coap-observe.c

Currently Contiki generates Observe notifications with the observe counter going up to 4 bytes. Yet RFC 7641(https://tools.ietf.org/html/rfc7641) clearly shows that the Observe option may have length from 0 to 3 bytes.
This causes problems for out application because with 4 byte observe option some packets will get too large to be sent over the air.

Keep CoAP 'observe' option length <= 3 bytes

---

cpu/cc26xx-cc13xx/rf-core/ieee-mode.c

This commit changes the logic of `get_cca_info()` in the CC26xx IEEE mode driver. We now use the command's return status bits to determine whether the radio's CCA monitoring function has completed, instead of drawing conclusions based on RSSI readings.
The logic that dictates whether CCA will signal an IDLE or BUSY channel is unchanged.

Use `ccaInfo.ccaState` to decide whether CCA is complete

---

examples/cc26xx/cc26xx-web-demo/httpd-simple.c
examples/cc26xx/cc26xx-web-demo/mqtt-client.c

This commit implements address validation for the broker address in the MQTT configuration page of the CC26XX web demo example. Additionally, the Type ID, Org ID, Auth Token, Command Type and Event Type ID fields have quotes escaped (" -> &quot;) to prevent XSS/broken page issues when displaying user-sourced input in HTML input fields.

Validate MQTT broker IP and escape quotes when displaying

---

cpu/avr/radio/rf230bb/rf230bb.c
cpu/avr/radio/rf230bb/rf230bb.h
examples/rf_environment/Makefile
examples/rf_environment/README.md
examples/rf_environment/project-conf.h
examples/rf_environment/rf_environment.c

Missing set/get CCA functions for Atmel radio. 
-------------------------------------------------------
Also rf_environment example.
Non-intrusive monitoring of the RF-environment
-----------------------------------------------------------
rf_environment runs the clear channel assessment (CCA) test over all 802.15.4 channels and reports stats per channel. The CCA test is run for different CCA thresholds from -60dBm to -90dBm. CCA is
a non-destructive for the rf-environment as it's just listens. Best and worst channel is printed as average rf activity. Probability for not passing a CCA check in percent per channel. 3-minute samples.

Atmel radio; Support for RADIO_PARAM_CCA_THRESHOLD plus rf_environment example

---

apps/er-coap/er-coap.c

This should address the issues reported in #2238, #2239 and #2240. Thanks to Stephan Zeisberg for reporting the issues and for the excellent test cases.

Added boundary checks when parsing CoAP packets.

---

cpu/avr/radio/rf230bb/atmega128rfa1_registermap.h
cpu/avr/radio/rf230bb/atmega256rfr2_registermap.h
cpu/avr/radio/rf230bb/rf230bb.c
cpu/avr/radio/rf230bb/rf230bb.h
examples/avr-rss2/AES128HW_test/AES128HW_test.c
examples/avr-rss2/AES128HW_test/Makefile
examples/avr-rss2/AES128HW_test/README.md
examples/avr-rss2/AES128HW_test/project-conf.h

Support for the builtin Atmel radio AES128 engine. Did this code many moons ago but it's now updated for Contiki. Integration to security layers and stuffing MIC in is needed. Atmel crypto engine is pretty generic and can be used for several purposes. A small test-program is in included.

Atmel radio AES128 crypto engine support.

---

cpu/cc26xx-cc13xx/dev/cc26xx-uart.c

This PR removes the requirement for both UART TX and RX to be set, thus adding support for boards which only have one or the other.

CC26xx/CC13xx: Support uni-directional UART

---

core/net/ipv6/websocket-http-client.c

Explicitly terminate the field strings when registering a websocket client.
Spotted by @ArthurTaggart using [Coverity](https://www.synopsys.com/software-integrity/resources/datasheets/coverity.html).

Terminate websocket strings

---

platform/srf06-cc26xx/sensortag/bmp-280-sensor.c

The CALIB_DATA_SIZE was set to 24 while the actual structure size is 28.
Because of this, some other variables in the module were overwritten after the sensor read operation. This, for example, prevented reading the temperature immediately after the pressure (or vice versa), because the "enabled" static variable contained garbage.

cc26xx/sensortag: Use correct calibration data structure size

---

tools/6502/Makefile

The Apple][ mouse driver file became obsolete with https://github.com/oliverschmidt/contiki/commit/91beb8670f9c8000330c11e54ed46c8e5ac4049f.

Removed Apple][ mouse driver file.
