examples/ipv6/native-border-router/README.md
examples/ipv6/slip-radio/README.md

This is just some documentation to clarify how these examples relate.

added some documentation of native-border-router and slip-radio relationship

---

core/net/ipv4/uip.c
core/net/rpl/rpl.c

Very minor grammar / spelling edits to comments

Update rpl.c and uip.c (in ipv4)

---

core/cfs/cfs-coffee.c

This PR corrects the indentation in various code fragments and removes some unnecessary white space.

Fix some code style issues in Coffee.

---

core/net/rpl/rpl-dag.c

No other purpose than save a little bit of space

Do not use rpl_add_dag when RPL is used with a single dag per instance

---

examples/z1/Makefile
examples/z1/test-sht25.c
platform/z1/Makefile.common
platform/z1/dev/sht25.c
platform/z1/dev/sht25.h

Included the Sensirion SHT25 Temperature and Humidity sensor driver, and a test example.

Added SHT25 sensor

---

cpu/avr/radio/rf230bb/rf230bb.h

Very simple change to include guard so that it matches the filename it appears in.

Update #if guard to match header filename

---

cpu/cc2538/dev/gpio.c
cpu/cc2538/dev/gpio.h

This PR factors out duplicated ISR code, and it fixes several cases of missed interrupts.
This fixes issues #921 and #1019.
@g-oikonomou: This has been build-tested, but *not* runtime-tested.
@darkopetrovic: Please test that this works for your use case.

cc2538: gpio: Improve and fix IRQ management

---

cpu/cc2538/dev/cc2538-rf.c

This improves the "if we were off, turn back off" logic in the RF driver.
This will prevent the RF from lingering in the RX state for longer than intended, and will thus reduce overall average energy consumption.
This is in response to the discussion with @darkopetrovic - I'd appreciate if you could have a look and verify this fix.
Fixes #823

Use local variable to store RF on/off state

---

core/lib/petsciiconv.c
core/net/ip/resolv.c
core/net/ip/slipdev.c
core/net/ip/uip-nameserver.c
core/net/ipv6/uip-nd6.c
core/net/mac/contikimac/contikimac.c
core/net/mac/nullrdc.c
examples/ipv6/rpl-collect/udp-sender.c

This PR simply fixes some compiler warnings.

Fixed a number of compiler warnings

---

core/net/rpl/rpl-dag.c

addresses https://github.com/contiki-os/contiki/pull/1053#issuecomment-101472729

rpl_print_neighbor_list(): cast clock_time_t to unsigned for portable printout

---

.travis.yml
regression-tests/20-compile-tools/Makefile
tools/Makefile
tools/stm32w/Makefile

Currently fails due to unmerged https://github.com/contiki-os/contiki/pull/1048

Add regression-test for tools

---

core/dev/spi.h
core/sys/cc.h
cpu/cc2538/dev/spi.c
cpu/cc2538/dev/ssi.h
cpu/cc2538/spi-arch.h
platform/cc2538dk/dev/board.h

Added support for two SPI ports for cc2538 similar to uart modul.
This is a re-pull request for the already approved pull request based on a new branch in my own fork. Hopefully i don't create to much confusion...

CC2538: added support for SSI1

---

core/net/ip/resolv.c
core/net/mac/contikimac/contikimac.c
core/net/rime/collect-neighbor.c
core/net/rime/collect.c
cpu/cc2538/usb/usb-arch.c

Toolchain used:
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150303
(release) [ARM/embedded-4_9-branch revision 221220]

cc2538: examples: Fix build warnings

---

core/lib/ccm-star.c
core/lib/ccm-star.h
core/net/llsec/ccm-star-packetbuf.c
core/net/llsec/ccm-star-packetbuf.h
core/net/llsec/noncoresec/noncoresec.c
examples/llsec/ccm-star-tests/encryption/tests.c
examples/llsec/ccm-star-tests/verification/tests.c

also introduced a convenience module for LLSEC modules that automatically construct an appropriate IV to pass in

generalised CCM module into lib

---

core/net/mac/contikimac/contikimac.c

This PR adds support for S/W ACK TX in ContikiMAC.
This is handy when the radio cannot send H/W ACKs. This is quite common for sub-ghz operation.

Implement TX of S/W ACKs with ContikiMAC

---

README.md

This should keep 3.0 green even if master gets temporarily red :)

Travis icon in README.md: show build status of branch release-3-0

---

platform/wismote/Makefile.wismote
platform/wismote/contiki-wismote-main.c
platform/wismote/dev/xmem.c
platform/wismote/platform-conf.h

Contiki 2.7 does not have driver support for WISMOTE external flash. I have updated the driver of external flash for WISMOTE platform.

Wismote external flash driver

---

core/lib/aes-128.c

@akdjka's fix for https://github.com/contiki-os/contiki/issues/1147 as a PR.
Looks legit to me, even though I don't think this gives 100% constant time guarantee (that being compiler- and platform-dependent)

galois_mul2 conditional-free implementation

---

tools/cooja/java/org/contikios/cooja/SafeRandom.java
tools/cooja/java/org/contikios/cooja/Simulation.java

This ensures that simulations are reproducable.
This is the aftermath of https://github.com/contiki-os/contiki/pull/810 and https://github.com/contiki-os/contiki/pull/821
Will rebase this, once #810 is merged.

Make Random simulation thread safe

---

cpu/avr/radio/rf230bb/rf230bb.c

Avoids packet reordering in cases when RF230_CONF_RX_BUFFERS > 1.
Until now, the code moved the cursor forward to the next slot only if the reception of a packet was successful. That lead to continuous packet reception reordering after once seeing a corrupt packet. The patch simply moves to the next packet even if the current packet cannot be successfully received.
It also looks like that the RS230bb driver enables automatic CRC,  but does not check is on reception. I got a lot of corrupt packets up to Rime level. Probably can be worked around by enabling the software checksum. I did not attempt to verify or patch that.

Atmel 230bb: always increase the rx frame ringbuffer cursor in rf230_read()

---

cpu/mc1322x/clock.c
cpu/mc1322x/lib/include/crm.h
cpu/mc1322x/lib/include/nvm.h
cpu/mc1322x/lib/nvm.c

Learned from pull request #594. Added some new functions for hardware usage on mc1322x.

Added mc1322x functions

---

.travis.yml
examples/econotag-flash-test/Makefile
examples/econotag-flash-test/README
examples/econotag-flash-test/econotag-flash-test.c
examples/econotag-flash-test/econotag-flash-test.cfg
examples/econotag-flash-test/econotag-flash-test.h
platform/econotag/apps/flash/Makefile.flash
platform/econotag/apps/flash/flash.c
platform/econotag/apps/flash/flash.h
regression-tests/15-compile-arm-apcs-ports/Makefile
tools/blaster/Makefile
tools/blaster/README
tools/blaster/blaster.c
tools/blaster/blaster.h

App/Tool/Example for usage of additional flash on econotag/mc1322x.
Depends on / Includes #685, so you are able to accept only new mc1322x functions.

App/Tool/Example for usage of additional flash on econotag/mc1322x

---

core/net/rime/route.c

Actually contiki removes the first added (FIFO) rime route if any module tries to add a new route to a full routing table. For large networks the route discovery module (used by the mesh module) saves many newly learned routes. But this amount of newly learned routes may not be as relevant as already existing routes the node is aware of.
With large sensor networks my most important routes have been constantly removed because of many learned "useless" route discovery routes, triggering route discovery indefinitely.
The suggested change will change the route deletion strategy from FIFO to LRU so any actively used routes which are refreshed by ``route_refresh()`` are not deleted "by accident". If neither route is refreshed by the application the LRU implementation is completely backwards …

LRU deletion strategy for rime routes

---

tools/tunslip6.c

An additional important thing is to be able to reliably see console messages from contiki which may be interspersed into the code IP packets.

some additions to tunslip6 to make it a bit easier to diagnose problems with it

---

core/sys/pt-sem.h

Using PT_SEM_SIGNAL() within an interrupt service routine can cause a race condition if the counter decrement is not an atomic operation. Representing the semaphore count as a difference between two separate counters prevents such a race condition from occurring and makes PT_SEM_SIGNAL() interrupt-safe.

Make protothread semaphores interrupt-safe.

---

core/net/packetbuf.c

Protection against possible buffer overflow

Protection against possible buffer overflow

---

cpu/native/net/linuxradio-drv.c
cpu/native/net/linuxradio-drv.h
platform/minimal-net/Makefile.minimal-net
platform/minimal-net/contiki-conf.h
platform/native/Makefile.native
platform/native/contiki-conf.h

Fork off the closed https://github.com/contiki-os/contiki/pull/492

Basic NETSTACK_CONF_RADIO based on kernel 802.15.4

---

platform/minimal-net/contiki-conf.h

Based on https://github.com/contiki-os/contiki/commit/bd1b7d981438fb589e27ad6bf5c818175db2eac7#commitcomment-13486760

Fixed detection of windows-native

---

.gitignore

https://github.com/contiki-os/contiki/commit/4db4b7fcf208a100edc057f93a45b32063c9f6bf added .zip files so ignore them like all other build artifacts.

Have Git ignore .zip files.

---

regression-tests/Makefile.compile-test

addresses https://github.com/contiki-os/contiki/pull/1327#issuecomment-157502562

Compile-test: show make variables in log output

---

core/net/rime/chameleon-bitopt.c

When testing Contiki on a big endian platform we discovered that Rime protocols do not work correctly even both communicating nodes are based on a big endian platform. This patch fixes this problem allowing the Rime attributes to be serialized correctly.
This patch does just what it promises, in particular it does not address the interoperability between little-endian and big-endian nodes using Rime.

Fix Rime attribute serialization in chameleon-bitopts for big endian systems

---

examples/jn516x/rpl/border-router/slip-bridge.c
platform/jn516x/dev/micromac-radio.c
platform/jn516x/dev/rtimer-arch.h

update from https://github.com/EIT-ICT-RICH/contiki

JN516x: minor fixes

---

core/net/mac/contikimac/contikimac.c

Made ContikiMAC more configurable (on uknoblic behalf)

---

core/net/mac/contikimac/contikimac.c

Fixes missing tabs in previous commit

Replaced tabs leftover in previous commit

---

.gitignore

Fixing a leftover from a previous commit

Reverting change in .gitignore

---

platform/avr-atmega128rfa1/contiki-conf.h
platform/avr-raven/contiki-conf.h
platform/avr-ravenusb/contiki-conf.h
platform/avr-rcb/contiki-conf.h
platform/avr-zigbit/contiki-conf.h
platform/micaz/platform-conf.h

AVR platforms: use 32 bit clock_time_t

---

core/net/rpl/rpl-dag.c

This makes sure newly added DAGs are properly initialized. Fixes Travis test 12-rpl/10-rpl-multi-dodag.csc.
Upstream:
```
Running test 10-rpl-multi-dodag with random Seed 1: .................. OK
Running test 10-rpl-multi-dodag with random Seed 2: .................. OK
Running test 10-rpl-multi-dodag with random Seed 3: .................. OK
Running test 10-rpl-multi-dodag with random Seed 4: .................. OK
Running test 10-rpl-multi-dodag with random Seed 5: ..................FAIL
Running test 10-rpl-multi-dodag with random Seed 6: .................. OK
Running test 10-rpl-multi-dodag with random Seed 7: ..................FAIL
Running test 10-rpl-multi-dodag with random Seed 8: .................. OK
Running test 10-rpl-multi-dodag with random Seed 9: .................. OK
Running …
```

RPL multiple DAG bugfix

---

dev/enc28j60/enc28j60.c

See the commit messages for details.

enc28j60: Fixes and improvements

---

cpu/cc2538/dev/bignum-driver.c
cpu/cc2538/dev/bignum-driver.h
cpu/cc2538/dev/ecc-algorithm.c
cpu/cc2538/dev/ecc-algorithm.h
cpu/cc2538/dev/ecc-curve.c
cpu/cc2538/dev/ecc-driver.c
cpu/cc2538/dev/ecc-driver.h
cpu/cc2538/dev/udma.c
examples/cc2538dk/pka/Makefile.target
examples/cc2538dk/pka/ecc-ecdh.c
examples/cc2538dk/pka/ecc-sign.c
examples/cc2538dk/pka/ecc-verify.c
regression-tests/18-compile-arm-ports/Makefile

Fix a few minor build issues, including build testing. See the commit messages.

cc2538: Fix build issues

---

cpu/cc26xx-cc13xx/rf-core/rf-core.c

As discussed in #1294, every time a CC13xx/CC26xx RF interrupt fires, we clear all interrupt flags unconditionally. This may result in missed events. This patch fixes this bug by clearing only the flag that triggered the interrupt in the first place.
Fixes #1294

Clear CC26xx/CC13xx interrupt flags selectively

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/project-conf.h
examples/zolertia/zoul/test-bmp085.c
examples/zolertia/zoul/test-tsl2563.c
platform/zoul/dev/bmp085.c
platform/zoul/dev/bmp085.h
platform/zoul/dev/tsl2563.c
platform/zoul/dev/tsl2563.h
platform/zoul/dev/zoul-sensors.h
platform/zoul/firefly/board.h
platform/zoul/remote/board.h

This PR adds support for the BMP085 digital barometric sensor (atmospheric pressure and temperature, soon altitude as well).  It depends on #1446.

BMP085 barometric sensor for the RE-Mote platform

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/project-conf.h
examples/zolertia/zoul/test-bmp085.c
examples/zolertia/zoul/test-sht25.c
examples/zolertia/zoul/test-tsl2563.c
platform/zoul/dev/bmp085.c
platform/zoul/dev/bmp085.h
platform/zoul/dev/sht25.c
platform/zoul/dev/sht25.h
platform/zoul/dev/tsl2563.c
platform/zoul/dev/tsl2563.h
platform/zoul/dev/zoul-sensors.h
platform/zoul/firefly/board.h
platform/zoul/remote/board.h

This PR fixes the SHT25 temperature and humidity driver and extends its available features, such as changing the resolution, checking for a low-voltage alarm, etc.
The PR depends on #1449.

Fixes and enhancements for the SHT25 sensor

---

examples/jn516x/rpl/common-conf.h
examples/jn516x/rpl/node/node.c

The jn516x rpl example was added before merging TSCH. This PR adds TSCH to the examples.

Adding TSCH to examples/jn516x/rpl

---

examples/zolertia/z1/ipv6/z1-websense/Makefile
examples/zolertia/z1/ipv6/z1-websense/Makefile.target
examples/zolertia/z1/ipv6/z1-websense/README.md
examples/zolertia/z1/ipv6/z1-websense/example-z1-websense.csc

This PR fix the broken `z1-websense` example and its cooja simulation

Fix z1-websense example

---

platform/zoul/dev/weather-meter.c

This PR includes a simple change from `rtimer` to `ctimer` as it was breaking up `ContikiMAC` when enabled, as `rtimer` is reserved.

Weather meter: replaced rtimer by ctimer as it was breaking contikimac

---

apps/json/json.h
apps/json/jsontree.c
apps/json/jsontree.h

* add JSONTREE_CONF_PRETTY option
* add uint type
* add int pointer types

jsontree: new features

---

examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-zonik.c
platform/zoul/dev/zonik.c
platform/zoul/dev/zonik.h

Drivers for the Zonik sonometer sensor. Added drivers and test application.

Added Zolertia Zonik sound sensor test and drivers

---

cpu/6502/net/w5100.S

If the setup of socket 0 to 3 with 4+2+1+1KB is detected then the W5100 is _not_ initialized, otherwise it does set up socket 0 and 1 with 4KB each. Either way socket 0 is used - now with 4KB instead of 8KB as before.

Added compatibility with W5100 shared access.

---

core/net/packetbuf.c
core/net/packetbuf.h
platform/avr-raven/contiki-conf.h
platform/avr-ravenusb/contiki-conf.h
platform/avr-rcb/contiki-conf.h
platform/avr-zigbit/contiki-conf.h

This pull request removes unnecessary `packetbuf` functions.

packetbuf cleanup

---

core/cfs/cfs-coffee.c

The protected memory structure was used by the sensornet checkpointing module to protect Coffee's internal structures while performing checkpointing. Since sensornet checkpointing has been removed, there is no longer a need for this extra functionality in Coffee.

Remove protected memory from Coffee

---

core/net/ip/tcpip.c
core/net/ipv6/uip6.c

Nothing but spacing changes: https://github.com/contiki-os/contiki/pull/1618/files?w=1

Fixes indent in tcpip.c and uip6.c

---

core/net/mac/rdc.h

This is a fix for the issue described in #1425.

Fix for "LLSEC802154_CONF_ENABLED undefined"

---

apps/oma-lwm2m/lwm2m-engine.c

This fixes JSON parsing errors when reading entire instances from the Leshan example server web GUI.
http://dev_devtoolkit.openmobilealliance.org/IoT/LWM2M10/doc/TS/index.html#!Documents/json.htm

oma-lwm2m: Use sv for string value, bv for boolean

---

apps/orchestra/orchestra-rule-eb-per-time-source.c
apps/orchestra/orchestra-rule-unicast-per-neighbor.c

This PR includes a number of fixes to Orchestra, including a fix to https://github.com/contiki-os/contiki/issues/1671

Various Orchestra fixes

---

core/net/mac/tsch/tsch-log.c

This fixes a bug in the logging of TSCH security level

Fix tsch-log bug

---

apps/oma-lwm2m/lwm2m-engine.c

~~depends on #1651~~ - merged
This simplifies using Copper for debugging LWM2M resources since it lets us look at the variables in plain text.
Also changes the decision to use the provided Accept header instead of Content-Format header to determine if we are sending an APPLICATION_LINK_FORMAT or LWM2M_JSON response for dumping entire service instances.

oma-lwm2m: Use Accept header to determine writer object

---

examples/openmote-cc2538/openmote-demo.c
platform/openmote-cc2538/dev/adxl346.c
platform/openmote-cc2538/dev/adxl346.h
platform/openmote-cc2538/dev/max44009.c
platform/openmote-cc2538/dev/max44009.h
platform/openmote-cc2538/dev/sht21.c
platform/openmote-cc2538/dev/sht21.h

This PR adapts the OpenMote-CC2538 sensor drivers to the Contiki sensor API.

Adapted OpenMote-CC2538 sensor drivers to Contiki sensor API.

---

examples/rssi-scanner/rssi-scanner-cc2420.c

Fixes  #1664 
(Tested using sky platform)

Fixed rssi-scanner example

---

apps/oma-lwm2m/Makefile.oma-lwm2m
apps/oma-lwm2m/lwm2m-engine.c
apps/oma-lwm2m/lwm2m-json.c
apps/oma-lwm2m/lwm2m-json.h

A minimal JSON writer for LWM2M resources.
Depends on #1652, ~~#1651~~

oma-lwm2m: Add JSON writer

---

core/net/mac/tsch/tsch-adaptive-timesync.c
core/net/mac/tsch/tsch-conf.h
core/net/mac/tsch/tsch-queue.h
core/net/mac/tsch/tsch-rpl.c
core/net/mac/tsch/tsch-slot-operation.c
core/net/mac/tsch/tsch.c

This patch fixes some minor bugs and prepares TSCH code for a port to the CC2650 platform.

TSCH enhancements

---

core/dev/slip.c

Currently, the slip buffer can contain only one pending packet, which means that if there is a burst of packets coming from the BR all but the first are discarded. This PR transforms the slip buffer into a circular buffer able to store an unlimited number of packets (as long as they fit into the buffer)

Support more than one pending slip message

---

examples/ipv6/rpl-border-router/border-router.c

With this PR, the BR will include the list of (RPL non-storing) links in its HTTP response.

RPL border HTTP server: support for non-storing

---

platform/atarixl/Makefile.atarixl
platform/atarixl/contiki-conf.h
tools/6502/Makefile

- platform/atarixl/Makefile.atarixl: put two more objects into high memory
- platform/atarixl/contiki-conf.h: define WWW_CONF_WGET_EXEC
- tools/6502/Makefile: add 'clean' target; remove unused CONTIKI define

Some 6502 target changes

---

cpu/cc26xx-cc13xx/lpm.c

This addresses all three points of issue #1736

CC26xx: fix a regression in and refactor LPM code

---

platform/srf06-cc26xx/sensortag/board-i2c.c

Fixes I2C multiple-write bug, as reported by Ron Segal: https://sourceforge.net/p/contiki/mailman/message/34633862/
plus minor opt.

Cc26xx/cc13xx I2C fix

---

core/net/mac/mac-sequence.c

Without a lifetime, there are cases where node B receives from A with seqno N, then does not hear anything for an arbitrary period of time, and then hears a new, different packet with seqno N again (seqnos wrap quick given they are a single byte).
This PR adds a configurable lifetime for received seqnos in history.

mac-seqno: add a lifetime to sequence numbers in history

---

cpu/cc2538/dev/pwm.c
cpu/cc2538/dev/pwm.h
examples/cc2538-common/test-pwm.c
examples/zolertia/zoul/Makefile
examples/zolertia/zoul/test-servo.c
platform/zoul/dev/servo.c
platform/zoul/dev/servo.h

This PR adds a basic servo driver using the PWM library
[![](https://img.youtube.com/vi/LMnSEBkATvA/0.jpg)](https://www.youtube.com/watch?v=LMnSEBkATvA)
There are still suggestions open in https://github.com/contiki-os/contiki/issues/1505 to improve the PWM driver, but this PR doesn't significantly prevents so.

Zoul: generic servo driver

---

dev/cc2520/cc2520.c

In CC2520 datasheet (http://www.ti.com/lit/ds/symlink/cc2520.pdf), according to section 5.7 
Real RSSI = Register value - offset
where offset = 76 dBm

CC2520: Added offset to calculate correct RSSI value

---

core/net/mac/tsch/tsch-slot-operation.c
core/net/mac/tsch/tsch-slot-operation.h
core/net/mac/tsch/tsch.c

A series of minor fixes / new features as described in the commit logs

TSCH minor enhancements

---

cpu/cc253x/dev/uart1.c

including "sfr-bits.h" to define PERCFG_U1CFG, and UCSR_MODE.

update uart1.c to include Special function registers bits definitions

---

examples/cc2538-common/Makefile
examples/cc2538-common/test-uart.c

A quick program for testing the UART1 on the RE-mote (Zoul) platform which can be used to interface with sensor having UART interface.

Zoul UART example

---

core/net/rpl/rpl-dag.c

This is as per RFC 6550, section 9.6: in non-storing mode, only the root triggers DTSN updates.

RPL non-storing: more conservative DTSN update

---

core/net/mac/tsch/README.md
examples/ipv6/rpl-tsch/node.c
platform/cooja/rtimer-arch.h

- Two updates to resolve issues arising when running examples/ipv6/rpl-tsch/rpl-tsch-cooja.csc.
- One update on README.md of TSCH
- add cooja as supported platform
- correct Rx mode requirements

Miscellaneous updates for tsch-cooja-mote

---

platform/zoul/contiki-conf.h

Added NullRDC and ContikiMAC timings for Zolertia RE-Mote.

---

platform/zoul/README.md
platform/zoul/firefly-reva/README.md

Updated documentation and fixed broken links

Minor documentation fixes

---

tools/zolertia/motelist-zolertia

Updates the expected motelist string

Orion: update motelist string

---

core/net/ipv6/uip-nd6.h

Trivial PR allowing user configuration of all the NDP parameters related to Router Advertisement.

Make all NDP configuration parameters user configurable

---

cpu/avr/radio/rf230bb/halbb.c
cpu/avr/radio/rf230bb/rf230bb.c

More get/set_value fixes and get_obj RADIO_PARAM_LAST_PACKET_TIMESTAMP support.
modified:   cpu/avr/radio/rf230bb/halbb.c
modified:   cpu/avr/radio/rf230bb/rf230bb.c

Updates for Atmel radio part II

---

examples/cc26xx/cc26xx-web-demo/cc26xx-web-demo.c
examples/cc26xx/cc26xx-web-demo/cc26xx-web-demo.h
examples/cc26xx/cc26xx-web-demo/coap-server.c
examples/cc26xx/cc26xx-web-demo/project-conf.h
examples/cc26xx/cc26xx-web-demo/resources/res-sensors.c

Add ADC reading (from DIO23 pin on CC26xx/CC13xx) example to cc26xx-web-demo and connect it to COAP/MQTT.

add ADC example to cc26xx-web-demo

---

.travis.yml

This pull fixes the current travis build failure by changing the PPA for Doxygen

Fix Doxygen PPA location

---

examples/cc26xx/cc26xx-web-demo/httpd-simple.c
examples/cc26xx/cc26xx-web-demo/mqtt-client.c

Reverts contiki-os/contiki#2213

Revert "Validate MQTT broker IP and escape quotes when displaying"

---

core/net/rpl/rpl-dag-root.c
core/net/rpl/rpl-dag.c
core/net/rpl/rpl-ext-header.c
core/net/rpl/rpl-icmp6.c
core/net/rpl/rpl-nbr-policy.c
core/net/rpl/rpl.c

Cleans up some annoying anomalies I noticed while debugging RPL.

Minor cleanup to RPL debug output

---

dev/pms5003/README.pms5003
dev/pms5003/pms5003-sensor.c
dev/pms5003/pms5003-sensor.h
dev/pms5003/pms5003.c
dev/pms5003/pms5003.h
platform/avr-rss2/dev/i2c.c
platform/avr-rss2/dev/pms5003-arch.c
platform/avr-rss2/dev/pms5003-arch.h

Support for UART and I2C communication, with configurable duty cycling. Works also with PMS 3003 (and probably other PMS X003 sensors).
(Previously submitted as pull request #2223)

Driver for Plantower PMS 5003 dust sensors. 
